# terrascript/resource/terra-farm/virtualbox.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:30:30 UTC)
import terrascript


class virtualbox_vm(terrascript.Resource):
    pass


__all__ = [
    "virtualbox_vm",
]
