# terrascript/resource/terra-farm/xenorchestra.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:31:20 UTC)
import terrascript


class xenorchestra_acl(terrascript.Resource):
    pass


class xenorchestra_cloud_config(terrascript.Resource):
    pass


class xenorchestra_resource_set(terrascript.Resource):
    pass


class xenorchestra_vm(terrascript.Resource):
    pass


__all__ = [
    "xenorchestra_acl",
    "xenorchestra_cloud_config",
    "xenorchestra_resource_set",
    "xenorchestra_vm",
]
