# terrascript/sql/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class sql_migrate(terrascript.Resource):
    pass


class sql_migrate_directory(terrascript.Resource):
    pass
