# terrascript/provider/nrkno/lastpass.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:12 UTC)

import terrascript

class lastpass(terrascript.Provider):
    '''Terraform Lastpass provider
    
    '''
    __description__ = "Terraform Lastpass provider"
    __namespace__ = "nrkno"
    __name__ = "lastpass"
    __source__ = "https://github.com/nrkno/terraform-provider-lastpass"
    __version__ = "0.5.3"
    __published__ = "2021-07-23T15:13:43Z"
    __tier__ = "community"
    

__all__ = ["lastpass"]
