# terrascript/data/cappyzawa/christmas_tree.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:08 UTC)
import terrascript


class christmas_tree(terrascript.Data):
    pass


__all__ = [
    "christmas_tree",
]
