# terrascript/data/cappyzawa/concourse.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:14:28 UTC)
import terrascript


class concourse_team(terrascript.Data):
    pass


__all__ = [
    "concourse_team",
]
