# terrascript/hsdp/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class hsdp_cdl_data_type_definition(terrascript.Resource):
    pass


class hsdp_cdl_export_route(terrascript.Resource):
    pass


class hsdp_cdl_label_definition(terrascript.Resource):
    pass


class hsdp_cdl_research_study(terrascript.Resource):
    pass


class hsdp_cdr_org(terrascript.Resource):
    pass


class hsdp_cdr_subscription(terrascript.Resource):
    pass


class hsdp_container_host(terrascript.Resource):
    pass


class hsdp_container_host_exec(terrascript.Resource):
    pass


class hsdp_dicom_gateway_config(terrascript.Resource):
    pass


class hsdp_dicom_object_store(terrascript.Resource):
    pass


class hsdp_dicom_remote_node(terrascript.Resource):
    pass


class hsdp_dicom_repository(terrascript.Resource):
    pass


class hsdp_dicom_store_config(terrascript.Resource):
    pass


class hsdp_function(terrascript.Resource):
    pass


class hsdp_iam_application(terrascript.Resource):
    pass


class hsdp_iam_client(terrascript.Resource):
    pass


class hsdp_iam_email_template(terrascript.Resource):
    pass


class hsdp_iam_group(terrascript.Resource):
    pass


class hsdp_iam_mfa_policy(terrascript.Resource):
    pass


class hsdp_iam_org(terrascript.Resource):
    pass


class hsdp_iam_password_policy(terrascript.Resource):
    pass


class hsdp_iam_proposition(terrascript.Resource):
    pass


class hsdp_iam_role(terrascript.Resource):
    pass


class hsdp_iam_service(terrascript.Resource):
    pass


class hsdp_iam_user(terrascript.Resource):
    pass


class hsdp_metrics_autoscaler(terrascript.Resource):
    pass


class hsdp_notification_producer(terrascript.Resource):
    pass


class hsdp_notification_subscriber(terrascript.Resource):
    pass


class hsdp_notification_subscription(terrascript.Resource):
    pass


class hsdp_notification_topic(terrascript.Resource):
    pass


class hsdp_pki_cert(terrascript.Resource):
    pass


class hsdp_pki_tenant(terrascript.Resource):
    pass


class hsdp_s3creds_policy(terrascript.Resource):
    pass


class hsdp_stl_app(terrascript.Resource):
    pass


class hsdp_stl_config(terrascript.Resource):
    pass


class hsdp_stl_custom_cert(terrascript.Resource):
    pass


class hsdp_stl_sync(terrascript.Resource):
    pass
