# terrascript/resource/PortOfPortland/activedirectory.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:38 UTC)
import terrascript


class activedirectory_groupMembership(terrascript.Resource):
    pass


class activedirectory_ouMapping(terrascript.Resource):
    pass

__all__ = [
    "activedirectory_groupMembership",
    "activedirectory_ouMapping",
]
