# terrascript/resource/PortOfPortland/windns.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:31:16 UTC)
import terrascript


class windns(terrascript.Resource):
    pass


__all__ = [
    "windns",
]
