# terrascript/provider/AdrienneCohea/nomadutility.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:25 UTC)

import terrascript

class nomadutility(terrascript.Provider):
    '''
    
    '''
    __description__ = ""
    __namespace__ = "AdrienneCohea"
    __name__ = "nomadutility"
    __source__ = "https://github.com/AdrienneCohea/terraform-provider-nomadutility"
    __version__ = "0.0.14"
    __published__ = "2020-12-17T06:10:54Z"
    __tier__ = "community"
    

__all__ = ["nomadutility"]
