# terrascript/resource/invidian/gpg.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:41 UTC)
import terrascript


class gpg_encrypted_message(terrascript.Resource):
    pass

__all__ = [
    "gpg_encrypted_message",
]
