# terrascript/resource/invidian/uptimerobot.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:29:51 UTC)
import terrascript


class uptimerobot_alert_contact(terrascript.Resource):
    pass


class uptimerobot_monitor(terrascript.Resource):
    pass


class uptimerobot_status_page(terrascript.Resource):
    pass


__all__ = [
    "uptimerobot_alert_contact",
    "uptimerobot_monitor",
    "uptimerobot_status_page",
]
