# terrascript/jsonnet/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class jsonnet_file(terrascript.Data):
    pass
