# terrascript/provider/cloudknox/cloudknox.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:11 UTC)

import terrascript

class cloudknox(terrascript.Provider):
    '''
    
    '''
    __description__ = ""
    __namespace__ = "cloudknox"
    __name__ = "cloudknox"
    __source__ = "https://github.com/cloudknox/terraform-provider-cloudknox"
    __version__ = "0.6.0"
    __published__ = "2020-11-09T21:15:43Z"
    __tier__ = "community"
    

__all__ = ["cloudknox"]
