# terrascript/resource/ucloud/ucloud.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:29:33 UTC)
import terrascript


class ucloud_cube_pod(terrascript.Resource):
    pass


class ucloud_db_instance(terrascript.Resource):
    pass


class ucloud_disk(terrascript.Resource):
    pass


class ucloud_disk_attachment(terrascript.Resource):
    pass


class ucloud_eip(terrascript.Resource):
    pass


class ucloud_eip_association(terrascript.Resource):
    pass


class ucloud_instance(terrascript.Resource):
    pass


class ucloud_isolation_group(terrascript.Resource):
    pass


class ucloud_lb(terrascript.Resource):
    pass


class ucloud_lb_attachment(terrascript.Resource):
    pass


class ucloud_lb_listener(terrascript.Resource):
    pass


class ucloud_lb_rule(terrascript.Resource):
    pass


class ucloud_lb_ssl(terrascript.Resource):
    pass


class ucloud_lb_ssl_attachment(terrascript.Resource):
    pass


class ucloud_memcache_instance(terrascript.Resource):
    pass


class ucloud_nat_gateway(terrascript.Resource):
    pass


class ucloud_nat_gateway_rule(terrascript.Resource):
    pass


class ucloud_redis_instance(terrascript.Resource):
    pass


class ucloud_security_group(terrascript.Resource):
    pass


class ucloud_subnet(terrascript.Resource):
    pass


class ucloud_udpn_connection(terrascript.Resource):
    pass


class ucloud_ufs_volume(terrascript.Resource):
    pass


class ucloud_uk8s_cluster(terrascript.Resource):
    pass


class ucloud_uk8s_node(terrascript.Resource):
    pass


class ucloud_us3_bucket(terrascript.Resource):
    pass


class ucloud_vip(terrascript.Resource):
    pass


class ucloud_vpc(terrascript.Resource):
    pass


class ucloud_vpc_peering_connection(terrascript.Resource):
    pass


class ucloud_vpn_connection(terrascript.Resource):
    pass


class ucloud_vpn_customer_gateway(terrascript.Resource):
    pass


class ucloud_vpn_gateway(terrascript.Resource):
    pass


__all__ = [
    "ucloud_cube_pod",
    "ucloud_db_instance",
    "ucloud_disk",
    "ucloud_disk_attachment",
    "ucloud_eip",
    "ucloud_eip_association",
    "ucloud_instance",
    "ucloud_isolation_group",
    "ucloud_lb",
    "ucloud_lb_attachment",
    "ucloud_lb_listener",
    "ucloud_lb_rule",
    "ucloud_lb_ssl",
    "ucloud_lb_ssl_attachment",
    "ucloud_memcache_instance",
    "ucloud_nat_gateway",
    "ucloud_nat_gateway_rule",
    "ucloud_redis_instance",
    "ucloud_security_group",
    "ucloud_subnet",
    "ucloud_udpn_connection",
    "ucloud_ufs_volume",
    "ucloud_uk8s_cluster",
    "ucloud_uk8s_node",
    "ucloud_us3_bucket",
    "ucloud_vip",
    "ucloud_vpc",
    "ucloud_vpc_peering_connection",
    "ucloud_vpn_connection",
    "ucloud_vpn_customer_gateway",
    "ucloud_vpn_gateway",
]
