# terrascript/resource/hashicorp/cloudinit.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:14:09 UTC)
import terrascript


class cloudinit_config(terrascript.Resource):
    pass


__all__ = [
    "cloudinit_config",
]
