# terrascript/resource/hashicorp/cloudinit.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:11 UTC)
import terrascript


class cloudinit_config(terrascript.Resource):
    pass

__all__ = [
    "cloudinit_config",
]
