# terrascript/resource/hashicorp/time.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:20 UTC)
import terrascript


class time_offset(terrascript.Resource):
    pass


class time_rotating(terrascript.Resource):
    pass


class time_sleep(terrascript.Resource):
    pass


class time_static(terrascript.Resource):
    pass

__all__ = [
    "time_offset",
    "time_rotating",
    "time_sleep",
    "time_static",
]
