# terrascript/data/ad.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:39 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.ad
#
# instead of
#
#   >>> import terrascript.data.hashicorp.ad
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.ad import *