# terrascript/data/avi.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:51 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.avi
#
# instead of
#
#   >>> import terrascript.data.vmware.avi
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.vmware.avi import *