# terrascript/data/aws.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:12:25 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.aws
#
# instead of
#
#   >>> import terrascript.data.hashicorp.aws
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.aws import *
