# terrascript/data/aws.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:55 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.aws
#
# instead of
#
#   >>> import terrascript.data.hashicorp.aws
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.aws import *