# terrascript/data/azurecaf.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:12:56 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.azurecaf
#
# instead of
#
#   >>> import terrascript.data.aztfmod.azurecaf
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.aztfmod.azurecaf import *
