# terrascript/data/azurestack.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:15 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.azurestack
#
# instead of
#
#   >>> import terrascript.data.hashicorp.azurestack
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.azurestack import *
