# terrascript/data/azurerm.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:11 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.azurerm
#
# instead of
#
#   >>> import terrascript.data.hashicorp.azurerm
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.azurerm import *
