# terrascript/data/brightbox.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:43 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.brightbox
#
# instead of
#
#   >>> import terrascript.data.brightbox.brightbox
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.brightbox.brightbox import *
