# terrascript/data/cloudflare.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:14:07 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.cloudflare
#
# instead of
#
#   >>> import terrascript.data.cloudflare.cloudflare
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.cloudflare.cloudflare import *
