# terrascript/data/cloudflare.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:10 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.cloudflare
#
# instead of
#
#   >>> import terrascript.data.cloudflare.cloudflare
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.cloudflare.cloudflare import *