# terrascript/data/googleworkspace.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:41 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.googleworkspace
#
# instead of
#
#   >>> import terrascript.data.hashicorp.googleworkspace
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.googleworkspace import *