# terrascript/data/hcloud.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:06 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.hcloud
#
# instead of
#
#   >>> import terrascript.data.hetznercloud.hcloud
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hetznercloud.hcloud import *
