# terrascript/data/hcp.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:10 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.hcp
#
# instead of
#
#   >>> import terrascript.data.hashicorp.hcp
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.hcp import *
