# terrascript/data/helm.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:50 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.helm
#
# instead of
#
#   >>> import terrascript.data.hashicorp.helm
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.helm import *