# terrascript/data/linode.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:21:10 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.linode
#
# instead of
#
#   >>> import terrascript.data.linode.linode
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.linode.linode import *
