# terrascript/data/local.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:21:17 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.local
#
# instead of
#
#   >>> import terrascript.data.hashicorp.local
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.hashicorp.local import *
