# terrascript/data/mongodbatlas.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:19 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.mongodbatlas
#
# instead of
#
#   >>> import terrascript.data.mongodb.mongodbatlas
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.mongodb.mongodbatlas import *