# terrascript/data/netapp_elementsw.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:21 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.netapp_elementsw
#
# instead of
#
#   >>> import terrascript.data.NetApp.netapp_elementsw
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.NetApp.netapp_elementsw import *