# terrascript/data/nsxt.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:22:57 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.nsxt
#
# instead of
#
#   >>> import terrascript.data.vmware.nsxt
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.vmware.nsxt import *
