# terrascript/data/scaleway.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:22 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.scaleway
#
# instead of
#
#   >>> import terrascript.data.scaleway.scaleway
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.scaleway.scaleway import *
