# terrascript/data/signalfx.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:07 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.signalfx
#
# instead of
#
#   >>> import terrascript.data.splunk-terraform.signalfx
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.splunk_terraform.signalfx import *