# terrascript/data/signalfx.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:27:12 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.signalfx
#
# instead of
#
#   >>> import terrascript.data.splunk-terraform.signalfx
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.splunk_terraform.signalfx import *
