# terrascript/data/sumologic.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:15 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.sumologic
#
# instead of
#
#   >>> import terrascript.data.SumoLogic.sumologic
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.SumoLogic.sumologic import *