# terrascript/data/tencentcloud.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:18 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.tencentcloud
#
# instead of
#
#   >>> import terrascript.data.tencentcloudstack.tencentcloud
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.data.tencentcloudstack.tencentcloud import *