# terrascript/data/terraform.py

# !!! This module is NOT generated by tools/makecode.py !!!

import terrascript


class terraform_remote_state(terrascript.Data):
    pass


__all__ = ["terraform_remote_state"]
