# terrascript/data/turbot.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:29:24 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.turbot
#
# instead of
#
#   >>> import terrascript.data.turbot.turbot
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.turbot.turbot import *
