# terrascript/data/vra.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:30:45 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.vra
#
# instead of
#
#   >>> import terrascript.data.vmware.vra
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.vmware.vra import *
