# terrascript/data/vultr.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:31:06 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.data.vultr
#
# instead of
#
#   >>> import terrascript.data.vultr.vultr
#
# This is only available for 'official' and 'partner' providers.

from terrascript.data.vultr.vultr import *
