# terrascript/unifi/d.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class unifi_ap_group(terrascript.Data):
    pass


class unifi_network(terrascript.Data):
    pass


class unifi_port_profile(terrascript.Data):
    pass


class unifi_radius_profile(terrascript.Data):
    pass


class unifi_user(terrascript.Data):
    pass


class unifi_user_group(terrascript.Data):
    pass
