# terrascript/unifi/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class unifi_device(terrascript.Resource):
    pass


class unifi_dynamic_dns(terrascript.Resource):
    pass


class unifi_firewall_group(terrascript.Resource):
    pass


class unifi_firewall_rule(terrascript.Resource):
    pass


class unifi_network(terrascript.Resource):
    pass


class unifi_port_forward(terrascript.Resource):
    pass


class unifi_port_profile(terrascript.Resource):
    pass


class unifi_setting_mgmt(terrascript.Resource):
    pass


class unifi_setting_usg(terrascript.Resource):
    pass


class unifi_site(terrascript.Resource):
    pass


class unifi_static_route(terrascript.Resource):
    pass


class unifi_user(terrascript.Resource):
    pass


class unifi_user_group(terrascript.Resource):
    pass


class unifi_wlan(terrascript.Resource):
    pass
