# terrascript/zerotier/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class zerotier_member(terrascript.Resource):
    pass


class zerotier_network(terrascript.Resource):
    pass
