# terrascript/data/MissionCriticalCloud/cosmic.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:14:40 UTC)
import terrascript


class cosmic_network_acl(terrascript.Data):
    pass


__all__ = [
    "cosmic_network_acl",
]
