# terrascript/fortios/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class fortios_alertemail_setting(terrascript.Resource):
    pass


class fortios_antivirus_heuristic(terrascript.Resource):
    pass


class fortios_antivirus_profile(terrascript.Resource):
    pass


class fortios_antivirus_quarantine(terrascript.Resource):
    pass


class fortios_antivirus_settings(terrascript.Resource):
    pass


class fortios_application_custom(terrascript.Resource):
    pass


class fortios_application_group(terrascript.Resource):
    pass


class fortios_application_list(terrascript.Resource):
    pass


class fortios_application_name(terrascript.Resource):
    pass


class fortios_application_rulesettings(terrascript.Resource):
    pass


class fortios_authentication_rule(terrascript.Resource):
    pass


class fortios_authentication_scheme(terrascript.Resource):
    pass


class fortios_authentication_setting(terrascript.Resource):
    pass


class fortios_certificate_ca(terrascript.Resource):
    pass


class fortios_certificate_crl(terrascript.Resource):
    pass


class fortios_certificate_local(terrascript.Resource):
    pass


class fortios_certificate_remote(terrascript.Resource):
    pass


class fortios_cifs_domaincontroller(terrascript.Resource):
    pass


class fortios_cifs_profile(terrascript.Resource):
    pass


class fortios_credentialstore_domaincontroller(terrascript.Resource):
    pass


class fortios_dlp_filepattern(terrascript.Resource):
    pass


class fortios_dlp_fpdocsource(terrascript.Resource):
    pass


class fortios_dlp_fpsensitivity(terrascript.Resource):
    pass


class fortios_dlp_sensitivity(terrascript.Resource):
    pass


class fortios_dlp_sensor(terrascript.Resource):
    pass


class fortios_dlp_settings(terrascript.Resource):
    pass


class fortios_dnsfilter_domainfilter(terrascript.Resource):
    pass


class fortios_dnsfilter_profile(terrascript.Resource):
    pass


class fortios_dpdk_cpus(terrascript.Resource):
    pass


class fortios_dpdk_global(terrascript.Resource):
    pass


class fortios_emailfilter_blockallowlist(terrascript.Resource):
    pass


class fortios_emailfilter_bwl(terrascript.Resource):
    pass


class fortios_emailfilter_bword(terrascript.Resource):
    pass


class fortios_emailfilter_dnsbl(terrascript.Resource):
    pass


class fortios_emailfilter_fortishield(terrascript.Resource):
    pass


class fortios_emailfilter_iptrust(terrascript.Resource):
    pass


class fortios_emailfilter_mheader(terrascript.Resource):
    pass


class fortios_emailfilter_options(terrascript.Resource):
    pass


class fortios_emailfilter_profile(terrascript.Resource):
    pass


class fortios_endpointcontrol_client(terrascript.Resource):
    pass


class fortios_endpointcontrol_fctems(terrascript.Resource):
    pass


class fortios_endpointcontrol_forticlientems(terrascript.Resource):
    pass


class fortios_endpointcontrol_forticlientregistrationsync(terrascript.Resource):
    pass


class fortios_endpointcontrol_profile(terrascript.Resource):
    pass


class fortios_endpointcontrol_registeredforticlient(terrascript.Resource):
    pass


class fortios_endpointcontrol_settings(terrascript.Resource):
    pass


class fortios_extendercontroller_dataplan(terrascript.Resource):
    pass


class fortios_extendercontroller_extender(terrascript.Resource):
    pass


class fortios_extendercontroller_extender1(terrascript.Resource):
    pass


class fortios_filefilter_profile(terrascript.Resource):
    pass


class fortios_firewall_DoSpolicy(terrascript.Resource):
    pass


class fortios_firewall_DoSpolicy6(terrascript.Resource):
    pass


class fortios_firewall_address(terrascript.Resource):
    pass


class fortios_firewall_address6(terrascript.Resource):
    pass


class fortios_firewall_address6template(terrascript.Resource):
    pass


class fortios_firewall_addrgrp(terrascript.Resource):
    pass


class fortios_firewall_addrgrp6(terrascript.Resource):
    pass


class fortios_firewall_authportal(terrascript.Resource):
    pass


class fortios_firewall_centralsnatmap(terrascript.Resource):
    pass


class fortios_firewall_centralsnatmap_move(terrascript.Resource):
    pass


class fortios_firewall_centralsnatmap_sort(terrascript.Resource):
    pass


class fortios_firewall_city(terrascript.Resource):
    pass


class fortios_firewall_country(terrascript.Resource):
    pass


class fortios_firewall_decryptedtrafficmirror(terrascript.Resource):
    pass


class fortios_firewall_dnstranslation(terrascript.Resource):
    pass


class fortios_firewall_identitybasedroute(terrascript.Resource):
    pass


class fortios_firewall_interfacepolicy(terrascript.Resource):
    pass


class fortios_firewall_interfacepolicy6(terrascript.Resource):
    pass


class fortios_firewall_internetservice(terrascript.Resource):
    pass


class fortios_firewall_internetserviceaddition(terrascript.Resource):
    pass


class fortios_firewall_internetserviceappend(terrascript.Resource):
    pass


class fortios_firewall_internetservicebotnet(terrascript.Resource):
    pass


class fortios_firewall_internetservicecustom(terrascript.Resource):
    pass


class fortios_firewall_internetservicecustomgroup(terrascript.Resource):
    pass


class fortios_firewall_internetservicedefinition(terrascript.Resource):
    pass


class fortios_firewall_internetserviceextension(terrascript.Resource):
    pass


class fortios_firewall_internetservicegroup(terrascript.Resource):
    pass


class fortios_firewall_internetserviceipblreason(terrascript.Resource):
    pass


class fortios_firewall_internetserviceipblvendor(terrascript.Resource):
    pass


class fortios_firewall_internetservicelist(terrascript.Resource):
    pass


class fortios_firewall_internetservicename(terrascript.Resource):
    pass


class fortios_firewall_internetserviceowner(terrascript.Resource):
    pass


class fortios_firewall_internetservicereputation(terrascript.Resource):
    pass


class fortios_firewall_ippool(terrascript.Resource):
    pass


class fortios_firewall_ippool6(terrascript.Resource):
    pass


class fortios_firewall_iptranslation(terrascript.Resource):
    pass


class fortios_firewall_ipv6ehfilter(terrascript.Resource):
    pass


class fortios_firewall_ldbmonitor(terrascript.Resource):
    pass


class fortios_firewall_localinpolicy(terrascript.Resource):
    pass


class fortios_firewall_localinpolicy6(terrascript.Resource):
    pass


class fortios_firewall_multicastaddress(terrascript.Resource):
    pass


class fortios_firewall_multicastaddress6(terrascript.Resource):
    pass


class fortios_firewall_multicastpolicy(terrascript.Resource):
    pass


class fortios_firewall_multicastpolicy6(terrascript.Resource):
    pass


class fortios_firewall_object_address(terrascript.Resource):
    pass


class fortios_firewall_object_addressgroup(terrascript.Resource):
    pass


class fortios_firewall_object_ippool(terrascript.Resource):
    pass


class fortios_firewall_object_service(terrascript.Resource):
    pass


class fortios_firewall_object_servicecategory(terrascript.Resource):
    pass


class fortios_firewall_object_servicegroup(terrascript.Resource):
    pass


class fortios_firewall_object_vip(terrascript.Resource):
    pass


class fortios_firewall_object_vipgroup(terrascript.Resource):
    pass


class fortios_firewall_policy(terrascript.Resource):
    pass


class fortios_firewall_policy46(terrascript.Resource):
    pass


class fortios_firewall_policy6(terrascript.Resource):
    pass


class fortios_firewall_policy64(terrascript.Resource):
    pass


class fortios_firewall_profilegroup(terrascript.Resource):
    pass


class fortios_firewall_profileprotocoloptions(terrascript.Resource):
    pass


class fortios_firewall_proxyaddress(terrascript.Resource):
    pass


class fortios_firewall_proxyaddrgrp(terrascript.Resource):
    pass


class fortios_firewall_proxypolicy(terrascript.Resource):
    pass


class fortios_firewall_proxypolicy_move(terrascript.Resource):
    pass


class fortios_firewall_proxypolicy_sort(terrascript.Resource):
    pass


class fortios_firewall_region(terrascript.Resource):
    pass


class fortios_firewall_security_policy(terrascript.Resource):
    pass


class fortios_firewall_security_policyseq(terrascript.Resource):
    pass


class fortios_firewall_security_policysort(terrascript.Resource):
    pass


class fortios_firewall_securitypolicy(terrascript.Resource):
    pass


class fortios_firewall_shapingpolicy(terrascript.Resource):
    pass


class fortios_firewall_shapingprofile(terrascript.Resource):
    pass


class fortios_firewall_sniffer(terrascript.Resource):
    pass


class fortios_firewall_sslserver(terrascript.Resource):
    pass


class fortios_firewall_sslsshprofile(terrascript.Resource):
    pass


class fortios_firewall_trafficclass(terrascript.Resource):
    pass


class fortios_firewall_ttlpolicy(terrascript.Resource):
    pass


class fortios_firewall_vendormac(terrascript.Resource):
    pass


class fortios_firewall_vip(terrascript.Resource):
    pass


class fortios_firewall_vip46(terrascript.Resource):
    pass


class fortios_firewall_vip6(terrascript.Resource):
    pass


class fortios_firewall_vip64(terrascript.Resource):
    pass


class fortios_firewall_vipgrp(terrascript.Resource):
    pass


class fortios_firewall_vipgrp46(terrascript.Resource):
    pass


class fortios_firewall_vipgrp6(terrascript.Resource):
    pass


class fortios_firewall_vipgrp64(terrascript.Resource):
    pass


class fortios_firewallconsolidated_policy(terrascript.Resource):
    pass


class fortios_firewallipmacbinding_setting(terrascript.Resource):
    pass


class fortios_firewallipmacbinding_table(terrascript.Resource):
    pass


class fortios_firewallschedule_group(terrascript.Resource):
    pass


class fortios_firewallschedule_onetime(terrascript.Resource):
    pass


class fortios_firewallschedule_recurring(terrascript.Resource):
    pass


class fortios_firewallservice_category(terrascript.Resource):
    pass


class fortios_firewallservice_custom(terrascript.Resource):
    pass


class fortios_firewallservice_group(terrascript.Resource):
    pass


class fortios_firewallshaper_peripshaper(terrascript.Resource):
    pass


class fortios_firewallshaper_trafficshaper(terrascript.Resource):
    pass


class fortios_firewallssh_hostkey(terrascript.Resource):
    pass


class fortios_firewallssh_localca(terrascript.Resource):
    pass


class fortios_firewallssh_localkey(terrascript.Resource):
    pass


class fortios_firewallssh_setting(terrascript.Resource):
    pass


class fortios_firewallssl_setting(terrascript.Resource):
    pass


class fortios_firewallwildcardfqdn_custom(terrascript.Resource):
    pass


class fortios_firewallwildcardfqdn_group(terrascript.Resource):
    pass


class fortios_fmg_devicemanager_device(terrascript.Resource):
    pass


class fortios_fmg_devicemanager_install_device(terrascript.Resource):
    pass


class fortios_fmg_devicemanager_install_policypackage(terrascript.Resource):
    pass


class fortios_fmg_devicemanager_script(terrascript.Resource):
    pass


class fortios_fmg_devicemanager_script_execute(terrascript.Resource):
    pass


class fortios_fmg_firewall_object_address(terrascript.Resource):
    pass


class fortios_fmg_firewall_object_ippool(terrascript.Resource):
    pass


class fortios_fmg_firewall_object_service(terrascript.Resource):
    pass


class fortios_fmg_firewall_object_vip(terrascript.Resource):
    pass


class fortios_fmg_firewall_security_policy(terrascript.Resource):
    pass


class fortios_fmg_firewall_security_policypackage(terrascript.Resource):
    pass


class fortios_fmg_jsonrpc_request(terrascript.Resource):
    pass


class fortios_fmg_object_adom_revision(terrascript.Resource):
    pass


class fortios_fmg_system_admin(terrascript.Resource):
    pass


class fortios_fmg_system_admin_profiles(terrascript.Resource):
    pass


class fortios_fmg_system_admin_user(terrascript.Resource):
    pass


class fortios_fmg_system_adom(terrascript.Resource):
    pass


class fortios_fmg_system_dns(terrascript.Resource):
    pass


class fortios_fmg_system_global(terrascript.Resource):
    pass


class fortios_fmg_system_license_forticare(terrascript.Resource):
    pass


class fortios_fmg_system_license_vm(terrascript.Resource):
    pass


class fortios_fmg_system_network_interface(terrascript.Resource):
    pass


class fortios_fmg_system_network_route(terrascript.Resource):
    pass


class fortios_fmg_system_ntp(terrascript.Resource):
    pass


class fortios_fmg_system_syslogserver(terrascript.Resource):
    pass


class fortios_ftpproxy_explicit(terrascript.Resource):
    pass


class fortios_icap_profile(terrascript.Resource):
    pass


class fortios_icap_server(terrascript.Resource):
    pass


class fortios_ips_custom(terrascript.Resource):
    pass


class fortios_ips_decoder(terrascript.Resource):
    pass


class fortios_ips_global(terrascript.Resource):
    pass


class fortios_ips_rule(terrascript.Resource):
    pass


class fortios_ips_rulesettings(terrascript.Resource):
    pass


class fortios_ips_sensor(terrascript.Resource):
    pass


class fortios_ips_settings(terrascript.Resource):
    pass


class fortios_ips_viewmap(terrascript.Resource):
    pass


class fortios_json_generic_api(terrascript.Resource):
    pass


class fortios_log_customfield(terrascript.Resource):
    pass


class fortios_log_eventfilter(terrascript.Resource):
    pass


class fortios_log_fortianalyzer_setting(terrascript.Resource):
    pass


class fortios_log_guidisplay(terrascript.Resource):
    pass


class fortios_log_setting(terrascript.Resource):
    pass


class fortios_log_syslog_setting(terrascript.Resource):
    pass


class fortios_log_threatweight(terrascript.Resource):
    pass


class fortios_logdisk_filter(terrascript.Resource):
    pass


class fortios_logdisk_setting(terrascript.Resource):
    pass


class fortios_logfortianalyzer2_filter(terrascript.Resource):
    pass


class fortios_logfortianalyzer2_overridefilter(terrascript.Resource):
    pass


class fortios_logfortianalyzer2_overridesetting(terrascript.Resource):
    pass


class fortios_logfortianalyzer2_setting(terrascript.Resource):
    pass


class fortios_logfortianalyzer3_filter(terrascript.Resource):
    pass


class fortios_logfortianalyzer3_overridefilter(terrascript.Resource):
    pass


class fortios_logfortianalyzer3_overridesetting(terrascript.Resource):
    pass


class fortios_logfortianalyzer3_setting(terrascript.Resource):
    pass


class fortios_logfortianalyzer_filter(terrascript.Resource):
    pass


class fortios_logfortianalyzer_overridefilter(terrascript.Resource):
    pass


class fortios_logfortianalyzer_overridesetting(terrascript.Resource):
    pass


class fortios_logfortianalyzer_setting(terrascript.Resource):
    pass


class fortios_logfortianalyzercloud_filter(terrascript.Resource):
    pass


class fortios_logfortianalyzercloud_overridefilter(terrascript.Resource):
    pass


class fortios_logfortianalyzercloud_overridesetting(terrascript.Resource):
    pass


class fortios_logfortianalyzercloud_setting(terrascript.Resource):
    pass


class fortios_logfortiguard_filter(terrascript.Resource):
    pass


class fortios_logfortiguard_overridefilter(terrascript.Resource):
    pass


class fortios_logfortiguard_overridesetting(terrascript.Resource):
    pass


class fortios_logfortiguard_setting(terrascript.Resource):
    pass


class fortios_logmemory_filter(terrascript.Resource):
    pass


class fortios_logmemory_globalsetting(terrascript.Resource):
    pass


class fortios_logmemory_setting(terrascript.Resource):
    pass


class fortios_lognulldevice_filter(terrascript.Resource):
    pass


class fortios_lognulldevice_setting(terrascript.Resource):
    pass


class fortios_logsyslogd2_filter(terrascript.Resource):
    pass


class fortios_logsyslogd2_overridefilter(terrascript.Resource):
    pass


class fortios_logsyslogd2_overridesetting(terrascript.Resource):
    pass


class fortios_logsyslogd2_setting(terrascript.Resource):
    pass


class fortios_logsyslogd3_filter(terrascript.Resource):
    pass


class fortios_logsyslogd3_overridefilter(terrascript.Resource):
    pass


class fortios_logsyslogd3_overridesetting(terrascript.Resource):
    pass


class fortios_logsyslogd3_setting(terrascript.Resource):
    pass


class fortios_logsyslogd4_filter(terrascript.Resource):
    pass


class fortios_logsyslogd4_overridefilter(terrascript.Resource):
    pass


class fortios_logsyslogd4_overridesetting(terrascript.Resource):
    pass


class fortios_logsyslogd4_setting(terrascript.Resource):
    pass


class fortios_logsyslogd_filter(terrascript.Resource):
    pass


class fortios_logsyslogd_overridefilter(terrascript.Resource):
    pass


class fortios_logsyslogd_overridesetting(terrascript.Resource):
    pass


class fortios_logsyslogd_setting(terrascript.Resource):
    pass


class fortios_logwebtrends_filter(terrascript.Resource):
    pass


class fortios_logwebtrends_setting(terrascript.Resource):
    pass


class fortios_networking_interface_port(terrascript.Resource):
    pass


class fortios_networking_route_static(terrascript.Resource):
    pass


class fortios_nsxt_servicechain(terrascript.Resource):
    pass


class fortios_nsxt_setting(terrascript.Resource):
    pass


class fortios_report_chart(terrascript.Resource):
    pass


class fortios_report_dataset(terrascript.Resource):
    pass


class fortios_report_layout(terrascript.Resource):
    pass


class fortios_report_setting(terrascript.Resource):
    pass


class fortios_report_style(terrascript.Resource):
    pass


class fortios_report_theme(terrascript.Resource):
    pass


class fortios_router_accesslist(terrascript.Resource):
    pass


class fortios_router_accesslist6(terrascript.Resource):
    pass


class fortios_router_aspathlist(terrascript.Resource):
    pass


class fortios_router_authpath(terrascript.Resource):
    pass


class fortios_router_bfd(terrascript.Resource):
    pass


class fortios_router_bfd6(terrascript.Resource):
    pass


class fortios_router_bgp(terrascript.Resource):
    pass


class fortios_router_communitylist(terrascript.Resource):
    pass


class fortios_router_isis(terrascript.Resource):
    pass


class fortios_router_keychain(terrascript.Resource):
    pass


class fortios_router_multicast(terrascript.Resource):
    pass


class fortios_router_multicast6(terrascript.Resource):
    pass


class fortios_router_multicastflow(terrascript.Resource):
    pass


class fortios_router_ospf(terrascript.Resource):
    pass


class fortios_router_ospf6(terrascript.Resource):
    pass


class fortios_router_policy(terrascript.Resource):
    pass


class fortios_router_policy6(terrascript.Resource):
    pass


class fortios_router_prefixlist(terrascript.Resource):
    pass


class fortios_router_prefixlist6(terrascript.Resource):
    pass


class fortios_router_rip(terrascript.Resource):
    pass


class fortios_router_ripng(terrascript.Resource):
    pass


class fortios_router_routemap(terrascript.Resource):
    pass


class fortios_router_setting(terrascript.Resource):
    pass


class fortios_router_static(terrascript.Resource):
    pass


class fortios_router_static6(terrascript.Resource):
    pass


class fortios_routerbgp_neighbor(terrascript.Resource):
    pass


class fortios_routerbgp_network(terrascript.Resource):
    pass


class fortios_routerbgp_network6(terrascript.Resource):
    pass


class fortios_routerospf6_ospf6interface(terrascript.Resource):
    pass


class fortios_routerospf_neighbor(terrascript.Resource):
    pass


class fortios_routerospf_network(terrascript.Resource):
    pass


class fortios_routerospf_ospfinterface(terrascript.Resource):
    pass


class fortios_spamfilter_bwl(terrascript.Resource):
    pass


class fortios_spamfilter_bword(terrascript.Resource):
    pass


class fortios_spamfilter_dnsbl(terrascript.Resource):
    pass


class fortios_spamfilter_fortishield(terrascript.Resource):
    pass


class fortios_spamfilter_iptrust(terrascript.Resource):
    pass


class fortios_spamfilter_mheader(terrascript.Resource):
    pass


class fortios_spamfilter_options(terrascript.Resource):
    pass


class fortios_spamfilter_profile(terrascript.Resource):
    pass


class fortios_sshfilter_profile(terrascript.Resource):
    pass


class fortios_switchcontroller_8021Xsettings(terrascript.Resource):
    pass


class fortios_switchcontroller_customcommand(terrascript.Resource):
    pass


class fortios_switchcontroller_flowtracking(terrascript.Resource):
    pass


class fortios_switchcontroller_global(terrascript.Resource):
    pass


class fortios_switchcontroller_igmpsnooping(terrascript.Resource):
    pass


class fortios_switchcontroller_lldpprofile(terrascript.Resource):
    pass


class fortios_switchcontroller_lldpsettings(terrascript.Resource):
    pass


class fortios_switchcontroller_location(terrascript.Resource):
    pass


class fortios_switchcontroller_macsyncsettings(terrascript.Resource):
    pass


class fortios_switchcontroller_managedswitch(terrascript.Resource):
    pass


class fortios_switchcontroller_nacdevice(terrascript.Resource):
    pass


class fortios_switchcontroller_nacsettings(terrascript.Resource):
    pass


class fortios_switchcontroller_networkmonitorsettings(terrascript.Resource):
    pass


class fortios_switchcontroller_portpolicy(terrascript.Resource):
    pass


class fortios_switchcontroller_quarantine(terrascript.Resource):
    pass


class fortios_switchcontroller_remotelog(terrascript.Resource):
    pass


class fortios_switchcontroller_sflow(terrascript.Resource):
    pass


class fortios_switchcontroller_snmpcommunity(terrascript.Resource):
    pass


class fortios_switchcontroller_snmpsysinfo(terrascript.Resource):
    pass


class fortios_switchcontroller_snmptrapthreshold(terrascript.Resource):
    pass


class fortios_switchcontroller_snmpuser(terrascript.Resource):
    pass


class fortios_switchcontroller_stormcontrol(terrascript.Resource):
    pass


class fortios_switchcontroller_stormcontrolpolicy(terrascript.Resource):
    pass


class fortios_switchcontroller_stpinstance(terrascript.Resource):
    pass


class fortios_switchcontroller_stpsettings(terrascript.Resource):
    pass


class fortios_switchcontroller_switchgroup(terrascript.Resource):
    pass


class fortios_switchcontroller_switchinterfacetag(terrascript.Resource):
    pass


class fortios_switchcontroller_switchlog(terrascript.Resource):
    pass


class fortios_switchcontroller_switchprofile(terrascript.Resource):
    pass


class fortios_switchcontroller_system(terrascript.Resource):
    pass


class fortios_switchcontroller_trafficpolicy(terrascript.Resource):
    pass


class fortios_switchcontroller_trafficsniffer(terrascript.Resource):
    pass


class fortios_switchcontroller_virtualportpool(terrascript.Resource):
    pass


class fortios_switchcontroller_vlan(terrascript.Resource):
    pass


class fortios_switchcontroller_vlanpolicy(terrascript.Resource):
    pass


class fortios_switchcontrollerautoconfig_custom(terrascript.Resource):
    pass


class fortios_switchcontrollerautoconfig_default(terrascript.Resource):
    pass


class fortios_switchcontrollerautoconfig_policy(terrascript.Resource):
    pass


class fortios_switchcontrollerinitialconfig_template(terrascript.Resource):
    pass


class fortios_switchcontrollerinitialconfig_vlans(terrascript.Resource):
    pass


class fortios_switchcontrollerptp_policy(terrascript.Resource):
    pass


class fortios_switchcontrollerptp_settings(terrascript.Resource):
    pass


class fortios_switchcontrollerqos_dot1pmap(terrascript.Resource):
    pass


class fortios_switchcontrollerqos_ipdscpmap(terrascript.Resource):
    pass


class fortios_switchcontrollerqos_qospolicy(terrascript.Resource):
    pass


class fortios_switchcontrollerqos_queuepolicy(terrascript.Resource):
    pass


class fortios_switchcontrollersecuritypolicy_8021X(terrascript.Resource):
    pass


class fortios_switchcontrollersecuritypolicy_captiveportal(terrascript.Resource):
    pass


class fortios_switchcontrollersecuritypolicy_localaccess(terrascript.Resource):
    pass


class fortios_system_accprofile(terrascript.Resource):
    pass


class fortios_system_admin(terrascript.Resource):
    pass


class fortios_system_admin_administrator(terrascript.Resource):
    pass


class fortios_system_admin_profiles(terrascript.Resource):
    pass


class fortios_system_affinityinterrupt(terrascript.Resource):
    pass


class fortios_system_affinitypacketredistribution(terrascript.Resource):
    pass


class fortios_system_alarm(terrascript.Resource):
    pass


class fortios_system_alias(terrascript.Resource):
    pass


class fortios_system_apiuser(terrascript.Resource):
    pass


class fortios_system_apiuser_setting(terrascript.Resource):
    pass


class fortios_system_arptable(terrascript.Resource):
    pass


class fortios_system_autoinstall(terrascript.Resource):
    pass


class fortios_system_automationaction(terrascript.Resource):
    pass


class fortios_system_automationdestination(terrascript.Resource):
    pass


class fortios_system_automationstitch(terrascript.Resource):
    pass


class fortios_system_automationtrigger(terrascript.Resource):
    pass


class fortios_system_autoscript(terrascript.Resource):
    pass


class fortios_system_centralmanagement(terrascript.Resource):
    pass


class fortios_system_clustersync(terrascript.Resource):
    pass


class fortios_system_console(terrascript.Resource):
    pass


class fortios_system_csf(terrascript.Resource):
    pass


class fortios_system_customlanguage(terrascript.Resource):
    pass


class fortios_system_ddns(terrascript.Resource):
    pass


class fortios_system_dedicatedmgmt(terrascript.Resource):
    pass


class fortios_system_dns(terrascript.Resource):
    pass


class fortios_system_dnsdatabase(terrascript.Resource):
    pass


class fortios_system_dnsserver(terrascript.Resource):
    pass


class fortios_system_dscpbasedpriority(terrascript.Resource):
    pass


class fortios_system_emailserver(terrascript.Resource):
    pass


class fortios_system_externalresource(terrascript.Resource):
    pass


class fortios_system_federatedupgrade(terrascript.Resource):
    pass


class fortios_system_fipscc(terrascript.Resource):
    pass


class fortios_system_fm(terrascript.Resource):
    pass


class fortios_system_fortiguard(terrascript.Resource):
    pass


class fortios_system_fortimanager(terrascript.Resource):
    pass


class fortios_system_fortisandbox(terrascript.Resource):
    pass


class fortios_system_fssopolling(terrascript.Resource):
    pass


class fortios_system_ftmpush(terrascript.Resource):
    pass


class fortios_system_geneve(terrascript.Resource):
    pass


class fortios_system_geoipcountry(terrascript.Resource):
    pass


class fortios_system_geoipoverride(terrascript.Resource):
    pass


class fortios_system_global(terrascript.Resource):
    pass


class fortios_system_gretunnel(terrascript.Resource):
    pass


class fortios_system_ha(terrascript.Resource):
    pass


class fortios_system_hamonitor(terrascript.Resource):
    pass


class fortios_system_interface(terrascript.Resource):
    pass


class fortios_system_ipiptunnel(terrascript.Resource):
    pass


class fortios_system_ips(terrascript.Resource):
    pass


class fortios_system_ipsecaggregate(terrascript.Resource):
    pass


class fortios_system_ipsurlfilterdns(terrascript.Resource):
    pass


class fortios_system_ipsurlfilterdns6(terrascript.Resource):
    pass


class fortios_system_ipv6neighborcache(terrascript.Resource):
    pass


class fortios_system_ipv6tunnel(terrascript.Resource):
    pass


class fortios_system_license_forticare(terrascript.Resource):
    pass


class fortios_system_license_vdom(terrascript.Resource):
    pass


class fortios_system_license_vm(terrascript.Resource):
    pass


class fortios_system_linkmonitor(terrascript.Resource):
    pass


class fortios_system_macaddresstable(terrascript.Resource):
    pass


class fortios_system_managementtunnel(terrascript.Resource):
    pass


class fortios_system_mobiletunnel(terrascript.Resource):
    pass


class fortios_system_nat64(terrascript.Resource):
    pass


class fortios_system_ndproxy(terrascript.Resource):
    pass


class fortios_system_netflow(terrascript.Resource):
    pass


class fortios_system_networkvisibility(terrascript.Resource):
    pass


class fortios_system_ntp(terrascript.Resource):
    pass


class fortios_system_objecttagging(terrascript.Resource):
    pass


class fortios_system_passwordpolicy(terrascript.Resource):
    pass


class fortios_system_passwordpolicyguestadmin(terrascript.Resource):
    pass


class fortios_system_pppoeinterface(terrascript.Resource):
    pass


class fortios_system_proberesponse(terrascript.Resource):
    pass


class fortios_system_proxyarp(terrascript.Resource):
    pass


class fortios_system_ptp(terrascript.Resource):
    pass


class fortios_system_replacemsggroup(terrascript.Resource):
    pass


class fortios_system_replacemsgimage(terrascript.Resource):
    pass


class fortios_system_resourcelimits(terrascript.Resource):
    pass


class fortios_system_saml(terrascript.Resource):
    pass


class fortios_system_sdnconnector(terrascript.Resource):
    pass


class fortios_system_sdwan(terrascript.Resource):
    pass


class fortios_system_sessionhelper(terrascript.Resource):
    pass


class fortios_system_sessionttl(terrascript.Resource):
    pass


class fortios_system_setting_dns(terrascript.Resource):
    pass


class fortios_system_setting_global(terrascript.Resource):
    pass


class fortios_system_setting_ntp(terrascript.Resource):
    pass


class fortios_system_settings(terrascript.Resource):
    pass


class fortios_system_sflow(terrascript.Resource):
    pass


class fortios_system_sittunnel(terrascript.Resource):
    pass


class fortios_system_smsserver(terrascript.Resource):
    pass


class fortios_system_speedtestschedule(terrascript.Resource):
    pass


class fortios_system_speedtestserver(terrascript.Resource):
    pass


class fortios_system_ssoadmin(terrascript.Resource):
    pass


class fortios_system_standalonecluster(terrascript.Resource):
    pass


class fortios_system_storage(terrascript.Resource):
    pass


class fortios_system_switchinterface(terrascript.Resource):
    pass


class fortios_system_tosbasedpriority(terrascript.Resource):
    pass


class fortios_system_vdom(terrascript.Resource):
    pass


class fortios_system_vdom_setting(terrascript.Resource):
    pass


class fortios_system_vdomdns(terrascript.Resource):
    pass


class fortios_system_vdomexception(terrascript.Resource):
    pass


class fortios_system_vdomlink(terrascript.Resource):
    pass


class fortios_system_vdomnetflow(terrascript.Resource):
    pass


class fortios_system_vdomproperty(terrascript.Resource):
    pass


class fortios_system_vdomradiusserver(terrascript.Resource):
    pass


class fortios_system_vdomsflow(terrascript.Resource):
    pass


class fortios_system_virtualswitch(terrascript.Resource):
    pass


class fortios_system_virtualwanlink(terrascript.Resource):
    pass


class fortios_system_virtualwirepair(terrascript.Resource):
    pass


class fortios_system_vnetunnel(terrascript.Resource):
    pass


class fortios_system_vxlan(terrascript.Resource):
    pass


class fortios_system_wccp(terrascript.Resource):
    pass


class fortios_system_zone(terrascript.Resource):
    pass


class fortios_systemautoupdate_pushupdate(terrascript.Resource):
    pass


class fortios_systemautoupdate_schedule(terrascript.Resource):
    pass


class fortios_systemautoupdate_tunneling(terrascript.Resource):
    pass


class fortios_systemdhcp6_server(terrascript.Resource):
    pass


class fortios_systemdhcp_server(terrascript.Resource):
    pass


class fortios_systemlldp_networkpolicy(terrascript.Resource):
    pass


class fortios_systemreplacemsg_admin(terrascript.Resource):
    pass


class fortios_systemreplacemsg_alertmail(terrascript.Resource):
    pass


class fortios_systemreplacemsg_auth(terrascript.Resource):
    pass


class fortios_systemreplacemsg_automation(terrascript.Resource):
    pass


class fortios_systemreplacemsg_devicedetectionportal(terrascript.Resource):
    pass


class fortios_systemreplacemsg_ec(terrascript.Resource):
    pass


class fortios_systemreplacemsg_fortiguardwf(terrascript.Resource):
    pass


class fortios_systemreplacemsg_ftp(terrascript.Resource):
    pass


class fortios_systemreplacemsg_http(terrascript.Resource):
    pass


class fortios_systemreplacemsg_icap(terrascript.Resource):
    pass


class fortios_systemreplacemsg_mail(terrascript.Resource):
    pass


class fortios_systemreplacemsg_nacquar(terrascript.Resource):
    pass


class fortios_systemreplacemsg_nntp(terrascript.Resource):
    pass


class fortios_systemreplacemsg_spam(terrascript.Resource):
    pass


class fortios_systemreplacemsg_sslvpn(terrascript.Resource):
    pass


class fortios_systemreplacemsg_trafficquota(terrascript.Resource):
    pass


class fortios_systemreplacemsg_utm(terrascript.Resource):
    pass


class fortios_systemreplacemsg_webproxy(terrascript.Resource):
    pass


class fortios_systemsnmp_community(terrascript.Resource):
    pass


class fortios_systemsnmp_sysinfo(terrascript.Resource):
    pass


class fortios_systemsnmp_user(terrascript.Resource):
    pass


class fortios_user_adgrp(terrascript.Resource):
    pass


class fortios_user_device(terrascript.Resource):
    pass


class fortios_user_deviceaccesslist(terrascript.Resource):
    pass


class fortios_user_devicecategory(terrascript.Resource):
    pass


class fortios_user_devicegroup(terrascript.Resource):
    pass


class fortios_user_domaincontroller(terrascript.Resource):
    pass


class fortios_user_exchange(terrascript.Resource):
    pass


class fortios_user_fortitoken(terrascript.Resource):
    pass


class fortios_user_fsso(terrascript.Resource):
    pass


class fortios_user_fssopolling(terrascript.Resource):
    pass


class fortios_user_group(terrascript.Resource):
    pass


class fortios_user_krbkeytab(terrascript.Resource):
    pass


class fortios_user_ldap(terrascript.Resource):
    pass


class fortios_user_local(terrascript.Resource):
    pass


class fortios_user_nacpolicy(terrascript.Resource):
    pass


class fortios_user_passwordpolicy(terrascript.Resource):
    pass


class fortios_user_peer(terrascript.Resource):
    pass


class fortios_user_peergrp(terrascript.Resource):
    pass


class fortios_user_pop3(terrascript.Resource):
    pass


class fortios_user_quarantine(terrascript.Resource):
    pass


class fortios_user_radius(terrascript.Resource):
    pass


class fortios_user_saml(terrascript.Resource):
    pass


class fortios_user_securityexemptlist(terrascript.Resource):
    pass


class fortios_user_setting(terrascript.Resource):
    pass


class fortios_user_tacacs(terrascript.Resource):
    pass


class fortios_voip_profile(terrascript.Resource):
    pass


class fortios_vpn_ipsec_phase1interface(terrascript.Resource):
    pass


class fortios_vpn_ipsec_phase2interface(terrascript.Resource):
    pass


class fortios_vpn_l2tp(terrascript.Resource):
    pass


class fortios_vpn_ocvpn(terrascript.Resource):
    pass


class fortios_vpn_pptp(terrascript.Resource):
    pass


class fortios_vpncertificate_ca(terrascript.Resource):
    pass


class fortios_vpncertificate_crl(terrascript.Resource):
    pass


class fortios_vpncertificate_local(terrascript.Resource):
    pass


class fortios_vpncertificate_ocspserver(terrascript.Resource):
    pass


class fortios_vpncertificate_remote(terrascript.Resource):
    pass


class fortios_vpncertificate_setting(terrascript.Resource):
    pass


class fortios_vpnipsec_concentrator(terrascript.Resource):
    pass


class fortios_vpnipsec_forticlient(terrascript.Resource):
    pass


class fortios_vpnipsec_manualkey(terrascript.Resource):
    pass


class fortios_vpnipsec_manualkeyinterface(terrascript.Resource):
    pass


class fortios_vpnipsec_phase1(terrascript.Resource):
    pass


class fortios_vpnipsec_phase1interface(terrascript.Resource):
    pass


class fortios_vpnipsec_phase2(terrascript.Resource):
    pass


class fortios_vpnipsec_phase2interface(terrascript.Resource):
    pass


class fortios_vpnssl_settings(terrascript.Resource):
    pass


class fortios_vpnsslweb_hostchecksoftware(terrascript.Resource):
    pass


class fortios_vpnsslweb_portal(terrascript.Resource):
    pass


class fortios_vpnsslweb_realm(terrascript.Resource):
    pass


class fortios_vpnsslweb_userbookmark(terrascript.Resource):
    pass


class fortios_vpnsslweb_usergroupbookmark(terrascript.Resource):
    pass


class fortios_waf_mainclass(terrascript.Resource):
    pass


class fortios_waf_profile(terrascript.Resource):
    pass


class fortios_waf_signature(terrascript.Resource):
    pass


class fortios_waf_subclass(terrascript.Resource):
    pass


class fortios_wanopt_authgroup(terrascript.Resource):
    pass


class fortios_wanopt_cacheservice(terrascript.Resource):
    pass


class fortios_wanopt_contentdeliverynetworkrule(terrascript.Resource):
    pass


class fortios_wanopt_peer(terrascript.Resource):
    pass


class fortios_wanopt_profile(terrascript.Resource):
    pass


class fortios_wanopt_remotestorage(terrascript.Resource):
    pass


class fortios_wanopt_settings(terrascript.Resource):
    pass


class fortios_wanopt_webcache(terrascript.Resource):
    pass


class fortios_webfilter_content(terrascript.Resource):
    pass


class fortios_webfilter_contentheader(terrascript.Resource):
    pass


class fortios_webfilter_fortiguard(terrascript.Resource):
    pass


class fortios_webfilter_ftgdlocalcat(terrascript.Resource):
    pass


class fortios_webfilter_ftgdlocalrating(terrascript.Resource):
    pass


class fortios_webfilter_ipsurlfiltercachesetting(terrascript.Resource):
    pass


class fortios_webfilter_ipsurlfiltersetting(terrascript.Resource):
    pass


class fortios_webfilter_ipsurlfiltersetting6(terrascript.Resource):
    pass


class fortios_webfilter_override(terrascript.Resource):
    pass


class fortios_webfilter_profile(terrascript.Resource):
    pass


class fortios_webfilter_searchengine(terrascript.Resource):
    pass


class fortios_webfilter_urlfilter(terrascript.Resource):
    pass


class fortios_webproxy_debugurl(terrascript.Resource):
    pass


class fortios_webproxy_explicit(terrascript.Resource):
    pass


class fortios_webproxy_forwardserver(terrascript.Resource):
    pass


class fortios_webproxy_forwardservergroup(terrascript.Resource):
    pass


class fortios_webproxy_global(terrascript.Resource):
    pass


class fortios_webproxy_profile(terrascript.Resource):
    pass


class fortios_webproxy_urlmatch(terrascript.Resource):
    pass


class fortios_webproxy_wisp(terrascript.Resource):
    pass


class fortios_wirelesscontroller_accesscontrollist(terrascript.Resource):
    pass


class fortios_wirelesscontroller_address(terrascript.Resource):
    pass


class fortios_wirelesscontroller_addrgrp(terrascript.Resource):
    pass


class fortios_wirelesscontroller_apcfgprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_apstatus(terrascript.Resource):
    pass


class fortios_wirelesscontroller_arrpprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_bleprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_bonjourprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_global(terrascript.Resource):
    pass


class fortios_wirelesscontroller_intercontroller(terrascript.Resource):
    pass


class fortios_wirelesscontroller_log(terrascript.Resource):
    pass


class fortios_wirelesscontroller_mpskprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_qosprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_region(terrascript.Resource):
    pass


class fortios_wirelesscontroller_setting(terrascript.Resource):
    pass


class fortios_wirelesscontroller_snmp(terrascript.Resource):
    pass


class fortios_wirelesscontroller_timers(terrascript.Resource):
    pass


class fortios_wirelesscontroller_utmprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_vap(terrascript.Resource):
    pass


class fortios_wirelesscontroller_vapgroup(terrascript.Resource):
    pass


class fortios_wirelesscontroller_wagprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_widsprofile(terrascript.Resource):
    pass


class fortios_wirelesscontroller_wtp(terrascript.Resource):
    pass


class fortios_wirelesscontroller_wtpgroup(terrascript.Resource):
    pass


class fortios_wirelesscontroller_wtpprofile(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_anqp3gppcellular(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_anqpipaddresstype(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_anqpnairealm(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_anqpnetworkauthtype(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_anqproamingconsortium(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_anqpvenuename(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_h2qpconncapability(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_h2qpoperatorname(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_h2qposuprovider(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_h2qpwanmetric(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_hsprofile(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_icon(terrascript.Resource):
    pass


class fortios_wirelesscontrollerhotspot20_qosmap(terrascript.Resource):
    pass
