# terrascript/data/ns1-terraform/ns1.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:26 UTC)
import terrascript


class ns1_dnssec(terrascript.Data):
    pass


class ns1_record(terrascript.Data):
    pass


class ns1_zone(terrascript.Data):
    pass


__all__ = [
    "ns1_dnssec",
    "ns1_record",
    "ns1_zone",
]
