# terrascript/data/fastly/fastly.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:26 UTC)
import terrascript


class fastly_ip_ranges(terrascript.Data):
    pass


class fastly_tls_activation(terrascript.Data):
    pass


class fastly_tls_activation_ids(terrascript.Data):
    pass


class fastly_tls_certificate(terrascript.Data):
    pass


class fastly_tls_certificate_ids(terrascript.Data):
    pass


class fastly_tls_configuration(terrascript.Data):
    pass


class fastly_tls_configuration_ids(terrascript.Data):
    pass


class fastly_tls_domain(terrascript.Data):
    pass


class fastly_tls_platform_certificate(terrascript.Data):
    pass


class fastly_tls_platform_certificate_ids(terrascript.Data):
    pass


class fastly_tls_private_key(terrascript.Data):
    pass


class fastly_tls_private_key_ids(terrascript.Data):
    pass


class fastly_tls_subscription(terrascript.Data):
    pass


class fastly_tls_subscription_ids(terrascript.Data):
    pass


class fastly_waf_rules(terrascript.Data):
    pass


__all__ = [
    "fastly_ip_ranges",
    "fastly_tls_activation",
    "fastly_tls_activation_ids",
    "fastly_tls_certificate",
    "fastly_tls_certificate_ids",
    "fastly_tls_configuration",
    "fastly_tls_configuration_ids",
    "fastly_tls_domain",
    "fastly_tls_platform_certificate",
    "fastly_tls_platform_certificate_ids",
    "fastly_tls_private_key",
    "fastly_tls_private_key_ids",
    "fastly_tls_subscription",
    "fastly_tls_subscription_ids",
    "fastly_waf_rules",
]
