# terrascript/provider/gridscale/gridscale.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:17:40 UTC)

import terrascript


class gridscale(terrascript.Provider):
    """Terraform gridscale provider"""

    __description__ = "Terraform gridscale provider"
    __namespace__ = "gridscale"
    __name__ = "gridscale"
    __source__ = "https://github.com/gridscale/terraform-provider-gridscale"
    __version__ = "1.13.0"
    __published__ = "2021-09-09T15:12:28Z"
    __tier__ = "partner"


__all__ = ["gridscale"]
