# terrascript/data/vmware/vmc.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:30:35 UTC)
import terrascript


class vmc_connected_accounts(terrascript.Data):
    pass


class vmc_customer_subnets(terrascript.Data):
    pass


class vmc_org(terrascript.Data):
    pass


class vmc_sddc(terrascript.Data):
    pass


__all__ = [
    "vmc_connected_accounts",
    "vmc_customer_subnets",
    "vmc_org",
    "vmc_sddc",
]
