# terrascript/provider/alicloud.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:11:35 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.alicloud
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.alicloud
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.alicloud import *
