# terrascript/provider/amixr.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:11:40 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.amixr
#
# instead of
#
#   >>> import terrascript.provider.alertmixer.amixr
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.alertmixer.amixr import *
