# terrascript/provider/aviatrix.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:52 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.aviatrix
#
# instead of
#
#   >>> import terrascript.provider.AviatrixSystems.aviatrix
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.AviatrixSystems.aviatrix import *