# terrascript/provider/aviatrix.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:12:12 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.aviatrix
#
# instead of
#
#   >>> import terrascript.provider.AviatrixSystems.aviatrix
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.AviatrixSystems.aviatrix import *
