# terrascript/provider/azurestack.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:04 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.azurestack
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.azurestack
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.azurestack import *