# terrascript/provider/azuread.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:59 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.azuread
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.azuread
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.azuread import *