# terrascript/provider/bigip.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:05 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.bigip
#
# instead of
#
#   >>> import terrascript.provider.F5Networks.bigip
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.F5Networks.bigip import *