# terrascript/provider/boundary.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:38 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.boundary
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.boundary
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.boundary import *
