# terrascript/provider/brightbox.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:07 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.brightbox
#
# instead of
#
#   >>> import terrascript.provider.brightbox.brightbox
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.brightbox.brightbox import *