# terrascript/provider/cloudinit.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:14:09 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.cloudinit
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.cloudinit
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.cloudinit import *
