# terrascript/provider/datadog.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:17 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.datadog
#
# instead of
#
#   >>> import terrascript.provider.DataDog.datadog
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.DataDog.datadog import *