# terrascript/provider/digitalocean.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:18 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.digitalocean
#
# instead of
#
#   >>> import terrascript.provider.digitalocean.digitalocean
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.digitalocean.digitalocean import *