# terrascript/provider/fakewebservices.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:16:12 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.fakewebservices
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.fakewebservices
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.fakewebservices import *
