# terrascript/provider/fastly.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:26 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.fastly
#
# instead of
#
#   >>> import terrascript.provider.fastly.fastly
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.fastly.fastly import *