# terrascript/provider/googleworkspace.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:41 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.googleworkspace
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.googleworkspace
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.googleworkspace import *