# terrascript/provider/kubernetes.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:20:43 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.kubernetes
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.kubernetes
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.kubernetes import *
