# terrascript/provider/mongodbatlas.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:21:48 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.mongodbatlas
#
# instead of
#
#   >>> import terrascript.provider.mongodb.mongodbatlas
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.mongodb.mongodbatlas import *
