# terrascript/provider/netapp_gcp.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:22 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.netapp_gcp
#
# instead of
#
#   >>> import terrascript.provider.NetApp.netapp_gcp
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.NetApp.netapp_gcp import *