# terrascript/provider/oci.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:23:14 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.oci
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.oci
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.oci import *
