# terrascript/provider/pagerduty.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:41 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.pagerduty
#
# instead of
#
#   >>> import terrascript.provider.PagerDuty.pagerduty
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.PagerDuty.pagerduty import *