# terrascript/provider/sdm.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:26 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.sdm
#
# instead of
#
#   >>> import terrascript.provider.strongdm.sdm
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.strongdm.sdm import *
