# terrascript/provider/stackpath.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:13 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.stackpath
#
# instead of
#
#   >>> import terrascript.provider.stackpath.stackpath
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.stackpath.stackpath import *