# terrascript/provider/time.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:20 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.time
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.time
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.time import *