# terrascript/provider/tls.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:21 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.tls
#
# instead of
#
#   >>> import terrascript.provider.hashicorp.tls
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.hashicorp.tls import *