# terrascript/provider/transloadit.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:24 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.transloadit
#
# instead of
#
#   >>> import terrascript.provider.transloadit.transloadit
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.transloadit.transloadit import *