# terrascript/provider/triton.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:29:19 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.triton
#
# instead of
#
#   >>> import terrascript.provider.joyent.triton
#
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.joyent.triton import *
