# terrascript/provider/wavefront.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:39 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.provider.wavefront
#
# instead of
#
#   >>> import terrascript.provider.vmware.wavefront
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.provider.vmware.wavefront import *