# terrascript/resource/mrcrilly/awx.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:12:44 UTC)
import terrascript


class awx_credential_azure_key_vault(terrascript.Resource):
    pass


class awx_credential_input_source(terrascript.Resource):
    pass


class awx_credential_machine(terrascript.Resource):
    pass


__all__ = [
    "awx_credential_azure_key_vault",
    "awx_credential_input_source",
    "awx_credential_machine",
]
