# terrascript/resource/phzietsman/awsx.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:12:40 UTC)
import terrascript


class controltower_account_vending(terrascript.Resource):
    pass


__all__ = [
    "controltower_account_vending",
]
