# terrascript/azure_preview/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class azurepreview_budget(terrascript.Resource):
    pass


class azurepreview_subscription(terrascript.Resource):
    pass
