# terrascript/avi/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class avi_actiongroupconfig(terrascript.Resource):
    pass


class avi_albservicesconfig(terrascript.Resource):
    pass


class avi_albservicesfileupload(terrascript.Resource):
    pass


class avi_alertconfig(terrascript.Resource):
    pass


class avi_alertemailconfig(terrascript.Resource):
    pass


class avi_alertscriptconfig(terrascript.Resource):
    pass


class avi_alertsyslogconfig(terrascript.Resource):
    pass


class avi_analyticsprofile(terrascript.Resource):
    pass


class avi_applicationpersistenceprofile(terrascript.Resource):
    pass


class avi_applicationprofile(terrascript.Resource):
    pass


class avi_authprofile(terrascript.Resource):
    pass


class avi_autoscalelaunchconfig(terrascript.Resource):
    pass


class avi_availabilityzone(terrascript.Resource):
    pass


class avi_backup(terrascript.Resource):
    pass


class avi_backupconfiguration(terrascript.Resource):
    pass


class avi_botconfigconsolidator(terrascript.Resource):
    pass


class avi_botdetectionpolicy(terrascript.Resource):
    pass


class avi_botipreputationtypemapping(terrascript.Resource):
    pass


class avi_botmapping(terrascript.Resource):
    pass


class avi_certificatemanagementprofile(terrascript.Resource):
    pass


class avi_cloud(terrascript.Resource):
    pass


class avi_cloudconnectoruser(terrascript.Resource):
    pass


class avi_cloudproperties(terrascript.Resource):
    pass


class avi_cluster(terrascript.Resource):
    pass


class avi_clusterclouddetails(terrascript.Resource):
    pass


class avi_controllerportalregistration(terrascript.Resource):
    pass


class avi_controllerproperties(terrascript.Resource):
    pass


class avi_controllersite(terrascript.Resource):
    pass


class avi_customipamdnsprofile(terrascript.Resource):
    pass


class avi_dnspolicy(terrascript.Resource):
    pass


class avi_dynamicdnsrecord(terrascript.Resource):
    pass


class avi_errorpagebody(terrascript.Resource):
    pass


class avi_errorpageprofile(terrascript.Resource):
    pass


class avi_federationcheckpoint(terrascript.Resource):
    pass


class avi_fileobject(terrascript.Resource):
    pass


class avi_fileservice(terrascript.Resource):
    pass


class avi_geodb(terrascript.Resource):
    pass


class avi_gslb(terrascript.Resource):
    pass


class avi_gslbgeodbprofile(terrascript.Resource):
    pass


class avi_gslbservice(terrascript.Resource):
    pass


class avi_hardwaresecuritymodulegroup(terrascript.Resource):
    pass


class avi_healthmonitor(terrascript.Resource):
    pass


class avi_httppolicyset(terrascript.Resource):
    pass


class avi_icapprofile(terrascript.Resource):
    pass


class avi_image(terrascript.Resource):
    pass


class avi_inventoryfaultconfig(terrascript.Resource):
    pass


class avi_ipaddrgroup(terrascript.Resource):
    pass


class avi_ipamdnsproviderprofile(terrascript.Resource):
    pass


class avi_ipreputationdb(terrascript.Resource):
    pass


class avi_jwtserverprofile(terrascript.Resource):
    pass


class avi_l4policyset(terrascript.Resource):
    pass


class avi_labelgroup(terrascript.Resource):
    pass


class avi_licenseledgerdetails(terrascript.Resource):
    pass


class avi_memorybalancerrequest(terrascript.Resource):
    pass


class avi_microservicegroup(terrascript.Resource):
    pass


class avi_natpolicy(terrascript.Resource):
    pass


class avi_network(terrascript.Resource):
    pass


class avi_networkprofile(terrascript.Resource):
    pass


class avi_networksecuritypolicy(terrascript.Resource):
    pass


class avi_networkservice(terrascript.Resource):
    pass


class avi_nsxtsegmentruntime(terrascript.Resource):
    pass


class avi_pingaccessagent(terrascript.Resource):
    pass


class avi_pkiprofile(terrascript.Resource):
    pass


class avi_pool(terrascript.Resource):
    pass


class avi_poolgroup(terrascript.Resource):
    pass


class avi_poolgroupdeploymentpolicy(terrascript.Resource):
    pass


class avi_prioritylabels(terrascript.Resource):
    pass


class avi_protocolparser(terrascript.Resource):
    pass


class avi_rmcloudopsproto(terrascript.Resource):
    pass


class avi_role(terrascript.Resource):
    pass


class avi_scheduler(terrascript.Resource):
    pass


class avi_securitymanagerdata(terrascript.Resource):
    pass


class avi_securitypolicy(terrascript.Resource):
    pass


class avi_seproperties(terrascript.Resource):
    pass


class avi_server(terrascript.Resource):
    pass


class avi_serverautoscalepolicy(terrascript.Resource):
    pass


class avi_serviceengine(terrascript.Resource):
    pass


class avi_serviceenginegroup(terrascript.Resource):
    pass


class avi_siteversion(terrascript.Resource):
    pass


class avi_snmptrapprofile(terrascript.Resource):
    pass


class avi_sslkeyandcertificate(terrascript.Resource):
    pass


class avi_sslprofile(terrascript.Resource):
    pass


class avi_ssopolicy(terrascript.Resource):
    pass


class avi_stringgroup(terrascript.Resource):
    pass


class avi_systemconfiguration(terrascript.Resource):
    pass


class avi_systemlimits(terrascript.Resource):
    pass


class avi_tenant(terrascript.Resource):
    pass


class avi_testsedatastorelevel1(terrascript.Resource):
    pass


class avi_testsedatastorelevel2(terrascript.Resource):
    pass


class avi_testsedatastorelevel3(terrascript.Resource):
    pass


class avi_trafficcloneprofile(terrascript.Resource):
    pass


class avi_upgradestatusinfo(terrascript.Resource):
    pass


class avi_upgradestatussummary(terrascript.Resource):
    pass


class avi_user(terrascript.Resource):
    pass


class avi_useraccount(terrascript.Resource):
    pass


class avi_useraccountprofile(terrascript.Resource):
    pass


class avi_vcenterserver(terrascript.Resource):
    pass


class avi_virtualservice(terrascript.Resource):
    pass


class avi_vrfcontext(terrascript.Resource):
    pass


class avi_vsdatascriptset(terrascript.Resource):
    pass


class avi_vsvip(terrascript.Resource):
    pass


class avi_wafapplicationsignatureprovider(terrascript.Resource):
    pass


class avi_wafcrs(terrascript.Resource):
    pass


class avi_wafpolicy(terrascript.Resource):
    pass


class avi_wafpolicypsmgroup(terrascript.Resource):
    pass


class avi_wafprofile(terrascript.Resource):
    pass


class avi_webhook(terrascript.Resource):
    pass
