# terrascript/data/onelogin/onelogin.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:23:37 UTC)
import terrascript


class onelogin_user(terrascript.Data):
    pass


class onelogin_users(terrascript.Data):
    pass


__all__ = [
    "onelogin_user",
    "onelogin_users",
]
