# terrascript/resource/Mongey/hellosign.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:22 UTC)
import terrascript


class hellosign_api_app(terrascript.Resource):
    pass


__all__ = [
    "hellosign_api_app",
]
