# terrascript/data/cloudknox/cloudknox.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:11 UTC)
import terrascript


class cloudknox_role_policy(terrascript.Data):
    pass


__all__ = [
    "cloudknox_role_policy",
]
