# terrascript/data/sethvargo/berglas.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:20 UTC)
import terrascript


class berglas_secret(terrascript.Data):
    pass


__all__ = [
    "berglas_secret",
]
