# terrascript/provider/databrickslabs/databricks.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:14:57 UTC)

import terrascript


class databricks(terrascript.Provider):
    """Databricks Terraform Provider"""

    __description__ = "Databricks Terraform Provider"
    __namespace__ = "databrickslabs"
    __name__ = "databricks"
    __source__ = "https://github.com/databrickslabs/terraform-provider-databricks"
    __version__ = "0.3.7"
    __published__ = "2021-08-02T17:18:16Z"
    __tier__ = "partner"


__all__ = ["databricks"]
