# terrascript/kubeflowpipelines/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class kubeflowpipelines_experiment(terrascript.Data):
    pass


class kubeflowpipelines_pipeline(terrascript.Data):
    pass
