# terrascript/provider/F5Networks/bigip.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:25 UTC)

import terrascript


class bigip(terrascript.Provider):
    """Terraform resources that can configure F5 BIG-IP products"""

    __description__ = "Terraform resources that can configure F5 BIG-IP products"
    __namespace__ = "F5Networks"
    __name__ = "bigip"
    __source__ = "https://github.com/F5Networks/terraform-provider-bigip"
    __version__ = "1.11.1"
    __published__ = "2021-09-16T19:24:27Z"
    __tier__ = "partner"


__all__ = ["bigip"]
