# terrascript/sumologic/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class sumologic_aws_inventory_source(terrascript.Resource):
    pass


class sumologic_aws_xray_source(terrascript.Resource):
    pass


class sumologic_cloud_to_cloud_source(terrascript.Resource):
    pass


class sumologic_cloudfront_source(terrascript.Resource):
    pass


class sumologic_cloudsyslog_source(terrascript.Resource):
    pass


class sumologic_cloudtrail_source(terrascript.Resource):
    pass


class sumologic_cloudwatch_source(terrascript.Resource):
    pass


class sumologic_collector(terrascript.Resource):
    pass


class sumologic_collector_ingest_budget_assignment(terrascript.Resource):
    pass


class sumologic_connection(terrascript.Resource):
    pass


class sumologic_content(terrascript.Resource):
    pass


class sumologic_dashboard(terrascript.Resource):
    pass


class sumologic_elb_source(terrascript.Resource):
    pass


class sumologic_field(terrascript.Resource):
    pass


class sumologic_field_extraction_rule(terrascript.Resource):
    pass


class sumologic_folder(terrascript.Resource):
    pass


class sumologic_gcp_source(terrascript.Resource):
    pass


class sumologic_http_source(terrascript.Resource):
    pass


class sumologic_ingest_budget(terrascript.Resource):
    pass


class sumologic_ingest_budget_v2(terrascript.Resource):
    pass


class sumologic_kinesis_metrics_source(terrascript.Resource):
    pass


class sumologic_lookup_table(terrascript.Resource):
    pass


class sumologic_metadata_source(terrascript.Resource):
    pass


class sumologic_monitor(terrascript.Resource):
    pass


class sumologic_monitor_folder(terrascript.Resource):
    pass


class sumologic_partition(terrascript.Resource):
    pass


class sumologic_password_policy(terrascript.Resource):
    pass


class sumologic_polling_source(terrascript.Resource):
    pass


class sumologic_role(terrascript.Resource):
    pass


class sumologic_s3_audit_source(terrascript.Resource):
    pass


class sumologic_s3_source(terrascript.Resource):
    pass


class sumologic_saml_configuration(terrascript.Resource):
    pass


class sumologic_scheduled_view(terrascript.Resource):
    pass


class sumologic_subdomain(terrascript.Resource):
    pass


class sumologic_token(terrascript.Resource):
    pass


class sumologic_user(terrascript.Resource):
    pass
