# terrascript/teamcity/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class teamcity_agent_pool(terrascript.Resource):
    pass


class teamcity_agent_pool_project_assignment(terrascript.Resource):
    pass


class teamcity_agent_requirement(terrascript.Resource):
    pass


class teamcity_artifact_dependency(terrascript.Resource):
    pass


class teamcity_build_config(terrascript.Resource):
    pass


class teamcity_build_trigger_build_finish(terrascript.Resource):
    pass


class teamcity_build_trigger_schedule(terrascript.Resource):
    pass


class teamcity_build_trigger_vcs(terrascript.Resource):
    pass


class teamcity_feature_commit_status_publisher(terrascript.Resource):
    pass


class teamcity_feature_golang(terrascript.Resource):
    pass


class teamcity_group(terrascript.Resource):
    pass


class teamcity_project(terrascript.Resource):
    pass


class teamcity_project_feature_oauth_provider_settings(terrascript.Resource):
    pass


class teamcity_project_feature_versioned_settings(terrascript.Resource):
    pass


class teamcity_snapshot_dependency(terrascript.Resource):
    pass


class teamcity_vcs_root_git(terrascript.Resource):
    pass
