# terrascript/oci/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class oci_ai_anomaly_detection_ai_private_endpoint(terrascript.Resource):
    pass


class oci_ai_anomaly_detection_data_asset(terrascript.Resource):
    pass


class oci_ai_anomaly_detection_model(terrascript.Resource):
    pass


class oci_ai_anomaly_detection_project(terrascript.Resource):
    pass


class oci_analytics_analytics_instance(terrascript.Resource):
    pass


class oci_analytics_analytics_instance_private_access_channel(terrascript.Resource):
    pass


class oci_analytics_analytics_instance_vanity_url(terrascript.Resource):
    pass


class oci_apigateway_api(terrascript.Resource):
    pass


class oci_apigateway_certificate(terrascript.Resource):
    pass


class oci_apigateway_deployment(terrascript.Resource):
    pass


class oci_apigateway_gateway(terrascript.Resource):
    pass


class oci_apm_apm_domain(terrascript.Resource):
    pass


class oci_apm_synthetics_monitor(terrascript.Resource):
    pass


class oci_apm_synthetics_script(terrascript.Resource):
    pass


class oci_artifacts_container_configuration(terrascript.Resource):
    pass


class oci_artifacts_container_image_signature(terrascript.Resource):
    pass


class oci_artifacts_container_repository(terrascript.Resource):
    pass


class oci_artifacts_generic_artifact(terrascript.Resource):
    pass


class oci_artifacts_repository(terrascript.Resource):
    pass


class oci_audit_configuration(terrascript.Resource):
    pass


class oci_autoscaling_auto_scaling_configuration(terrascript.Resource):
    pass


class oci_bastion_bastion(terrascript.Resource):
    pass


class oci_bastion_session(terrascript.Resource):
    pass


class oci_bds_auto_scaling_configuration(terrascript.Resource):
    pass


class oci_bds_bds_instance(terrascript.Resource):
    pass


class oci_blockchain_blockchain_platform(terrascript.Resource):
    pass


class oci_blockchain_osn(terrascript.Resource):
    pass


class oci_blockchain_peer(terrascript.Resource):
    pass


class oci_budget_alert_rule(terrascript.Resource):
    pass


class oci_budget_budget(terrascript.Resource):
    pass


class oci_cloud_guard_cloud_guard_configuration(terrascript.Resource):
    pass


class oci_cloud_guard_data_mask_rule(terrascript.Resource):
    pass


class oci_cloud_guard_detector_recipe(terrascript.Resource):
    pass


class oci_cloud_guard_managed_list(terrascript.Resource):
    pass


class oci_cloud_guard_responder_recipe(terrascript.Resource):
    pass


class oci_cloud_guard_target(terrascript.Resource):
    pass


class oci_containerengine_cluster(terrascript.Resource):
    pass


class oci_containerengine_node_pool(terrascript.Resource):
    pass


class oci_core_app_catalog_listing_resource_version_agreement(terrascript.Resource):
    pass


class oci_core_app_catalog_subscription(terrascript.Resource):
    pass


class oci_core_boot_volume(terrascript.Resource):
    pass


class oci_core_boot_volume_backup(terrascript.Resource):
    pass


class oci_core_cluster_network(terrascript.Resource):
    pass


class oci_core_compute_capacity_reservation(terrascript.Resource):
    pass


class oci_core_compute_image_capability_schema(terrascript.Resource):
    pass


class oci_core_console_history(terrascript.Resource):
    pass


class oci_core_cpe(terrascript.Resource):
    pass


class oci_core_cross_connect(terrascript.Resource):
    pass


class oci_core_cross_connect_group(terrascript.Resource):
    pass


class oci_core_dedicated_vm_host(terrascript.Resource):
    pass


class oci_core_default_dhcp_options(terrascript.Resource):
    pass


class oci_core_default_route_table(terrascript.Resource):
    pass


class oci_core_default_security_list(terrascript.Resource):
    pass


class oci_core_dhcp_options(terrascript.Resource):
    pass


class oci_core_drg(terrascript.Resource):
    pass


class oci_core_drg_attachment(terrascript.Resource):
    pass


class oci_core_drg_attachment_management(terrascript.Resource):
    pass


class oci_core_drg_attachments_list(terrascript.Resource):
    pass


class oci_core_drg_route_distribution(terrascript.Resource):
    pass


class oci_core_drg_route_distribution_statement(terrascript.Resource):
    pass


class oci_core_drg_route_table(terrascript.Resource):
    pass


class oci_core_drg_route_table_route_rule(terrascript.Resource):
    pass


class oci_core_image(terrascript.Resource):
    pass


class oci_core_instance(terrascript.Resource):
    pass


class oci_core_instance_configuration(terrascript.Resource):
    pass


class oci_core_instance_console_connection(terrascript.Resource):
    pass


class oci_core_instance_pool(terrascript.Resource):
    pass


class oci_core_instance_pool_instance(terrascript.Resource):
    pass


class oci_core_internet_gateway(terrascript.Resource):
    pass


class oci_core_ipsec(terrascript.Resource):
    pass


class oci_core_ipsec_connection_tunnel_management(terrascript.Resource):
    pass


class oci_core_ipv6(terrascript.Resource):
    pass


class oci_core_listing_resource_version_agreement(terrascript.Resource):
    pass


class oci_core_local_peering_gateway(terrascript.Resource):
    pass


class oci_core_nat_gateway(terrascript.Resource):
    pass


class oci_core_network_security_group(terrascript.Resource):
    pass


class oci_core_network_security_group_security_rule(terrascript.Resource):
    pass


class oci_core_private_ip(terrascript.Resource):
    pass


class oci_core_public_ip(terrascript.Resource):
    pass


class oci_core_public_ip_pool(terrascript.Resource):
    pass


class oci_core_public_ip_pool_capacity(terrascript.Resource):
    pass


class oci_core_remote_peering_connection(terrascript.Resource):
    pass


class oci_core_route_table(terrascript.Resource):
    pass


class oci_core_route_table_attachment(terrascript.Resource):
    pass


class oci_core_security_list(terrascript.Resource):
    pass


class oci_core_service_gateway(terrascript.Resource):
    pass


class oci_core_shape_management(terrascript.Resource):
    pass


class oci_core_subnet(terrascript.Resource):
    pass


class oci_core_vcn(terrascript.Resource):
    pass


class oci_core_virtual_circuit(terrascript.Resource):
    pass


class oci_core_virtual_network(terrascript.Resource):
    pass


class oci_core_vlan(terrascript.Resource):
    pass


class oci_core_vnic_attachment(terrascript.Resource):
    pass


class oci_core_volume(terrascript.Resource):
    pass


class oci_core_volume_attachment(terrascript.Resource):
    pass


class oci_core_volume_backup(terrascript.Resource):
    pass


class oci_core_volume_backup_policy(terrascript.Resource):
    pass


class oci_core_volume_backup_policy_assignment(terrascript.Resource):
    pass


class oci_core_volume_group(terrascript.Resource):
    pass


class oci_core_volume_group_backup(terrascript.Resource):
    pass


class oci_data_safe_data_safe_configuration(terrascript.Resource):
    pass


class oci_data_safe_data_safe_private_endpoint(terrascript.Resource):
    pass


class oci_data_safe_on_prem_connector(terrascript.Resource):
    pass


class oci_data_safe_target_database(terrascript.Resource):
    pass


class oci_database_autonomous_container_database(terrascript.Resource):
    pass


class oci_database_autonomous_container_database_dataguard_association_operation(
    terrascript.Resource
):
    pass


class oci_database_autonomous_database(terrascript.Resource):
    pass


class oci_database_autonomous_database_backup(terrascript.Resource):
    pass


class oci_database_autonomous_database_instance_wallet_management(terrascript.Resource):
    pass


class oci_database_autonomous_database_regional_wallet_management(terrascript.Resource):
    pass


class oci_database_autonomous_database_wallet(terrascript.Resource):
    pass


class oci_database_autonomous_exadata_infrastructure(terrascript.Resource):
    pass


class oci_database_autonomous_vm_cluster(terrascript.Resource):
    pass


class oci_database_backup(terrascript.Resource):
    pass


class oci_database_backup_destination(terrascript.Resource):
    pass


class oci_database_cloud_database_management(terrascript.Resource):
    pass


class oci_database_cloud_exadata_infrastructure(terrascript.Resource):
    pass


class oci_database_cloud_vm_cluster(terrascript.Resource):
    pass


class oci_database_data_guard_association(terrascript.Resource):
    pass


class oci_database_database(terrascript.Resource):
    pass


class oci_database_database_software_image(terrascript.Resource):
    pass


class oci_database_database_upgrade(terrascript.Resource):
    pass


class oci_database_db_home(terrascript.Resource):
    pass


class oci_database_db_node_console_connection(terrascript.Resource):
    pass


class oci_database_db_system(terrascript.Resource):
    pass


class oci_database_exadata_infrastructure(terrascript.Resource):
    pass


class oci_database_exadata_infrastructure_storage(terrascript.Resource):
    pass


class oci_database_exadata_iorm_config(terrascript.Resource):
    pass


class oci_database_external_container_database(terrascript.Resource):
    pass


class oci_database_external_container_database_management(terrascript.Resource):
    pass


class oci_database_external_database_connector(terrascript.Resource):
    pass


class oci_database_external_non_container_database(terrascript.Resource):
    pass


class oci_database_external_non_container_database_management(terrascript.Resource):
    pass


class oci_database_external_non_container_database_operations_insights_management(
    terrascript.Resource
):
    pass


class oci_database_external_pluggable_database(terrascript.Resource):
    pass


class oci_database_external_pluggable_database_management(terrascript.Resource):
    pass


class oci_database_external_pluggable_database_operations_insights_management(
    terrascript.Resource
):
    pass


class oci_database_key_store(terrascript.Resource):
    pass


class oci_database_maintenance_run(terrascript.Resource):
    pass


class oci_database_management_db_management_private_endpoint(terrascript.Resource):
    pass


class oci_database_management_managed_database_group(terrascript.Resource):
    pass


class oci_database_management_managed_databases_change_database_parameter(
    terrascript.Resource
):
    pass


class oci_database_management_managed_databases_reset_database_parameter(
    terrascript.Resource
):
    pass


class oci_database_migration(terrascript.Resource):
    pass


class oci_database_migration_agent(terrascript.Resource):
    pass


class oci_database_migration_connection(terrascript.Resource):
    pass


class oci_database_migration_job(terrascript.Resource):
    pass


class oci_database_migration_migration(terrascript.Resource):
    pass


class oci_database_pluggable_database(terrascript.Resource):
    pass


class oci_database_pluggable_databases_local_clone(terrascript.Resource):
    pass


class oci_database_pluggable_databases_remote_clone(terrascript.Resource):
    pass


class oci_database_vm_cluster(terrascript.Resource):
    pass


class oci_database_vm_cluster_network(terrascript.Resource):
    pass


class oci_datacatalog_catalog(terrascript.Resource):
    pass


class oci_datacatalog_catalog_private_endpoint(terrascript.Resource):
    pass


class oci_datacatalog_connection(terrascript.Resource):
    pass


class oci_datacatalog_data_asset(terrascript.Resource):
    pass


class oci_datacatalog_metastore(terrascript.Resource):
    pass


class oci_dataflow_application(terrascript.Resource):
    pass


class oci_dataflow_invoke_run(terrascript.Resource):
    pass


class oci_dataflow_private_endpoint(terrascript.Resource):
    pass


class oci_dataintegration_workspace(terrascript.Resource):
    pass


class oci_datascience_job(terrascript.Resource):
    pass


class oci_datascience_job_run(terrascript.Resource):
    pass


class oci_datascience_model(terrascript.Resource):
    pass


class oci_datascience_model_deployment(terrascript.Resource):
    pass


class oci_datascience_model_provenance(terrascript.Resource):
    pass


class oci_datascience_notebook_session(terrascript.Resource):
    pass


class oci_datascience_project(terrascript.Resource):
    pass


class oci_devops_deploy_artifact(terrascript.Resource):
    pass


class oci_devops_deploy_environment(terrascript.Resource):
    pass


class oci_devops_deploy_pipeline(terrascript.Resource):
    pass


class oci_devops_deploy_stage(terrascript.Resource):
    pass


class oci_devops_deployment(terrascript.Resource):
    pass


class oci_devops_project(terrascript.Resource):
    pass


class oci_dns_record(terrascript.Resource):
    pass


class oci_dns_resolver(terrascript.Resource):
    pass


class oci_dns_resolver_endpoint(terrascript.Resource):
    pass


class oci_dns_rrset(terrascript.Resource):
    pass


class oci_dns_steering_policy(terrascript.Resource):
    pass


class oci_dns_steering_policy_attachment(terrascript.Resource):
    pass


class oci_dns_tsig_key(terrascript.Resource):
    pass


class oci_dns_view(terrascript.Resource):
    pass


class oci_dns_zone(terrascript.Resource):
    pass


class oci_email_dkim(terrascript.Resource):
    pass


class oci_email_email_domain(terrascript.Resource):
    pass


class oci_email_sender(terrascript.Resource):
    pass


class oci_email_suppression(terrascript.Resource):
    pass


class oci_events_rule(terrascript.Resource):
    pass


class oci_file_storage_export(terrascript.Resource):
    pass


class oci_file_storage_export_set(terrascript.Resource):
    pass


class oci_file_storage_file_system(terrascript.Resource):
    pass


class oci_file_storage_mount_target(terrascript.Resource):
    pass


class oci_file_storage_snapshot(terrascript.Resource):
    pass


class oci_functions_application(terrascript.Resource):
    pass


class oci_functions_function(terrascript.Resource):
    pass


class oci_functions_invoke_function(terrascript.Resource):
    pass


class oci_generic_artifacts_content_artifact_by_path(terrascript.Resource):
    pass


class oci_golden_gate_database_registration(terrascript.Resource):
    pass


class oci_golden_gate_deployment(terrascript.Resource):
    pass


class oci_golden_gate_deployment_backup(terrascript.Resource):
    pass


class oci_health_checks_http_monitor(terrascript.Resource):
    pass


class oci_health_checks_http_probe(terrascript.Resource):
    pass


class oci_health_checks_ping_monitor(terrascript.Resource):
    pass


class oci_health_checks_ping_probe(terrascript.Resource):
    pass


class oci_identity_api_key(terrascript.Resource):
    pass


class oci_identity_auth_token(terrascript.Resource):
    pass


class oci_identity_authentication_policy(terrascript.Resource):
    pass


class oci_identity_compartment(terrascript.Resource):
    pass


class oci_identity_customer_secret_key(terrascript.Resource):
    pass


class oci_identity_dynamic_group(terrascript.Resource):
    pass


class oci_identity_group(terrascript.Resource):
    pass


class oci_identity_identity_provider(terrascript.Resource):
    pass


class oci_identity_idp_group_mapping(terrascript.Resource):
    pass


class oci_identity_network_source(terrascript.Resource):
    pass


class oci_identity_policy(terrascript.Resource):
    pass


class oci_identity_smtp_credential(terrascript.Resource):
    pass


class oci_identity_swift_password(terrascript.Resource):
    pass


class oci_identity_tag(terrascript.Resource):
    pass


class oci_identity_tag_default(terrascript.Resource):
    pass


class oci_identity_tag_namespace(terrascript.Resource):
    pass


class oci_identity_ui_password(terrascript.Resource):
    pass


class oci_identity_user(terrascript.Resource):
    pass


class oci_identity_user_capabilities_management(terrascript.Resource):
    pass


class oci_identity_user_group_membership(terrascript.Resource):
    pass


class oci_integration_integration_instance(terrascript.Resource):
    pass


class oci_jms_fleet(terrascript.Resource):
    pass


class oci_kms_encrypted_data(terrascript.Resource):
    pass


class oci_kms_generated_key(terrascript.Resource):
    pass


class oci_kms_key(terrascript.Resource):
    pass


class oci_kms_key_version(terrascript.Resource):
    pass


class oci_kms_sign(terrascript.Resource):
    pass


class oci_kms_vault(terrascript.Resource):
    pass


class oci_kms_vault_replication(terrascript.Resource):
    pass


class oci_kms_verify(terrascript.Resource):
    pass


class oci_limits_quota(terrascript.Resource):
    pass


class oci_load_balancer(terrascript.Resource):
    pass


class oci_load_balancer_backend(terrascript.Resource):
    pass


class oci_load_balancer_backend_set(terrascript.Resource):
    pass


class oci_load_balancer_backendset(terrascript.Resource):
    pass


class oci_load_balancer_certificate(terrascript.Resource):
    pass


class oci_load_balancer_hostname(terrascript.Resource):
    pass


class oci_load_balancer_listener(terrascript.Resource):
    pass


class oci_load_balancer_load_balancer(terrascript.Resource):
    pass


class oci_load_balancer_load_balancer_routing_policy(terrascript.Resource):
    pass


class oci_load_balancer_path_route_set(terrascript.Resource):
    pass


class oci_load_balancer_rule_set(terrascript.Resource):
    pass


class oci_load_balancer_ssl_cipher_suite(terrascript.Resource):
    pass


class oci_log_analytics_log_analytics_entity(terrascript.Resource):
    pass


class oci_log_analytics_log_analytics_import_custom_content(terrascript.Resource):
    pass


class oci_log_analytics_log_analytics_log_group(terrascript.Resource):
    pass


class oci_log_analytics_log_analytics_object_collection_rule(terrascript.Resource):
    pass


class oci_log_analytics_namespace(terrascript.Resource):
    pass


class oci_logging_log(terrascript.Resource):
    pass


class oci_logging_log_group(terrascript.Resource):
    pass


class oci_logging_log_saved_search(terrascript.Resource):
    pass


class oci_logging_unified_agent_configuration(terrascript.Resource):
    pass


class oci_management_agent_management_agent(terrascript.Resource):
    pass


class oci_management_agent_management_agent_install_key(terrascript.Resource):
    pass


class oci_management_dashboard_management_dashboards_import(terrascript.Resource):
    pass


class oci_marketplace_accepted_agreement(terrascript.Resource):
    pass


class oci_marketplace_listing_package_agreement(terrascript.Resource):
    pass


class oci_marketplace_publication(terrascript.Resource):
    pass


class oci_metering_computation_custom_table(terrascript.Resource):
    pass


class oci_metering_computation_query(terrascript.Resource):
    pass


class oci_metering_computation_usage(terrascript.Resource):
    pass


class oci_monitoring_alarm(terrascript.Resource):
    pass


class oci_mysql_analytics_cluster(terrascript.Resource):
    pass


class oci_mysql_channel(terrascript.Resource):
    pass


class oci_mysql_heat_wave_cluster(terrascript.Resource):
    pass


class oci_mysql_mysql_backup(terrascript.Resource):
    pass


class oci_mysql_mysql_db_system(terrascript.Resource):
    pass


class oci_network_load_balancer_backend(terrascript.Resource):
    pass


class oci_network_load_balancer_backend_set(terrascript.Resource):
    pass


class oci_network_load_balancer_listener(terrascript.Resource):
    pass


class oci_network_load_balancer_network_load_balancer(terrascript.Resource):
    pass


class oci_nosql_index(terrascript.Resource):
    pass


class oci_nosql_table(terrascript.Resource):
    pass


class oci_objectstorage_bucket(terrascript.Resource):
    pass


class oci_objectstorage_namespace_metadata(terrascript.Resource):
    pass


class oci_objectstorage_object(terrascript.Resource):
    pass


class oci_objectstorage_object_lifecycle_policy(terrascript.Resource):
    pass


class oci_objectstorage_preauthrequest(terrascript.Resource):
    pass


class oci_objectstorage_replication_policy(terrascript.Resource):
    pass


class oci_oce_oce_instance(terrascript.Resource):
    pass


class oci_ocvp_esxi_host(terrascript.Resource):
    pass


class oci_ocvp_sddc(terrascript.Resource):
    pass


class oci_oda_oda_instance(terrascript.Resource):
    pass


class oci_ons_notification_topic(terrascript.Resource):
    pass


class oci_ons_subscription(terrascript.Resource):
    pass


class oci_opsi_database_insight(terrascript.Resource):
    pass


class oci_opsi_enterprise_manager_bridge(terrascript.Resource):
    pass


class oci_opsi_host_insight(terrascript.Resource):
    pass


class oci_optimizer_enrollment_status(terrascript.Resource):
    pass


class oci_optimizer_profile(terrascript.Resource):
    pass


class oci_optimizer_recommendation(terrascript.Resource):
    pass


class oci_optimizer_resource_action(terrascript.Resource):
    pass


class oci_osmanagement_managed_instance(terrascript.Resource):
    pass


class oci_osmanagement_managed_instance_group(terrascript.Resource):
    pass


class oci_osmanagement_managed_instance_management(terrascript.Resource):
    pass


class oci_osmanagement_software_source(terrascript.Resource):
    pass


class oci_sch_service_connector(terrascript.Resource):
    pass


class oci_service_catalog_private_application(terrascript.Resource):
    pass


class oci_service_catalog_service_catalog(terrascript.Resource):
    pass


class oci_service_catalog_service_catalog_association(terrascript.Resource):
    pass


class oci_streaming_connect_harness(terrascript.Resource):
    pass


class oci_streaming_stream(terrascript.Resource):
    pass


class oci_streaming_stream_pool(terrascript.Resource):
    pass


class oci_vulnerability_scanning_container_scan_recipe(terrascript.Resource):
    pass


class oci_vulnerability_scanning_container_scan_target(terrascript.Resource):
    pass


class oci_vulnerability_scanning_host_scan_recipe(terrascript.Resource):
    pass


class oci_vulnerability_scanning_host_scan_target(terrascript.Resource):
    pass


class oci_waas_address_list(terrascript.Resource):
    pass


class oci_waas_certificate(terrascript.Resource):
    pass


class oci_waas_custom_protection_rule(terrascript.Resource):
    pass


class oci_waas_http_redirect(terrascript.Resource):
    pass


class oci_waas_protection_rule(terrascript.Resource):
    pass


class oci_waas_purge_cache(terrascript.Resource):
    pass


class oci_waas_waas_policy(terrascript.Resource):
    pass
