# terrascript/ecloud/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class ecloud_firewallpolicy(terrascript.Resource):
    pass


class ecloud_firewallrule(terrascript.Resource):
    pass


class ecloud_floatingip(terrascript.Resource):
    pass


class ecloud_host(terrascript.Resource):
    pass


class ecloud_hostgroup(terrascript.Resource):
    pass


class ecloud_instance(terrascript.Resource):
    pass


class ecloud_network(terrascript.Resource):
    pass


class ecloud_networkpolicy(terrascript.Resource):
    pass


class ecloud_networkrule(terrascript.Resource):
    pass


class ecloud_router(terrascript.Resource):
    pass


class ecloud_ssh_keypair(terrascript.Resource):
    pass


class ecloud_volume(terrascript.Resource):
    pass


class ecloud_vpc(terrascript.Resource):
    pass
