# tests/test_provider_alertmixer_amixr.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:11:40 UTC)


def test_provider_import():
    import terrascript.provider.alertmixer.amixr


def test_resource_import():
    from terrascript.resource.alertmixer.amixr import amixr_escalation

    from terrascript.resource.alertmixer.amixr import amixr_integration

    from terrascript.resource.alertmixer.amixr import amixr_on_call_shift

    from terrascript.resource.alertmixer.amixr import amixr_route

    from terrascript.resource.alertmixer.amixr import amixr_schedule


def test_datasource_import():
    from terrascript.data.alertmixer.amixr import amixr_action

    from terrascript.data.alertmixer.amixr import amixr_schedule

    from terrascript.data.alertmixer.amixr import amixr_slack_channel

    from terrascript.data.alertmixer.amixr import amixr_user

    from terrascript.data.alertmixer.amixr import amixr_user_group


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.alertmixer.amixr
#
#      t = terrascript.provider.alertmixer.amixr.amixr()
#      s = str(t)
#
#      assert 'https://github.com/alertmixer/terraform-provider-amixr' in s
#      assert '0.2.3' in s
