# tests/test_provider_jeremmfr_lvsnetwork.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:21:28 UTC)


def test_provider_import():
    import terrascript.provider.jeremmfr.lvsnetwork


def test_resource_import():
    from terrascript.resource.jeremmfr.lvsnetwork import lvsnetwork_ifacevrrp

    from terrascript.resource.jeremmfr.lvsnetwork import lvsnetwork_vrrp_script


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.jeremmfr.lvsnetwork
#
#      t = terrascript.provider.jeremmfr.lvsnetwork.lvsnetwork()
#      s = str(t)
#
#      assert 'https://github.com/jeremmfr/terraform-provider-lvsnetwork' in s
#      assert '1.2.0' in s
