# tests/test_provider_greg-gajda_po.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:24:56 UTC)


def test_provider_import():
    import terrascript.provider.greg_gajda.po


def test_resource_import():
    from terrascript.resource.greg_gajda.po import po_alertmanager

    from terrascript.resource.greg_gajda.po import po_prometheus

    from terrascript.resource.greg_gajda.po import po_prometheus_rule

    from terrascript.resource.greg_gajda.po import po_service_monitor


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.greg_gajda.po
#
#      t = terrascript.provider.greg_gajda.po.po()
#      s = str(t)
#
#      assert 'https://github.com/greg-gajda/terraform-provider-po' in s
#      assert '1.0.0' in s
