# tests/test_provider_innovationnorway_tfvars.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:28:41 UTC)


def test_provider_import():
    import terrascript.provider.innovationnorway.tfvars


def test_datasource_import():
    from terrascript.data.innovationnorway.tfvars import tfvars_file


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.innovationnorway.tfvars
#
#      t = terrascript.provider.innovationnorway.tfvars.tfvars()
#      s = str(t)
#
#      assert 'https://github.com/innovationnorway/terraform-provider-tfvars' in s
#      assert '0.0.1' in s
