# tests/test_provider_TomTucka_circleci.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:55 UTC)


def test_provider_import():
    import terrascript.provider.TomTucka.circleci


def test_resource_import():
    from terrascript.resource.TomTucka.circleci import circleci_environment_variable

    from terrascript.resource.TomTucka.circleci import circleci_project


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.TomTucka.circleci
#
#      t = terrascript.provider.TomTucka.circleci.circleci()
#      s = str(t)
#
#      assert 'https://github.com/TomTucka/terraform-provider-circleci' in s
#      assert '0.4.0' in s
