#tests/test_provider_camptocamp_puppetca.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:47 UTC)

def test_provider_import():
    import terrascript.provider.camptocamp.puppetca


def test_resource_import():
    from terrascript.resource.camptocamp.puppetca import puppetca_certificate





# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.camptocamp.puppetca
#      
#      t = terrascript.provider.camptocamp.puppetca.puppetca()
#      s = str(t)
#      
#      assert 'https://github.com/camptocamp/terraform-provider-puppetca' in s
#      assert '1.3.0' in s
