#tests/test_provider_innovationnorway_domeneshop.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:20 UTC)

def test_provider_import():
    import terrascript.provider.innovationnorway.domeneshop


def test_resource_import():
    from terrascript.resource.innovationnorway.domeneshop import domeneshop_forward

    from terrascript.resource.innovationnorway.domeneshop import domeneshop_record




def test_datasource_import():
    from terrascript.data.innovationnorway.domeneshop import domeneshop_domain

    from terrascript.data.innovationnorway.domeneshop import domeneshop_domains

    from terrascript.data.innovationnorway.domeneshop import domeneshop_forward

    from terrascript.data.innovationnorway.domeneshop import domeneshop_forwards

    from terrascript.data.innovationnorway.domeneshop import domeneshop_record

    from terrascript.data.innovationnorway.domeneshop import domeneshop_records



# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.innovationnorway.domeneshop
#      
#      t = terrascript.provider.innovationnorway.domeneshop.domeneshop()
#      s = str(t)
#      
#      assert 'https://github.com/innovationnorway/terraform-provider-domeneshop' in s
#      assert '0.1.0' in s
