# tests/test_provider_ukfast_loadbalancer.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:21:15 UTC)


def test_provider_import():
    import terrascript.provider.ukfast.loadbalancer


def test_resource_import():
    from terrascript.resource.ukfast.loadbalancer import loadbalancer_accessip

    from terrascript.resource.ukfast.loadbalancer import loadbalancer_acl

    from terrascript.resource.ukfast.loadbalancer import loadbalancer_bind

    from terrascript.resource.ukfast.loadbalancer import loadbalancer_certificate

    from terrascript.resource.ukfast.loadbalancer import loadbalancer_cluster

    from terrascript.resource.ukfast.loadbalancer import loadbalancer_listener

    from terrascript.resource.ukfast.loadbalancer import loadbalancer_target

    from terrascript.resource.ukfast.loadbalancer import loadbalancer_targetgroup


def test_datasource_import():
    from terrascript.data.ukfast.loadbalancer import loadbalancer_accessip

    from terrascript.data.ukfast.loadbalancer import loadbalancer_acl

    from terrascript.data.ukfast.loadbalancer import loadbalancer_bind

    from terrascript.data.ukfast.loadbalancer import loadbalancer_certificate

    from terrascript.data.ukfast.loadbalancer import loadbalancer_cluster

    from terrascript.data.ukfast.loadbalancer import loadbalancer_listener

    from terrascript.data.ukfast.loadbalancer import loadbalancer_target

    from terrascript.data.ukfast.loadbalancer import loadbalancer_targetgroup


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.ukfast.loadbalancer
#
#      t = terrascript.provider.ukfast.loadbalancer.loadbalancer()
#      s = str(t)
#
#      assert 'https://github.com/ukfast/terraform-provider-loadbalancer' in s
#      assert '1.0.0-alpha1' in s
