# tests/test_provider_Mongey_kafka.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:20:06 UTC)


def test_provider_import():
    import terrascript.provider.Mongey.kafka


def test_resource_import():
    from terrascript.resource.Mongey.kafka import kafka_acl

    from terrascript.resource.Mongey.kafka import kafka_topic


def test_datasource_import():
    from terrascript.data.Mongey.kafka import kafka_topic


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.Mongey.kafka
#
#      t = terrascript.provider.Mongey.kafka.kafka()
#      s = str(t)
#
#      assert 'https://github.com/Mongey/terraform-provider-kafka' in s
#      assert '0.4.1' in s
