# tests/test_provider_fortinetdev_fortios.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:16:41 UTC)


def test_provider_import():
    import terrascript.provider.fortinetdev.fortios


def test_resource_import():
    from terrascript.resource.fortinetdev.fortios import fortios_alertemail_setting

    from terrascript.resource.fortinetdev.fortios import fortios_antivirus_heuristic

    from terrascript.resource.fortinetdev.fortios import fortios_antivirus_profile

    from terrascript.resource.fortinetdev.fortios import fortios_antivirus_quarantine

    from terrascript.resource.fortinetdev.fortios import fortios_antivirus_settings

    from terrascript.resource.fortinetdev.fortios import fortios_application_custom

    from terrascript.resource.fortinetdev.fortios import fortios_application_group

    from terrascript.resource.fortinetdev.fortios import fortios_application_list

    from terrascript.resource.fortinetdev.fortios import fortios_application_name

    from terrascript.resource.fortinetdev.fortios import (
        fortios_application_rulesettings,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_authentication_rule

    from terrascript.resource.fortinetdev.fortios import fortios_authentication_scheme

    from terrascript.resource.fortinetdev.fortios import fortios_authentication_setting

    from terrascript.resource.fortinetdev.fortios import fortios_certificate_ca

    from terrascript.resource.fortinetdev.fortios import fortios_certificate_crl

    from terrascript.resource.fortinetdev.fortios import fortios_certificate_local

    from terrascript.resource.fortinetdev.fortios import fortios_certificate_remote

    from terrascript.resource.fortinetdev.fortios import fortios_cifs_domaincontroller

    from terrascript.resource.fortinetdev.fortios import fortios_cifs_profile

    from terrascript.resource.fortinetdev.fortios import (
        fortios_credentialstore_domaincontroller,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_dlp_filepattern

    from terrascript.resource.fortinetdev.fortios import fortios_dlp_fpdocsource

    from terrascript.resource.fortinetdev.fortios import fortios_dlp_fpsensitivity

    from terrascript.resource.fortinetdev.fortios import fortios_dlp_sensitivity

    from terrascript.resource.fortinetdev.fortios import fortios_dlp_sensor

    from terrascript.resource.fortinetdev.fortios import fortios_dlp_settings

    from terrascript.resource.fortinetdev.fortios import fortios_dnsfilter_domainfilter

    from terrascript.resource.fortinetdev.fortios import fortios_dnsfilter_profile

    from terrascript.resource.fortinetdev.fortios import fortios_dpdk_cpus

    from terrascript.resource.fortinetdev.fortios import fortios_dpdk_global

    from terrascript.resource.fortinetdev.fortios import (
        fortios_emailfilter_blockallowlist,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_bwl

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_bword

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_dnsbl

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_fortishield

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_iptrust

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_mheader

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_options

    from terrascript.resource.fortinetdev.fortios import fortios_emailfilter_profile

    from terrascript.resource.fortinetdev.fortios import fortios_endpointcontrol_client

    from terrascript.resource.fortinetdev.fortios import fortios_endpointcontrol_fctems

    from terrascript.resource.fortinetdev.fortios import (
        fortios_endpointcontrol_forticlientems,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_endpointcontrol_forticlientregistrationsync,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_endpointcontrol_profile

    from terrascript.resource.fortinetdev.fortios import (
        fortios_endpointcontrol_registeredforticlient,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_endpointcontrol_settings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_extendercontroller_dataplan,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_extendercontroller_extender,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_extendercontroller_extender1,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_filefilter_profile

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_DoSpolicy

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_DoSpolicy6

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_address

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_address6

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_address6template,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_addrgrp

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_addrgrp6

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_authportal

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_centralsnatmap

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_centralsnatmap_move,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_centralsnatmap_sort,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_city

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_country

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_decryptedtrafficmirror,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_dnstranslation

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_identitybasedroute,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_interfacepolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_interfacepolicy6,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservice,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetserviceaddition,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetserviceappend,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicebotnet,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicecustom,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicecustomgroup,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicedefinition,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetserviceextension,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicegroup,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetserviceipblreason,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetserviceipblvendor,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicelist,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicename,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetserviceowner,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_internetservicereputation,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_ippool

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_ippool6

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_iptranslation

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_ipv6ehfilter

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_ldbmonitor

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_localinpolicy

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_localinpolicy6

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_multicastaddress,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_multicastaddress6,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_multicastpolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_multicastpolicy6,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_object_address

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_object_addressgroup,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_object_ippool

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_object_service

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_object_servicecategory,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_object_servicegroup,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_object_vip

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_object_vipgroup,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_policy

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_policy46

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_policy6

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_policy64

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_profilegroup

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_profileprotocoloptions,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_proxyaddress

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_proxyaddrgrp

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_proxypolicy

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_proxypolicy_move,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_proxypolicy_sort,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_region

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_security_policy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_security_policyseq,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewall_security_policysort,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_securitypolicy

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_shapingpolicy

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_shapingprofile

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_sniffer

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_sslserver

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_sslsshprofile

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_trafficclass

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_ttlpolicy

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vendormac

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vip

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vip46

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vip6

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vip64

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vipgrp

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vipgrp46

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vipgrp6

    from terrascript.resource.fortinetdev.fortios import fortios_firewall_vipgrp64

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallconsolidated_policy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallipmacbinding_setting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallipmacbinding_table,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewallschedule_group

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallschedule_onetime,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallschedule_recurring,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallservice_category,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewallservice_custom

    from terrascript.resource.fortinetdev.fortios import fortios_firewallservice_group

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallshaper_peripshaper,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallshaper_trafficshaper,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_firewallssh_hostkey

    from terrascript.resource.fortinetdev.fortios import fortios_firewallssh_localca

    from terrascript.resource.fortinetdev.fortios import fortios_firewallssh_localkey

    from terrascript.resource.fortinetdev.fortios import fortios_firewallssh_setting

    from terrascript.resource.fortinetdev.fortios import fortios_firewallssl_setting

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallwildcardfqdn_custom,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_firewallwildcardfqdn_group,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_devicemanager_device,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_devicemanager_install_device,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_devicemanager_install_policypackage,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_devicemanager_script,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_devicemanager_script_execute,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_firewall_object_address,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_firewall_object_ippool,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_firewall_object_service,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_firewall_object_vip

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_firewall_security_policy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_firewall_security_policypackage,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_jsonrpc_request

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_object_adom_revision,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_admin

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_system_admin_profiles,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_admin_user

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_adom

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_dns

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_global

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_system_license_forticare,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_license_vm

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_system_network_interface,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_fmg_system_network_route,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_ntp

    from terrascript.resource.fortinetdev.fortios import fortios_fmg_system_syslogserver

    from terrascript.resource.fortinetdev.fortios import fortios_ftpproxy_explicit

    from terrascript.resource.fortinetdev.fortios import fortios_icap_profile

    from terrascript.resource.fortinetdev.fortios import fortios_icap_server

    from terrascript.resource.fortinetdev.fortios import fortios_ips_custom

    from terrascript.resource.fortinetdev.fortios import fortios_ips_decoder

    from terrascript.resource.fortinetdev.fortios import fortios_ips_global

    from terrascript.resource.fortinetdev.fortios import fortios_ips_rule

    from terrascript.resource.fortinetdev.fortios import fortios_ips_rulesettings

    from terrascript.resource.fortinetdev.fortios import fortios_ips_sensor

    from terrascript.resource.fortinetdev.fortios import fortios_ips_settings

    from terrascript.resource.fortinetdev.fortios import fortios_ips_viewmap

    from terrascript.resource.fortinetdev.fortios import fortios_json_generic_api

    from terrascript.resource.fortinetdev.fortios import fortios_log_customfield

    from terrascript.resource.fortinetdev.fortios import fortios_log_eventfilter

    from terrascript.resource.fortinetdev.fortios import (
        fortios_log_fortianalyzer_setting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_log_guidisplay

    from terrascript.resource.fortinetdev.fortios import fortios_log_setting

    from terrascript.resource.fortinetdev.fortios import fortios_log_syslog_setting

    from terrascript.resource.fortinetdev.fortios import fortios_log_threatweight

    from terrascript.resource.fortinetdev.fortios import fortios_logdisk_filter

    from terrascript.resource.fortinetdev.fortios import fortios_logdisk_setting

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer2_filter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer2_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer2_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer2_setting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer3_filter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer3_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer3_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer3_setting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_logfortianalyzer_filter

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzer_setting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzercloud_filter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzercloud_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzercloud_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortianalyzercloud_setting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_logfortiguard_filter

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortiguard_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logfortiguard_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_logfortiguard_setting

    from terrascript.resource.fortinetdev.fortios import fortios_logmemory_filter

    from terrascript.resource.fortinetdev.fortios import fortios_logmemory_globalsetting

    from terrascript.resource.fortinetdev.fortios import fortios_logmemory_setting

    from terrascript.resource.fortinetdev.fortios import fortios_lognulldevice_filter

    from terrascript.resource.fortinetdev.fortios import fortios_lognulldevice_setting

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd2_filter

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd2_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd2_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd2_setting

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd3_filter

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd3_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd3_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd3_setting

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd4_filter

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd4_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd4_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd4_setting

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd_filter

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd_overridefilter,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_logsyslogd_overridesetting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_logsyslogd_setting

    from terrascript.resource.fortinetdev.fortios import fortios_logwebtrends_filter

    from terrascript.resource.fortinetdev.fortios import fortios_logwebtrends_setting

    from terrascript.resource.fortinetdev.fortios import (
        fortios_networking_interface_port,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_networking_route_static

    from terrascript.resource.fortinetdev.fortios import fortios_nsxt_servicechain

    from terrascript.resource.fortinetdev.fortios import fortios_nsxt_setting

    from terrascript.resource.fortinetdev.fortios import fortios_report_chart

    from terrascript.resource.fortinetdev.fortios import fortios_report_dataset

    from terrascript.resource.fortinetdev.fortios import fortios_report_layout

    from terrascript.resource.fortinetdev.fortios import fortios_report_setting

    from terrascript.resource.fortinetdev.fortios import fortios_report_style

    from terrascript.resource.fortinetdev.fortios import fortios_report_theme

    from terrascript.resource.fortinetdev.fortios import fortios_router_accesslist

    from terrascript.resource.fortinetdev.fortios import fortios_router_accesslist6

    from terrascript.resource.fortinetdev.fortios import fortios_router_aspathlist

    from terrascript.resource.fortinetdev.fortios import fortios_router_authpath

    from terrascript.resource.fortinetdev.fortios import fortios_router_bfd

    from terrascript.resource.fortinetdev.fortios import fortios_router_bfd6

    from terrascript.resource.fortinetdev.fortios import fortios_router_bgp

    from terrascript.resource.fortinetdev.fortios import fortios_router_communitylist

    from terrascript.resource.fortinetdev.fortios import fortios_router_isis

    from terrascript.resource.fortinetdev.fortios import fortios_router_keychain

    from terrascript.resource.fortinetdev.fortios import fortios_router_multicast

    from terrascript.resource.fortinetdev.fortios import fortios_router_multicast6

    from terrascript.resource.fortinetdev.fortios import fortios_router_multicastflow

    from terrascript.resource.fortinetdev.fortios import fortios_router_ospf

    from terrascript.resource.fortinetdev.fortios import fortios_router_ospf6

    from terrascript.resource.fortinetdev.fortios import fortios_router_policy

    from terrascript.resource.fortinetdev.fortios import fortios_router_policy6

    from terrascript.resource.fortinetdev.fortios import fortios_router_prefixlist

    from terrascript.resource.fortinetdev.fortios import fortios_router_prefixlist6

    from terrascript.resource.fortinetdev.fortios import fortios_router_rip

    from terrascript.resource.fortinetdev.fortios import fortios_router_ripng

    from terrascript.resource.fortinetdev.fortios import fortios_router_routemap

    from terrascript.resource.fortinetdev.fortios import fortios_router_setting

    from terrascript.resource.fortinetdev.fortios import fortios_router_static

    from terrascript.resource.fortinetdev.fortios import fortios_router_static6

    from terrascript.resource.fortinetdev.fortios import fortios_routerbgp_neighbor

    from terrascript.resource.fortinetdev.fortios import fortios_routerbgp_network

    from terrascript.resource.fortinetdev.fortios import fortios_routerbgp_network6

    from terrascript.resource.fortinetdev.fortios import (
        fortios_routerospf6_ospf6interface,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_routerospf_neighbor

    from terrascript.resource.fortinetdev.fortios import fortios_routerospf_network

    from terrascript.resource.fortinetdev.fortios import (
        fortios_routerospf_ospfinterface,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_bwl

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_bword

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_dnsbl

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_fortishield

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_iptrust

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_mheader

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_options

    from terrascript.resource.fortinetdev.fortios import fortios_spamfilter_profile

    from terrascript.resource.fortinetdev.fortios import fortios_sshfilter_profile

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_8021Xsettings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_customcommand,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_flowtracking,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_switchcontroller_global

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_igmpsnooping,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_lldpprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_lldpsettings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_location,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_macsyncsettings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_managedswitch,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_nacdevice,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_nacsettings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_networkmonitorsettings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_portpolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_quarantine,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_remotelog,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_switchcontroller_sflow

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_snmpcommunity,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_snmpsysinfo,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_snmptrapthreshold,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_snmpuser,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_stormcontrol,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_stormcontrolpolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_stpinstance,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_stpsettings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_switchgroup,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_switchinterfacetag,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_switchlog,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_switchprofile,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_switchcontroller_system

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_trafficpolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_trafficsniffer,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_virtualportpool,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_switchcontroller_vlan

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontroller_vlanpolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerautoconfig_custom,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerautoconfig_default,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerautoconfig_policy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerinitialconfig_template,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerinitialconfig_vlans,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerptp_policy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerptp_settings,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerqos_dot1pmap,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerqos_ipdscpmap,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerqos_qospolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollerqos_queuepolicy,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollersecuritypolicy_8021X,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollersecuritypolicy_captiveportal,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_switchcontrollersecuritypolicy_localaccess,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_accprofile

    from terrascript.resource.fortinetdev.fortios import fortios_system_admin

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_admin_administrator,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_admin_profiles

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_affinityinterrupt,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_affinitypacketredistribution,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_alarm

    from terrascript.resource.fortinetdev.fortios import fortios_system_alias

    from terrascript.resource.fortinetdev.fortios import fortios_system_apiuser

    from terrascript.resource.fortinetdev.fortios import fortios_system_apiuser_setting

    from terrascript.resource.fortinetdev.fortios import fortios_system_arptable

    from terrascript.resource.fortinetdev.fortios import fortios_system_autoinstall

    from terrascript.resource.fortinetdev.fortios import fortios_system_automationaction

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_automationdestination,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_automationstitch

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_automationtrigger,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_autoscript

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_centralmanagement,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_clustersync

    from terrascript.resource.fortinetdev.fortios import fortios_system_console

    from terrascript.resource.fortinetdev.fortios import fortios_system_csf

    from terrascript.resource.fortinetdev.fortios import fortios_system_customlanguage

    from terrascript.resource.fortinetdev.fortios import fortios_system_ddns

    from terrascript.resource.fortinetdev.fortios import fortios_system_dedicatedmgmt

    from terrascript.resource.fortinetdev.fortios import fortios_system_dns

    from terrascript.resource.fortinetdev.fortios import fortios_system_dnsdatabase

    from terrascript.resource.fortinetdev.fortios import fortios_system_dnsserver

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_dscpbasedpriority,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_emailserver

    from terrascript.resource.fortinetdev.fortios import fortios_system_externalresource

    from terrascript.resource.fortinetdev.fortios import fortios_system_federatedupgrade

    from terrascript.resource.fortinetdev.fortios import fortios_system_fipscc

    from terrascript.resource.fortinetdev.fortios import fortios_system_fm

    from terrascript.resource.fortinetdev.fortios import fortios_system_fortiguard

    from terrascript.resource.fortinetdev.fortios import fortios_system_fortimanager

    from terrascript.resource.fortinetdev.fortios import fortios_system_fortisandbox

    from terrascript.resource.fortinetdev.fortios import fortios_system_fssopolling

    from terrascript.resource.fortinetdev.fortios import fortios_system_ftmpush

    from terrascript.resource.fortinetdev.fortios import fortios_system_geneve

    from terrascript.resource.fortinetdev.fortios import fortios_system_geoipcountry

    from terrascript.resource.fortinetdev.fortios import fortios_system_geoipoverride

    from terrascript.resource.fortinetdev.fortios import fortios_system_global

    from terrascript.resource.fortinetdev.fortios import fortios_system_gretunnel

    from terrascript.resource.fortinetdev.fortios import fortios_system_ha

    from terrascript.resource.fortinetdev.fortios import fortios_system_hamonitor

    from terrascript.resource.fortinetdev.fortios import fortios_system_interface

    from terrascript.resource.fortinetdev.fortios import fortios_system_ipiptunnel

    from terrascript.resource.fortinetdev.fortios import fortios_system_ips

    from terrascript.resource.fortinetdev.fortios import fortios_system_ipsecaggregate

    from terrascript.resource.fortinetdev.fortios import fortios_system_ipsurlfilterdns

    from terrascript.resource.fortinetdev.fortios import fortios_system_ipsurlfilterdns6

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_ipv6neighborcache,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_ipv6tunnel

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_license_forticare,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_license_vdom

    from terrascript.resource.fortinetdev.fortios import fortios_system_license_vm

    from terrascript.resource.fortinetdev.fortios import fortios_system_linkmonitor

    from terrascript.resource.fortinetdev.fortios import fortios_system_macaddresstable

    from terrascript.resource.fortinetdev.fortios import fortios_system_managementtunnel

    from terrascript.resource.fortinetdev.fortios import fortios_system_mobiletunnel

    from terrascript.resource.fortinetdev.fortios import fortios_system_nat64

    from terrascript.resource.fortinetdev.fortios import fortios_system_ndproxy

    from terrascript.resource.fortinetdev.fortios import fortios_system_netflow

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_networkvisibility,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_ntp

    from terrascript.resource.fortinetdev.fortios import fortios_system_objecttagging

    from terrascript.resource.fortinetdev.fortios import fortios_system_passwordpolicy

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_passwordpolicyguestadmin,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_pppoeinterface

    from terrascript.resource.fortinetdev.fortios import fortios_system_proberesponse

    from terrascript.resource.fortinetdev.fortios import fortios_system_proxyarp

    from terrascript.resource.fortinetdev.fortios import fortios_system_ptp

    from terrascript.resource.fortinetdev.fortios import fortios_system_replacemsggroup

    from terrascript.resource.fortinetdev.fortios import fortios_system_replacemsgimage

    from terrascript.resource.fortinetdev.fortios import fortios_system_resourcelimits

    from terrascript.resource.fortinetdev.fortios import fortios_system_saml

    from terrascript.resource.fortinetdev.fortios import fortios_system_sdnconnector

    from terrascript.resource.fortinetdev.fortios import fortios_system_sdwan

    from terrascript.resource.fortinetdev.fortios import fortios_system_sessionhelper

    from terrascript.resource.fortinetdev.fortios import fortios_system_sessionttl

    from terrascript.resource.fortinetdev.fortios import fortios_system_setting_dns

    from terrascript.resource.fortinetdev.fortios import fortios_system_setting_global

    from terrascript.resource.fortinetdev.fortios import fortios_system_setting_ntp

    from terrascript.resource.fortinetdev.fortios import fortios_system_settings

    from terrascript.resource.fortinetdev.fortios import fortios_system_sflow

    from terrascript.resource.fortinetdev.fortios import fortios_system_sittunnel

    from terrascript.resource.fortinetdev.fortios import fortios_system_smsserver

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_speedtestschedule,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_speedtestserver

    from terrascript.resource.fortinetdev.fortios import fortios_system_ssoadmin

    from terrascript.resource.fortinetdev.fortios import (
        fortios_system_standalonecluster,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_system_storage

    from terrascript.resource.fortinetdev.fortios import fortios_system_switchinterface

    from terrascript.resource.fortinetdev.fortios import fortios_system_tosbasedpriority

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdom

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdom_setting

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdomdns

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdomexception

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdomlink

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdomnetflow

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdomproperty

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdomradiusserver

    from terrascript.resource.fortinetdev.fortios import fortios_system_vdomsflow

    from terrascript.resource.fortinetdev.fortios import fortios_system_virtualswitch

    from terrascript.resource.fortinetdev.fortios import fortios_system_virtualwanlink

    from terrascript.resource.fortinetdev.fortios import fortios_system_virtualwirepair

    from terrascript.resource.fortinetdev.fortios import fortios_system_vnetunnel

    from terrascript.resource.fortinetdev.fortios import fortios_system_vxlan

    from terrascript.resource.fortinetdev.fortios import fortios_system_wccp

    from terrascript.resource.fortinetdev.fortios import fortios_system_zone

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemautoupdate_pushupdate,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemautoupdate_schedule,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemautoupdate_tunneling,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemdhcp6_server

    from terrascript.resource.fortinetdev.fortios import fortios_systemdhcp_server

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemlldp_networkpolicy,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_admin

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemreplacemsg_alertmail,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_auth

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemreplacemsg_automation,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemreplacemsg_devicedetectionportal,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_ec

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemreplacemsg_fortiguardwf,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_ftp

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_http

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_icap

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_mail

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemreplacemsg_nacquar,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_nntp

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_spam

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_sslvpn

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemreplacemsg_trafficquota,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemreplacemsg_utm

    from terrascript.resource.fortinetdev.fortios import (
        fortios_systemreplacemsg_webproxy,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_systemsnmp_community

    from terrascript.resource.fortinetdev.fortios import fortios_systemsnmp_sysinfo

    from terrascript.resource.fortinetdev.fortios import fortios_systemsnmp_user

    from terrascript.resource.fortinetdev.fortios import fortios_user_adgrp

    from terrascript.resource.fortinetdev.fortios import fortios_user_device

    from terrascript.resource.fortinetdev.fortios import fortios_user_deviceaccesslist

    from terrascript.resource.fortinetdev.fortios import fortios_user_devicecategory

    from terrascript.resource.fortinetdev.fortios import fortios_user_devicegroup

    from terrascript.resource.fortinetdev.fortios import fortios_user_domaincontroller

    from terrascript.resource.fortinetdev.fortios import fortios_user_exchange

    from terrascript.resource.fortinetdev.fortios import fortios_user_fortitoken

    from terrascript.resource.fortinetdev.fortios import fortios_user_fsso

    from terrascript.resource.fortinetdev.fortios import fortios_user_fssopolling

    from terrascript.resource.fortinetdev.fortios import fortios_user_group

    from terrascript.resource.fortinetdev.fortios import fortios_user_krbkeytab

    from terrascript.resource.fortinetdev.fortios import fortios_user_ldap

    from terrascript.resource.fortinetdev.fortios import fortios_user_local

    from terrascript.resource.fortinetdev.fortios import fortios_user_nacpolicy

    from terrascript.resource.fortinetdev.fortios import fortios_user_passwordpolicy

    from terrascript.resource.fortinetdev.fortios import fortios_user_peer

    from terrascript.resource.fortinetdev.fortios import fortios_user_peergrp

    from terrascript.resource.fortinetdev.fortios import fortios_user_pop3

    from terrascript.resource.fortinetdev.fortios import fortios_user_quarantine

    from terrascript.resource.fortinetdev.fortios import fortios_user_radius

    from terrascript.resource.fortinetdev.fortios import fortios_user_saml

    from terrascript.resource.fortinetdev.fortios import fortios_user_securityexemptlist

    from terrascript.resource.fortinetdev.fortios import fortios_user_setting

    from terrascript.resource.fortinetdev.fortios import fortios_user_tacacs

    from terrascript.resource.fortinetdev.fortios import fortios_voip_profile

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpn_ipsec_phase1interface,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpn_ipsec_phase2interface,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_vpn_l2tp

    from terrascript.resource.fortinetdev.fortios import fortios_vpn_ocvpn

    from terrascript.resource.fortinetdev.fortios import fortios_vpn_pptp

    from terrascript.resource.fortinetdev.fortios import fortios_vpncertificate_ca

    from terrascript.resource.fortinetdev.fortios import fortios_vpncertificate_crl

    from terrascript.resource.fortinetdev.fortios import fortios_vpncertificate_local

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpncertificate_ocspserver,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_vpncertificate_remote

    from terrascript.resource.fortinetdev.fortios import fortios_vpncertificate_setting

    from terrascript.resource.fortinetdev.fortios import fortios_vpnipsec_concentrator

    from terrascript.resource.fortinetdev.fortios import fortios_vpnipsec_forticlient

    from terrascript.resource.fortinetdev.fortios import fortios_vpnipsec_manualkey

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpnipsec_manualkeyinterface,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_vpnipsec_phase1

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpnipsec_phase1interface,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_vpnipsec_phase2

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpnipsec_phase2interface,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_vpnssl_settings

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpnsslweb_hostchecksoftware,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_vpnsslweb_portal

    from terrascript.resource.fortinetdev.fortios import fortios_vpnsslweb_realm

    from terrascript.resource.fortinetdev.fortios import fortios_vpnsslweb_userbookmark

    from terrascript.resource.fortinetdev.fortios import (
        fortios_vpnsslweb_usergroupbookmark,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_waf_mainclass

    from terrascript.resource.fortinetdev.fortios import fortios_waf_profile

    from terrascript.resource.fortinetdev.fortios import fortios_waf_signature

    from terrascript.resource.fortinetdev.fortios import fortios_waf_subclass

    from terrascript.resource.fortinetdev.fortios import fortios_wanopt_authgroup

    from terrascript.resource.fortinetdev.fortios import fortios_wanopt_cacheservice

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wanopt_contentdeliverynetworkrule,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_wanopt_peer

    from terrascript.resource.fortinetdev.fortios import fortios_wanopt_profile

    from terrascript.resource.fortinetdev.fortios import fortios_wanopt_remotestorage

    from terrascript.resource.fortinetdev.fortios import fortios_wanopt_settings

    from terrascript.resource.fortinetdev.fortios import fortios_wanopt_webcache

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_content

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_contentheader

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_fortiguard

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_ftgdlocalcat

    from terrascript.resource.fortinetdev.fortios import (
        fortios_webfilter_ftgdlocalrating,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_webfilter_ipsurlfiltercachesetting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_webfilter_ipsurlfiltersetting,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_webfilter_ipsurlfiltersetting6,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_override

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_profile

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_searchengine

    from terrascript.resource.fortinetdev.fortios import fortios_webfilter_urlfilter

    from terrascript.resource.fortinetdev.fortios import fortios_webproxy_debugurl

    from terrascript.resource.fortinetdev.fortios import fortios_webproxy_explicit

    from terrascript.resource.fortinetdev.fortios import fortios_webproxy_forwardserver

    from terrascript.resource.fortinetdev.fortios import (
        fortios_webproxy_forwardservergroup,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_webproxy_global

    from terrascript.resource.fortinetdev.fortios import fortios_webproxy_profile

    from terrascript.resource.fortinetdev.fortios import fortios_webproxy_urlmatch

    from terrascript.resource.fortinetdev.fortios import fortios_webproxy_wisp

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_accesscontrollist,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_address,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_addrgrp,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_apcfgprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_apstatus,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_arrpprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_bleprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_bonjourprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_global,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_intercontroller,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_wirelesscontroller_log

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_mpskprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_qosprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_region,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_setting,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_wirelesscontroller_snmp

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_timers,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_utmprofile,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_wirelesscontroller_vap

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_vapgroup,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_wagprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_widsprofile,
    )

    from terrascript.resource.fortinetdev.fortios import fortios_wirelesscontroller_wtp

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_wtpgroup,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontroller_wtpprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_anqp3gppcellular,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_anqpipaddresstype,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_anqpnairealm,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_anqpnetworkauthtype,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_anqproamingconsortium,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_anqpvenuename,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_h2qpconncapability,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_h2qpoperatorname,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_h2qposuprovider,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_h2qpwanmetric,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_hsprofile,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_icon,
    )

    from terrascript.resource.fortinetdev.fortios import (
        fortios_wirelesscontrollerhotspot20_qosmap,
    )


def test_datasource_import():
    from terrascript.data.fortinetdev.fortios import fortios_firewall_DoSpolicy

    from terrascript.data.fortinetdev.fortios import fortios_firewall_DoSpolicy6

    from terrascript.data.fortinetdev.fortios import fortios_firewall_DoSpolicy6list

    from terrascript.data.fortinetdev.fortios import fortios_firewall_DoSpolicylist

    from terrascript.data.fortinetdev.fortios import fortios_firewall_address

    from terrascript.data.fortinetdev.fortios import fortios_firewall_address6

    from terrascript.data.fortinetdev.fortios import fortios_firewall_address6list

    from terrascript.data.fortinetdev.fortios import fortios_firewall_address6template

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_address6templatelist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewall_addresslist

    from terrascript.data.fortinetdev.fortios import fortios_firewall_addrgrp

    from terrascript.data.fortinetdev.fortios import fortios_firewall_addrgrp6

    from terrascript.data.fortinetdev.fortios import fortios_firewall_addrgrp6list

    from terrascript.data.fortinetdev.fortios import fortios_firewall_addrgrplist

    from terrascript.data.fortinetdev.fortios import fortios_firewall_centralsnatmap

    from terrascript.data.fortinetdev.fortios import fortios_firewall_centralsnatmaplist

    from terrascript.data.fortinetdev.fortios import fortios_firewall_internetservice

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicecustom,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicecustomgroup,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicecustomgrouplist,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicecustomlist,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicedefinition,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicedefinitionlist,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetserviceextension,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetserviceextensionlist,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicegroup,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicegrouplist,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_internetservicelist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewall_ipv6ehfilter

    from terrascript.data.fortinetdev.fortios import fortios_firewall_multicastaddress

    from terrascript.data.fortinetdev.fortios import fortios_firewall_multicastaddress6

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_multicastaddress6list,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_multicastaddresslist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policy

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policy46

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policy46list

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policy6

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policy64

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policy64list

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policy6list

    from terrascript.data.fortinetdev.fortios import fortios_firewall_policylist

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_profileprotocoloptions,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewall_profileprotocoloptionslist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewall_proxyaddress

    from terrascript.data.fortinetdev.fortios import fortios_firewall_proxyaddresslist

    from terrascript.data.fortinetdev.fortios import fortios_firewall_proxyaddrgrp

    from terrascript.data.fortinetdev.fortios import fortios_firewall_proxyaddrgrplist

    from terrascript.data.fortinetdev.fortios import fortios_firewall_proxypolicy

    from terrascript.data.fortinetdev.fortios import fortios_firewall_proxypolicylist

    from terrascript.data.fortinetdev.fortios import fortios_firewallconsolidated_policy

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallconsolidated_policylist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewallschedule_group

    from terrascript.data.fortinetdev.fortios import fortios_firewallschedule_grouplist

    from terrascript.data.fortinetdev.fortios import fortios_firewallschedule_onetime

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallschedule_onetimelist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewallschedule_recurring

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallschedule_recurringlist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewallservice_category

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallservice_categorylist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewallservice_custom

    from terrascript.data.fortinetdev.fortios import fortios_firewallservice_customlist

    from terrascript.data.fortinetdev.fortios import fortios_firewallservice_group

    from terrascript.data.fortinetdev.fortios import fortios_firewallservice_grouplist

    from terrascript.data.fortinetdev.fortios import fortios_firewallshaper_peripshaper

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallshaper_peripshaperlist,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallshaper_trafficshaper,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallshaper_trafficshaperlist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewallwildcardfqdn_custom

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallwildcardfqdn_customlist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_firewallwildcardfqdn_group

    from terrascript.data.fortinetdev.fortios import (
        fortios_firewallwildcardfqdn_grouplist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_ipmask_cidr

    from terrascript.data.fortinetdev.fortios import fortios_json_generic_api

    from terrascript.data.fortinetdev.fortios import fortios_router_accesslist

    from terrascript.data.fortinetdev.fortios import fortios_router_accesslist6

    from terrascript.data.fortinetdev.fortios import fortios_router_accesslist6list

    from terrascript.data.fortinetdev.fortios import fortios_router_accesslistlist

    from terrascript.data.fortinetdev.fortios import fortios_router_aspathlist

    from terrascript.data.fortinetdev.fortios import fortios_router_aspathlistlist

    from terrascript.data.fortinetdev.fortios import fortios_router_authpath

    from terrascript.data.fortinetdev.fortios import fortios_router_authpathlist

    from terrascript.data.fortinetdev.fortios import fortios_router_bfd

    from terrascript.data.fortinetdev.fortios import fortios_router_bfd6

    from terrascript.data.fortinetdev.fortios import fortios_router_bgp

    from terrascript.data.fortinetdev.fortios import fortios_router_communitylist

    from terrascript.data.fortinetdev.fortios import fortios_router_communitylistlist

    from terrascript.data.fortinetdev.fortios import fortios_router_isis

    from terrascript.data.fortinetdev.fortios import fortios_router_keychain

    from terrascript.data.fortinetdev.fortios import fortios_router_keychainlist

    from terrascript.data.fortinetdev.fortios import fortios_router_multicast

    from terrascript.data.fortinetdev.fortios import fortios_router_multicast6

    from terrascript.data.fortinetdev.fortios import fortios_router_multicastflow

    from terrascript.data.fortinetdev.fortios import fortios_router_multicastflowlist

    from terrascript.data.fortinetdev.fortios import fortios_router_ospf

    from terrascript.data.fortinetdev.fortios import fortios_router_ospf6

    from terrascript.data.fortinetdev.fortios import fortios_router_policy

    from terrascript.data.fortinetdev.fortios import fortios_router_policy6

    from terrascript.data.fortinetdev.fortios import fortios_router_policy6list

    from terrascript.data.fortinetdev.fortios import fortios_router_policylist

    from terrascript.data.fortinetdev.fortios import fortios_router_prefixlist

    from terrascript.data.fortinetdev.fortios import fortios_router_prefixlist6

    from terrascript.data.fortinetdev.fortios import fortios_router_prefixlist6list

    from terrascript.data.fortinetdev.fortios import fortios_router_prefixlistlist

    from terrascript.data.fortinetdev.fortios import fortios_router_rip

    from terrascript.data.fortinetdev.fortios import fortios_router_ripng

    from terrascript.data.fortinetdev.fortios import fortios_router_routemap

    from terrascript.data.fortinetdev.fortios import fortios_router_routemaplist

    from terrascript.data.fortinetdev.fortios import fortios_router_setting

    from terrascript.data.fortinetdev.fortios import fortios_router_static

    from terrascript.data.fortinetdev.fortios import fortios_router_static6

    from terrascript.data.fortinetdev.fortios import fortios_router_static6list

    from terrascript.data.fortinetdev.fortios import fortios_router_staticlist

    from terrascript.data.fortinetdev.fortios import fortios_routerbgp_neighbor

    from terrascript.data.fortinetdev.fortios import fortios_routerbgp_neighborlist

    from terrascript.data.fortinetdev.fortios import fortios_system_accprofile

    from terrascript.data.fortinetdev.fortios import fortios_system_accprofilelist

    from terrascript.data.fortinetdev.fortios import fortios_system_admin

    from terrascript.data.fortinetdev.fortios import fortios_system_adminlist

    from terrascript.data.fortinetdev.fortios import fortios_system_alias

    from terrascript.data.fortinetdev.fortios import fortios_system_aliaslist

    from terrascript.data.fortinetdev.fortios import fortios_system_apiuser

    from terrascript.data.fortinetdev.fortios import fortios_system_apiuserlist

    from terrascript.data.fortinetdev.fortios import fortios_system_arptable

    from terrascript.data.fortinetdev.fortios import fortios_system_arptablelist

    from terrascript.data.fortinetdev.fortios import fortios_system_autoinstall

    from terrascript.data.fortinetdev.fortios import fortios_system_automationaction

    from terrascript.data.fortinetdev.fortios import fortios_system_automationactionlist

    from terrascript.data.fortinetdev.fortios import (
        fortios_system_automationdestination,
    )

    from terrascript.data.fortinetdev.fortios import (
        fortios_system_automationdestinationlist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_system_automationtrigger

    from terrascript.data.fortinetdev.fortios import (
        fortios_system_automationtriggerlist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_system_autoscript

    from terrascript.data.fortinetdev.fortios import fortios_system_autoscriptlist

    from terrascript.data.fortinetdev.fortios import fortios_system_centralmanagement

    from terrascript.data.fortinetdev.fortios import fortios_system_clustersync

    from terrascript.data.fortinetdev.fortios import fortios_system_clustersynclist

    from terrascript.data.fortinetdev.fortios import fortios_system_console

    from terrascript.data.fortinetdev.fortios import fortios_system_csf

    from terrascript.data.fortinetdev.fortios import fortios_system_ddns

    from terrascript.data.fortinetdev.fortios import fortios_system_ddnslist

    from terrascript.data.fortinetdev.fortios import fortios_system_dns

    from terrascript.data.fortinetdev.fortios import fortios_system_dnsdatabase

    from terrascript.data.fortinetdev.fortios import fortios_system_dnsdatabaselist

    from terrascript.data.fortinetdev.fortios import fortios_system_dnsserver

    from terrascript.data.fortinetdev.fortios import fortios_system_dnsserverlist

    from terrascript.data.fortinetdev.fortios import fortios_system_dscpbasedpriority

    from terrascript.data.fortinetdev.fortios import (
        fortios_system_dscpbasedprioritylist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_system_emailserver

    from terrascript.data.fortinetdev.fortios import fortios_system_externalresource

    from terrascript.data.fortinetdev.fortios import fortios_system_externalresourcelist

    from terrascript.data.fortinetdev.fortios import fortios_system_fipscc

    from terrascript.data.fortinetdev.fortios import fortios_system_fm

    from terrascript.data.fortinetdev.fortios import fortios_system_fortiguard

    from terrascript.data.fortinetdev.fortios import fortios_system_fortimanager

    from terrascript.data.fortinetdev.fortios import fortios_system_fortisandbox

    from terrascript.data.fortinetdev.fortios import fortios_system_fssopolling

    from terrascript.data.fortinetdev.fortios import fortios_system_ftmpush

    from terrascript.data.fortinetdev.fortios import fortios_system_global

    from terrascript.data.fortinetdev.fortios import fortios_system_gretunnel

    from terrascript.data.fortinetdev.fortios import fortios_system_gretunnellist

    from terrascript.data.fortinetdev.fortios import fortios_system_ha

    from terrascript.data.fortinetdev.fortios import fortios_system_hamonitor

    from terrascript.data.fortinetdev.fortios import fortios_system_interface

    from terrascript.data.fortinetdev.fortios import fortios_system_interfacelist

    from terrascript.data.fortinetdev.fortios import fortios_system_ipiptunnel

    from terrascript.data.fortinetdev.fortios import fortios_system_ipiptunnellist

    from terrascript.data.fortinetdev.fortios import fortios_system_ipv6neighborcache

    from terrascript.data.fortinetdev.fortios import (
        fortios_system_ipv6neighborcachelist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_system_ipv6tunnel

    from terrascript.data.fortinetdev.fortios import fortios_system_ipv6tunnellist

    from terrascript.data.fortinetdev.fortios import fortios_system_linkmonitor

    from terrascript.data.fortinetdev.fortios import fortios_system_linkmonitorlist

    from terrascript.data.fortinetdev.fortios import fortios_system_managementtunnel

    from terrascript.data.fortinetdev.fortios import fortios_system_mobiletunnel

    from terrascript.data.fortinetdev.fortios import fortios_system_mobiletunnellist

    from terrascript.data.fortinetdev.fortios import fortios_system_nat64

    from terrascript.data.fortinetdev.fortios import fortios_system_ndproxy

    from terrascript.data.fortinetdev.fortios import fortios_system_netflow

    from terrascript.data.fortinetdev.fortios import fortios_system_networkvisibility

    from terrascript.data.fortinetdev.fortios import fortios_system_ntp

    from terrascript.data.fortinetdev.fortios import fortios_system_objecttagging

    from terrascript.data.fortinetdev.fortios import fortios_system_objecttagginglist

    from terrascript.data.fortinetdev.fortios import fortios_system_passwordpolicy

    from terrascript.data.fortinetdev.fortios import (
        fortios_system_passwordpolicyguestadmin,
    )

    from terrascript.data.fortinetdev.fortios import fortios_system_pppoeinterface

    from terrascript.data.fortinetdev.fortios import fortios_system_pppoeinterfacelist

    from terrascript.data.fortinetdev.fortios import fortios_system_proberesponse

    from terrascript.data.fortinetdev.fortios import fortios_system_proxyarp

    from terrascript.data.fortinetdev.fortios import fortios_system_proxyarplist

    from terrascript.data.fortinetdev.fortios import fortios_system_replacemsggroup

    from terrascript.data.fortinetdev.fortios import fortios_system_replacemsggrouplist

    from terrascript.data.fortinetdev.fortios import fortios_system_replacemsgimage

    from terrascript.data.fortinetdev.fortios import fortios_system_replacemsgimagelist

    from terrascript.data.fortinetdev.fortios import fortios_system_resourcelimits

    from terrascript.data.fortinetdev.fortios import fortios_system_sdnconnector

    from terrascript.data.fortinetdev.fortios import fortios_system_sdnconnectorlist

    from terrascript.data.fortinetdev.fortios import fortios_system_sessionhelper

    from terrascript.data.fortinetdev.fortios import fortios_system_sessionhelperlist

    from terrascript.data.fortinetdev.fortios import fortios_system_sessionttl

    from terrascript.data.fortinetdev.fortios import fortios_system_sflow

    from terrascript.data.fortinetdev.fortios import fortios_system_sittunnel

    from terrascript.data.fortinetdev.fortios import fortios_system_sittunnellist

    from terrascript.data.fortinetdev.fortios import fortios_system_smsserver

    from terrascript.data.fortinetdev.fortios import fortios_system_smsserverlist

    from terrascript.data.fortinetdev.fortios import fortios_system_tosbasedpriority

    from terrascript.data.fortinetdev.fortios import fortios_system_tosbasedprioritylist

    from terrascript.data.fortinetdev.fortios import fortios_system_vdomexception

    from terrascript.data.fortinetdev.fortios import fortios_system_vdomexceptionlist

    from terrascript.data.fortinetdev.fortios import fortios_system_vdomnetflow

    from terrascript.data.fortinetdev.fortios import fortios_system_vdomsflow

    from terrascript.data.fortinetdev.fortios import fortios_system_virtualwanlink

    from terrascript.data.fortinetdev.fortios import fortios_system_vxlan

    from terrascript.data.fortinetdev.fortios import fortios_system_vxlanlist

    from terrascript.data.fortinetdev.fortios import fortios_system_wccp

    from terrascript.data.fortinetdev.fortios import fortios_system_wccplist

    from terrascript.data.fortinetdev.fortios import fortios_system_zone

    from terrascript.data.fortinetdev.fortios import fortios_system_zonelist

    from terrascript.data.fortinetdev.fortios import fortios_systemautoupdate_pushupdate

    from terrascript.data.fortinetdev.fortios import fortios_systemautoupdate_schedule

    from terrascript.data.fortinetdev.fortios import fortios_systemautoupdate_tunneling

    from terrascript.data.fortinetdev.fortios import fortios_systemdhcp_server

    from terrascript.data.fortinetdev.fortios import fortios_systemdhcp_serverlist

    from terrascript.data.fortinetdev.fortios import fortios_systemlldp_networkpolicy

    from terrascript.data.fortinetdev.fortios import (
        fortios_systemlldp_networkpolicylist,
    )

    from terrascript.data.fortinetdev.fortios import fortios_systemsnmp_community

    from terrascript.data.fortinetdev.fortios import fortios_systemsnmp_communitylist

    from terrascript.data.fortinetdev.fortios import fortios_systemsnmp_sysinfo

    from terrascript.data.fortinetdev.fortios import fortios_systemsnmp_user

    from terrascript.data.fortinetdev.fortios import fortios_systemsnmp_userlist

    from terrascript.data.fortinetdev.fortios import fortios_user_saml

    from terrascript.data.fortinetdev.fortios import fortios_user_samllist


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.fortinetdev.fortios
#
#      t = terrascript.provider.fortinetdev.fortios.fortios()
#      s = str(t)
#
#      assert 'https://github.com/fortinetdev/terraform-provider-fortios' in s
#      assert '1.13.1' in s
