#tests/test_provider_hashicorp_time.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:20 UTC)

def test_provider_import():
    import terrascript.provider.hashicorp.time


def test_resource_import():
    from terrascript.resource.hashicorp.time import time_offset

    from terrascript.resource.hashicorp.time import time_rotating

    from terrascript.resource.hashicorp.time import time_sleep

    from terrascript.resource.hashicorp.time import time_static





# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.hashicorp.time
#      
#      t = terrascript.provider.hashicorp.time.time()
#      s = str(t)
#      
#      assert 'https://github.com/hashicorp/terraform-provider-time' in s
#      assert '0.7.2' in s
