#tests/test_provider_jeremmfr_lvslb.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:15 UTC)

def test_provider_import():
    import terrascript.provider.jeremmfr.lvslb


def test_resource_import():
    from terrascript.resource.jeremmfr.lvslb import lvslb_ipvs





# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.jeremmfr.lvslb
#      
#      t = terrascript.provider.jeremmfr.lvslb.lvslb()
#      s = str(t)
#      
#      assert 'https://github.com/jeremmfr/terraform-provider-lvslb' in s
#      assert '1.1.0' in s
