#tests/test_provider_cloudsmith-io_cloudsmith.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:12 UTC)

def test_provider_import():
    import terrascript.provider.cloudsmith_io.cloudsmith


def test_resource_import():
    from terrascript.resource.cloudsmith_io.cloudsmith import cloudsmith_entitlement

    from terrascript.resource.cloudsmith_io.cloudsmith import cloudsmith_repository




def test_datasource_import():
    from terrascript.data.cloudsmith_io.cloudsmith import cloudsmith_namespace

    from terrascript.data.cloudsmith_io.cloudsmith import cloudsmith_package_list

    from terrascript.data.cloudsmith_io.cloudsmith import cloudsmith_repository



# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.cloudsmith_io.cloudsmith
#      
#      t = terrascript.provider.cloudsmith_io.cloudsmith.cloudsmith()
#      s = str(t)
#      
#      assert 'https://github.com/cloudsmith-io/terraform-provider-cloudsmith' in s
#      assert '0.0.6' in s
