# tests/test_provider_jb-abbadie_errorcheck.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:15:52 UTC)


def test_provider_import():
    import terrascript.provider.jb_abbadie.errorcheck


def test_resource_import():
    from terrascript.resource.jb_abbadie.errorcheck import errorcheck_is_valid


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.jb_abbadie.errorcheck
#
#      t = terrascript.provider.jb_abbadie.errorcheck.errorcheck()
#      s = str(t)
#
#      assert 'https://github.com/jb-abbadie/terraform-provider-errorcheck' in s
#      assert '2.0.4' in s
