# tests/test_provider_joerx_cheesecake.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:47 UTC)


def test_provider_import():
    import terrascript.provider.joerx.cheesecake


def test_datasource_import():
    from terrascript.data.joerx.cheesecake import cheesecake_cheesecakes


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.joerx.cheesecake
#
#      t = terrascript.provider.joerx.cheesecake.cheesecake()
#      s = str(t)
#
#      assert 'https://github.com/joerx/terraform-provider-cheesecake' in s
#      assert '0.2.3' in s
