# tests/test_provider_hashicorp_github.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:17:03 UTC)


def test_provider_import():
    import terrascript.provider.hashicorp.github


def test_resource_import():
    from terrascript.resource.hashicorp.github import github_actions_environment_secret

    from terrascript.resource.hashicorp.github import github_actions_organization_secret

    from terrascript.resource.hashicorp.github import (
        github_actions_organization_secret_repositories,
    )

    from terrascript.resource.hashicorp.github import github_actions_runner_group

    from terrascript.resource.hashicorp.github import github_actions_secret

    from terrascript.resource.hashicorp.github import github_app_installation_repository

    from terrascript.resource.hashicorp.github import github_branch

    from terrascript.resource.hashicorp.github import github_branch_default

    from terrascript.resource.hashicorp.github import github_branch_protection

    from terrascript.resource.hashicorp.github import github_branch_protection_v3

    from terrascript.resource.hashicorp.github import github_issue_label

    from terrascript.resource.hashicorp.github import github_membership

    from terrascript.resource.hashicorp.github import github_organization_block

    from terrascript.resource.hashicorp.github import github_organization_project

    from terrascript.resource.hashicorp.github import github_organization_webhook

    from terrascript.resource.hashicorp.github import github_project_card

    from terrascript.resource.hashicorp.github import github_project_column

    from terrascript.resource.hashicorp.github import github_repository

    from terrascript.resource.hashicorp.github import github_repository_collaborator

    from terrascript.resource.hashicorp.github import github_repository_deploy_key

    from terrascript.resource.hashicorp.github import github_repository_environment

    from terrascript.resource.hashicorp.github import github_repository_file

    from terrascript.resource.hashicorp.github import github_repository_milestone

    from terrascript.resource.hashicorp.github import github_repository_project

    from terrascript.resource.hashicorp.github import github_repository_pull_request

    from terrascript.resource.hashicorp.github import github_repository_webhook

    from terrascript.resource.hashicorp.github import github_team

    from terrascript.resource.hashicorp.github import github_team_membership

    from terrascript.resource.hashicorp.github import github_team_repository

    from terrascript.resource.hashicorp.github import github_team_sync_group_mapping

    from terrascript.resource.hashicorp.github import github_user_gpg_key

    from terrascript.resource.hashicorp.github import github_user_invitation_accepter

    from terrascript.resource.hashicorp.github import github_user_ssh_key


def test_datasource_import():
    from terrascript.data.hashicorp.github import github_actions_public_key

    from terrascript.data.hashicorp.github import github_branch

    from terrascript.data.hashicorp.github import github_collaborators

    from terrascript.data.hashicorp.github import github_ip_ranges

    from terrascript.data.hashicorp.github import github_membership

    from terrascript.data.hashicorp.github import github_organization

    from terrascript.data.hashicorp.github import github_organization_team_sync_groups

    from terrascript.data.hashicorp.github import github_organization_teams

    from terrascript.data.hashicorp.github import github_release

    from terrascript.data.hashicorp.github import github_repositories

    from terrascript.data.hashicorp.github import github_repository

    from terrascript.data.hashicorp.github import github_repository_milestone

    from terrascript.data.hashicorp.github import github_repository_pull_request

    from terrascript.data.hashicorp.github import github_repository_pull_requests

    from terrascript.data.hashicorp.github import github_team

    from terrascript.data.hashicorp.github import github_user


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.hashicorp.github
#
#      t = terrascript.provider.hashicorp.github.github()
#      s = str(t)
#
#      assert 'https://github.com/hashicorp/terraform-provider-github' in s
#      assert '4.15.1' in s
