# tests/test_provider_Mongey_hellosign.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:22 UTC)


def test_provider_import():
    import terrascript.provider.Mongey.hellosign


def test_resource_import():
    from terrascript.resource.Mongey.hellosign import hellosign_api_app


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.Mongey.hellosign
#
#      t = terrascript.provider.Mongey.hellosign.hellosign()
#      s = str(t)
#
#      assert 'https://github.com/Mongey/terraform-provider-hellosign' in s
#      assert '0.0.2' in s
