#tests/test_provider_unicell_kind.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:06 UTC)

def test_provider_import():
    import terrascript.provider.unicell.kind


def test_resource_import():
    from terrascript.resource.unicell.kind import kind_cluster





# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.unicell.kind
#      
#      t = terrascript.provider.unicell.kind.kind()
#      s = str(t)
#      
#      assert 'https://github.com/unicell/terraform-provider-kind' in s
#      assert '0.0.2-u2' in s
