#tests/test_provider_brightbox_brightbox.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:07 UTC)

def test_provider_import():
    import terrascript.provider.brightbox.brightbox


def test_resource_import():
    from terrascript.resource.brightbox.brightbox import brightbox_api_client

    from terrascript.resource.brightbox.brightbox import brightbox_cloudip

    from terrascript.resource.brightbox.brightbox import brightbox_config_map

    from terrascript.resource.brightbox.brightbox import brightbox_database_server

    from terrascript.resource.brightbox.brightbox import brightbox_firewall_policy

    from terrascript.resource.brightbox.brightbox import brightbox_firewall_rule

    from terrascript.resource.brightbox.brightbox import brightbox_load_balancer

    from terrascript.resource.brightbox.brightbox import brightbox_orbit_container

    from terrascript.resource.brightbox.brightbox import brightbox_server

    from terrascript.resource.brightbox.brightbox import brightbox_server_group




def test_datasource_import():
    from terrascript.data.brightbox.brightbox import brightbox_database_type

    from terrascript.data.brightbox.brightbox import brightbox_image

    from terrascript.data.brightbox.brightbox import brightbox_server_group



# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.brightbox.brightbox
#      
#      t = terrascript.provider.brightbox.brightbox.brightbox()
#      s = str(t)
#      
#      assert 'https://github.com/brightbox/terraform-provider-brightbox' in s
#      assert '2.0.6' in s
