# tests/test_provider_phoenixnap_pnap.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:24:49 UTC)


def test_provider_import():
    import terrascript.provider.phoenixnap.pnap


def test_resource_import():
    from terrascript.resource.phoenixnap.pnap import pnap_server

    from terrascript.resource.phoenixnap.pnap import pnap_ssh_key


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.phoenixnap.pnap
#
#      t = terrascript.provider.phoenixnap.pnap.pnap()
#      s = str(t)
#
#      assert 'https://github.com/phoenixnap/terraform-provider-pnap' in s
#      assert '0.8.0' in s
