# tests/test_provider_linode_linode.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:21:10 UTC)


def test_provider_import():
    import terrascript.provider.linode.linode


def test_resource_import():
    from terrascript.resource.linode.linode import linode_domain

    from terrascript.resource.linode.linode import linode_domain_record

    from terrascript.resource.linode.linode import linode_firewall

    from terrascript.resource.linode.linode import linode_image

    from terrascript.resource.linode.linode import linode_instance

    from terrascript.resource.linode.linode import linode_instance_ip

    from terrascript.resource.linode.linode import linode_lke_cluster

    from terrascript.resource.linode.linode import linode_nodebalancer

    from terrascript.resource.linode.linode import linode_nodebalancer_config

    from terrascript.resource.linode.linode import linode_nodebalancer_node

    from terrascript.resource.linode.linode import linode_object_storage_bucket

    from terrascript.resource.linode.linode import linode_object_storage_key

    from terrascript.resource.linode.linode import linode_object_storage_object

    from terrascript.resource.linode.linode import linode_rdns

    from terrascript.resource.linode.linode import linode_sshkey

    from terrascript.resource.linode.linode import linode_stackscript

    from terrascript.resource.linode.linode import linode_token

    from terrascript.resource.linode.linode import linode_user

    from terrascript.resource.linode.linode import linode_volume


def test_datasource_import():
    from terrascript.data.linode.linode import linode_account

    from terrascript.data.linode.linode import linode_domain

    from terrascript.data.linode.linode import linode_domain_record

    from terrascript.data.linode.linode import linode_firewall

    from terrascript.data.linode.linode import linode_image

    from terrascript.data.linode.linode import linode_images

    from terrascript.data.linode.linode import linode_instance_backups

    from terrascript.data.linode.linode import linode_instance_type

    from terrascript.data.linode.linode import linode_instances

    from terrascript.data.linode.linode import linode_kernel

    from terrascript.data.linode.linode import linode_lke_cluster

    from terrascript.data.linode.linode import linode_networking_ip

    from terrascript.data.linode.linode import linode_nodebalancer

    from terrascript.data.linode.linode import linode_nodebalancer_config

    from terrascript.data.linode.linode import linode_nodebalancer_node

    from terrascript.data.linode.linode import linode_object_storage_cluster

    from terrascript.data.linode.linode import linode_profile

    from terrascript.data.linode.linode import linode_region

    from terrascript.data.linode.linode import linode_sshkey

    from terrascript.data.linode.linode import linode_stackscript

    from terrascript.data.linode.linode import linode_user

    from terrascript.data.linode.linode import linode_vlans

    from terrascript.data.linode.linode import linode_volume


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.linode.linode
#
#      t = terrascript.provider.linode.linode.linode()
#      s = str(t)
#
#      assert 'https://github.com/linode/terraform-provider-linode' in s
#      assert '1.21.0' in s
