# tests/test_provider_invidian_stdlib.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:27:59 UTC)


def test_provider_import():
    import terrascript.provider.invidian.stdlib


def test_datasource_import():
    from terrascript.data.invidian.stdlib import stdlib_base64decodehash


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.invidian.stdlib
#
#      t = terrascript.provider.invidian.stdlib.stdlib()
#      s = str(t)
#
#      assert 'https://github.com/invidian/terraform-provider-stdlib' in s
#      assert '0.1.1' in s
