#tests/test_provider_jeffwecan_teamcity.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:17 UTC)

def test_provider_import():
    import terrascript.provider.jeffwecan.teamcity


def test_resource_import():
    from terrascript.resource.jeffwecan.teamcity import teamcity_agent_pool

    from terrascript.resource.jeffwecan.teamcity import teamcity_agent_pool_project_assignment

    from terrascript.resource.jeffwecan.teamcity import teamcity_agent_requirement

    from terrascript.resource.jeffwecan.teamcity import teamcity_artifact_dependency

    from terrascript.resource.jeffwecan.teamcity import teamcity_build_config

    from terrascript.resource.jeffwecan.teamcity import teamcity_build_trigger_build_finish

    from terrascript.resource.jeffwecan.teamcity import teamcity_build_trigger_schedule

    from terrascript.resource.jeffwecan.teamcity import teamcity_build_trigger_vcs

    from terrascript.resource.jeffwecan.teamcity import teamcity_feature_commit_status_publisher

    from terrascript.resource.jeffwecan.teamcity import teamcity_feature_golang

    from terrascript.resource.jeffwecan.teamcity import teamcity_group

    from terrascript.resource.jeffwecan.teamcity import teamcity_project

    from terrascript.resource.jeffwecan.teamcity import teamcity_project_feature_oauth_provider_settings

    from terrascript.resource.jeffwecan.teamcity import teamcity_project_feature_versioned_settings

    from terrascript.resource.jeffwecan.teamcity import teamcity_snapshot_dependency

    from terrascript.resource.jeffwecan.teamcity import teamcity_vcs_root_git




def test_datasource_import():
    from terrascript.data.jeffwecan.teamcity import teamcity_agent_pool

    from terrascript.data.jeffwecan.teamcity import teamcity_project



# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.jeffwecan.teamcity
#      
#      t = terrascript.provider.jeffwecan.teamcity.teamcity()
#      s = str(t)
#      
#      assert 'https://github.com/jeffwecan/terraform-provider-teamcity' in s
#      assert '1.0.1-jeffwecan-fork' in s
