#tests/test_provider_hashicorp_template.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:17 UTC)

def test_provider_import():
    import terrascript.provider.hashicorp.template


def test_resource_import():
    from terrascript.resource.hashicorp.template import template_cloudinit_config

    from terrascript.resource.hashicorp.template import template_dir

    from terrascript.resource.hashicorp.template import template_file




def test_datasource_import():
    from terrascript.data.hashicorp.template import template_cloudinit_config

    from terrascript.data.hashicorp.template import template_file



# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.hashicorp.template
#      
#      t = terrascript.provider.hashicorp.template.template()
#      s = str(t)
#      
#      assert 'https://github.com/hashicorp/terraform-provider-template' in s
#      assert '2.2.0' in s
