#tests/test_provider_hashicorp_vault.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:31 UTC)

def test_provider_import():
    import terrascript.provider.hashicorp.vault


def test_resource_import():
    from terrascript.resource.hashicorp.vault import vault_ad_secret_backend

    from terrascript.resource.hashicorp.vault import vault_ad_secret_library

    from terrascript.resource.hashicorp.vault import vault_ad_secret_role

    from terrascript.resource.hashicorp.vault import vault_alicloud_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_approle_auth_backend_login

    from terrascript.resource.hashicorp.vault import vault_approle_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_approle_auth_backend_role_secret_id

    from terrascript.resource.hashicorp.vault import vault_audit

    from terrascript.resource.hashicorp.vault import vault_auth_backend

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_cert

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_client

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_identity_whitelist

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_login

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_role_tag

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_roletag_blacklist

    from terrascript.resource.hashicorp.vault import vault_aws_auth_backend_sts_role

    from terrascript.resource.hashicorp.vault import vault_aws_secret_backend

    from terrascript.resource.hashicorp.vault import vault_aws_secret_backend_role

    from terrascript.resource.hashicorp.vault import vault_azure_auth_backend_config

    from terrascript.resource.hashicorp.vault import vault_azure_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_azure_secret_backend

    from terrascript.resource.hashicorp.vault import vault_azure_secret_backend_role

    from terrascript.resource.hashicorp.vault import vault_cert_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_consul_secret_backend

    from terrascript.resource.hashicorp.vault import vault_consul_secret_backend_role

    from terrascript.resource.hashicorp.vault import vault_database_secret_backend_connection

    from terrascript.resource.hashicorp.vault import vault_database_secret_backend_role

    from terrascript.resource.hashicorp.vault import vault_database_secret_backend_static_role

    from terrascript.resource.hashicorp.vault import vault_egp_policy

    from terrascript.resource.hashicorp.vault import vault_gcp_auth_backend

    from terrascript.resource.hashicorp.vault import vault_gcp_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_gcp_secret_backend

    from terrascript.resource.hashicorp.vault import vault_gcp_secret_roleset

    from terrascript.resource.hashicorp.vault import vault_gcp_secret_static_account

    from terrascript.resource.hashicorp.vault import vault_generic_endpoint

    from terrascript.resource.hashicorp.vault import vault_generic_secret

    from terrascript.resource.hashicorp.vault import vault_github_auth_backend

    from terrascript.resource.hashicorp.vault import vault_github_team

    from terrascript.resource.hashicorp.vault import vault_github_user

    from terrascript.resource.hashicorp.vault import vault_identity_entity

    from terrascript.resource.hashicorp.vault import vault_identity_entity_alias

    from terrascript.resource.hashicorp.vault import vault_identity_entity_policies

    from terrascript.resource.hashicorp.vault import vault_identity_group

    from terrascript.resource.hashicorp.vault import vault_identity_group_alias

    from terrascript.resource.hashicorp.vault import vault_identity_group_member_entity_ids

    from terrascript.resource.hashicorp.vault import vault_identity_group_policies

    from terrascript.resource.hashicorp.vault import vault_identity_oidc

    from terrascript.resource.hashicorp.vault import vault_identity_oidc_key

    from terrascript.resource.hashicorp.vault import vault_identity_oidc_key_allowed_client_id

    from terrascript.resource.hashicorp.vault import vault_identity_oidc_role

    from terrascript.resource.hashicorp.vault import vault_jwt_auth_backend

    from terrascript.resource.hashicorp.vault import vault_jwt_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_kubernetes_auth_backend_config

    from terrascript.resource.hashicorp.vault import vault_kubernetes_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_ldap_auth_backend

    from terrascript.resource.hashicorp.vault import vault_ldap_auth_backend_group

    from terrascript.resource.hashicorp.vault import vault_ldap_auth_backend_user

    from terrascript.resource.hashicorp.vault import vault_mfa_duo

    from terrascript.resource.hashicorp.vault import vault_mount

    from terrascript.resource.hashicorp.vault import vault_namespace

    from terrascript.resource.hashicorp.vault import vault_nomad_secret_backend

    from terrascript.resource.hashicorp.vault import vault_nomad_secret_role

    from terrascript.resource.hashicorp.vault import vault_okta_auth_backend

    from terrascript.resource.hashicorp.vault import vault_okta_auth_backend_group

    from terrascript.resource.hashicorp.vault import vault_okta_auth_backend_user

    from terrascript.resource.hashicorp.vault import vault_password_policy

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_cert

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_config_ca

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_config_urls

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_crl_config

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_intermediate_cert_request

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_intermediate_set_signed

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_role

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_root_cert

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_root_sign_intermediate

    from terrascript.resource.hashicorp.vault import vault_pki_secret_backend_sign

    from terrascript.resource.hashicorp.vault import vault_policy

    from terrascript.resource.hashicorp.vault import vault_quota_lease_count

    from terrascript.resource.hashicorp.vault import vault_quota_rate_limit

    from terrascript.resource.hashicorp.vault import vault_rabbitmq_secret_backend

    from terrascript.resource.hashicorp.vault import vault_rabbitmq_secret_backend_role

    from terrascript.resource.hashicorp.vault import vault_rgp_policy

    from terrascript.resource.hashicorp.vault import vault_ssh_secret_backend_ca

    from terrascript.resource.hashicorp.vault import vault_ssh_secret_backend_role

    from terrascript.resource.hashicorp.vault import vault_terraform_cloud_secret_backend

    from terrascript.resource.hashicorp.vault import vault_terraform_cloud_secret_creds

    from terrascript.resource.hashicorp.vault import vault_terraform_cloud_secret_role

    from terrascript.resource.hashicorp.vault import vault_token

    from terrascript.resource.hashicorp.vault import vault_token_auth_backend_role

    from terrascript.resource.hashicorp.vault import vault_transform_alphabet

    from terrascript.resource.hashicorp.vault import vault_transform_role

    from terrascript.resource.hashicorp.vault import vault_transform_template

    from terrascript.resource.hashicorp.vault import vault_transform_transformation

    from terrascript.resource.hashicorp.vault import vault_transit_secret_backend_key

    from terrascript.resource.hashicorp.vault import vault_transit_secret_cache_config




def test_datasource_import():
    from terrascript.data.hashicorp.vault import vault_ad_access_credentials

    from terrascript.data.hashicorp.vault import vault_approle_auth_backend_role_id

    from terrascript.data.hashicorp.vault import vault_auth_backend

    from terrascript.data.hashicorp.vault import vault_aws_access_credentials

    from terrascript.data.hashicorp.vault import vault_azure_access_credentials

    from terrascript.data.hashicorp.vault import vault_gcp_auth_backend_role

    from terrascript.data.hashicorp.vault import vault_generic_secret

    from terrascript.data.hashicorp.vault import vault_identity_entity

    from terrascript.data.hashicorp.vault import vault_identity_group

    from terrascript.data.hashicorp.vault import vault_kubernetes_auth_backend_config

    from terrascript.data.hashicorp.vault import vault_kubernetes_auth_backend_role

    from terrascript.data.hashicorp.vault import vault_nomad_access_token

    from terrascript.data.hashicorp.vault import vault_policy_document

    from terrascript.data.hashicorp.vault import vault_transform_decode

    from terrascript.data.hashicorp.vault import vault_transform_encode

    from terrascript.data.hashicorp.vault import vault_transit_decrypt

    from terrascript.data.hashicorp.vault import vault_transit_encrypt



# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#     
#      import terrascript.provider.hashicorp.vault
#      
#      t = terrascript.provider.hashicorp.vault.vault()
#      s = str(t)
#      
#      assert 'https://github.com/hashicorp/terraform-provider-vault' in s
#      assert '2.23.0' in s
