# tests/test_provider_scaleway_scaleway.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:22 UTC)


def test_provider_import():
    import terrascript.provider.scaleway.scaleway


def test_resource_import():
    from terrascript.resource.scaleway.scaleway import scaleway_account_ssh_key

    from terrascript.resource.scaleway.scaleway import scaleway_apple_silicon_server

    from terrascript.resource.scaleway.scaleway import scaleway_baremetal_server

    from terrascript.resource.scaleway.scaleway import scaleway_instance_ip

    from terrascript.resource.scaleway.scaleway import scaleway_instance_ip_reverse_dns

    from terrascript.resource.scaleway.scaleway import scaleway_instance_placement_group

    from terrascript.resource.scaleway.scaleway import scaleway_instance_private_nic

    from terrascript.resource.scaleway.scaleway import scaleway_instance_security_group

    from terrascript.resource.scaleway.scaleway import (
        scaleway_instance_security_group_rules,
    )

    from terrascript.resource.scaleway.scaleway import scaleway_instance_server

    from terrascript.resource.scaleway.scaleway import scaleway_instance_snapshot

    from terrascript.resource.scaleway.scaleway import scaleway_instance_volume

    from terrascript.resource.scaleway.scaleway import scaleway_iot_device

    from terrascript.resource.scaleway.scaleway import scaleway_iot_hub

    from terrascript.resource.scaleway.scaleway import scaleway_iot_network

    from terrascript.resource.scaleway.scaleway import scaleway_iot_route

    from terrascript.resource.scaleway.scaleway import scaleway_k8s_cluster

    from terrascript.resource.scaleway.scaleway import scaleway_k8s_pool

    from terrascript.resource.scaleway.scaleway import scaleway_lb

    from terrascript.resource.scaleway.scaleway import scaleway_lb_backend

    from terrascript.resource.scaleway.scaleway import scaleway_lb_certificate

    from terrascript.resource.scaleway.scaleway import scaleway_lb_frontend

    from terrascript.resource.scaleway.scaleway import scaleway_lb_ip

    from terrascript.resource.scaleway.scaleway import scaleway_object_bucket

    from terrascript.resource.scaleway.scaleway import scaleway_rdb_acl

    from terrascript.resource.scaleway.scaleway import scaleway_rdb_database

    from terrascript.resource.scaleway.scaleway import scaleway_rdb_instance

    from terrascript.resource.scaleway.scaleway import scaleway_rdb_user

    from terrascript.resource.scaleway.scaleway import scaleway_registry_namespace

    from terrascript.resource.scaleway.scaleway import scaleway_vpc_private_network


def test_datasource_import():
    from terrascript.data.scaleway.scaleway import scaleway_account_ssh_key

    from terrascript.data.scaleway.scaleway import scaleway_baremetal_offer

    from terrascript.data.scaleway.scaleway import scaleway_instance_image

    from terrascript.data.scaleway.scaleway import scaleway_instance_security_group

    from terrascript.data.scaleway.scaleway import scaleway_instance_server

    from terrascript.data.scaleway.scaleway import scaleway_instance_volume

    from terrascript.data.scaleway.scaleway import scaleway_k8s_cluster

    from terrascript.data.scaleway.scaleway import scaleway_k8s_pool

    from terrascript.data.scaleway.scaleway import scaleway_lb_ip

    from terrascript.data.scaleway.scaleway import scaleway_marketplace_image

    from terrascript.data.scaleway.scaleway import scaleway_rdb_acl

    from terrascript.data.scaleway.scaleway import scaleway_rdb_database

    from terrascript.data.scaleway.scaleway import scaleway_rdb_instance

    from terrascript.data.scaleway.scaleway import scaleway_registry_image

    from terrascript.data.scaleway.scaleway import scaleway_registry_namespace

    from terrascript.data.scaleway.scaleway import scaleway_vpc_private_network


# TODO: Shortcut imports without namespace for official and supported providers.

# TODO: This has to be moved into a required_providers block.
# def test_version_source():
#
#      import terrascript.provider.scaleway.scaleway
#
#      t = terrascript.provider.scaleway.scaleway.scaleway()
#      s = str(t)
#
#      assert 'https://github.com/scaleway/terraform-provider-scaleway' in s
#      assert '2.1.0' in s
