# terrascript/resource/newrelic/newrelic.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:24 UTC)
import terrascript


class newrelic_alert_channel(terrascript.Resource):
    pass


class newrelic_alert_condition(terrascript.Resource):
    pass


class newrelic_alert_muting_rule(terrascript.Resource):
    pass


class newrelic_alert_policy(terrascript.Resource):
    pass


class newrelic_alert_policy_channel(terrascript.Resource):
    pass


class newrelic_api_access_key(terrascript.Resource):
    pass


class newrelic_application_settings(terrascript.Resource):
    pass


class newrelic_dashboard(terrascript.Resource):
    pass


class newrelic_entity_tags(terrascript.Resource):
    pass


class newrelic_events_to_metrics_rule(terrascript.Resource):
    pass


class newrelic_infra_alert_condition(terrascript.Resource):
    pass


class newrelic_insights_event(terrascript.Resource):
    pass


class newrelic_nrql_alert_condition(terrascript.Resource):
    pass


class newrelic_nrql_drop_rule(terrascript.Resource):
    pass


class newrelic_one_dashboard(terrascript.Resource):
    pass


class newrelic_one_dashboard_raw(terrascript.Resource):
    pass


class newrelic_plugins_alert_condition(terrascript.Resource):
    pass


class newrelic_synthetics_alert_condition(terrascript.Resource):
    pass


class newrelic_synthetics_monitor(terrascript.Resource):
    pass


class newrelic_synthetics_monitor_script(terrascript.Resource):
    pass


class newrelic_synthetics_multilocation_alert_condition(terrascript.Resource):
    pass


class newrelic_synthetics_secure_credential(terrascript.Resource):
    pass


class newrelic_workload(terrascript.Resource):
    pass

__all__ = [
    "newrelic_alert_channel",
    "newrelic_alert_condition",
    "newrelic_alert_muting_rule",
    "newrelic_alert_policy",
    "newrelic_alert_policy_channel",
    "newrelic_api_access_key",
    "newrelic_application_settings",
    "newrelic_dashboard",
    "newrelic_entity_tags",
    "newrelic_events_to_metrics_rule",
    "newrelic_infra_alert_condition",
    "newrelic_insights_event",
    "newrelic_nrql_alert_condition",
    "newrelic_nrql_drop_rule",
    "newrelic_one_dashboard",
    "newrelic_one_dashboard_raw",
    "newrelic_plugins_alert_condition",
    "newrelic_synthetics_alert_condition",
    "newrelic_synthetics_monitor",
    "newrelic_synthetics_monitor_script",
    "newrelic_synthetics_multilocation_alert_condition",
    "newrelic_synthetics_secure_credential",
    "newrelic_workload",
]
