# terrascript/resource/bgpat/travis.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:29:15 UTC)
import terrascript


class travis_env_var(terrascript.Resource):
    pass


__all__ = [
    "travis_env_var",
]
