# terrascript/data/NaverCloudPlatform/ncloud.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:22:04 UTC)
import terrascript


class ncloud_access_control_group(terrascript.Data):
    pass


class ncloud_access_control_groups(terrascript.Data):
    pass


class ncloud_access_control_rule(terrascript.Data):
    pass


class ncloud_access_control_rules(terrascript.Data):
    pass


class ncloud_auto_scaling_group(terrascript.Data):
    pass


class ncloud_auto_scaling_policy(terrascript.Data):
    pass


class ncloud_auto_scaling_schedule(terrascript.Data):
    pass


class ncloud_block_storage(terrascript.Data):
    pass


class ncloud_block_storage_snapshot(terrascript.Data):
    pass


class ncloud_init_script(terrascript.Data):
    pass


class ncloud_launch_configuration(terrascript.Data):
    pass


class ncloud_lb(terrascript.Data):
    pass


class ncloud_lb_listener(terrascript.Data):
    pass


class ncloud_lb_target_group(terrascript.Data):
    pass


class ncloud_member_server_image(terrascript.Data):
    pass


class ncloud_member_server_images(terrascript.Data):
    pass


class ncloud_nas_volume(terrascript.Data):
    pass


class ncloud_nas_volumes(terrascript.Data):
    pass


class ncloud_nat_gateway(terrascript.Data):
    pass


class ncloud_network_acls(terrascript.Data):
    pass


class ncloud_network_interface(terrascript.Data):
    pass


class ncloud_network_interfaces(terrascript.Data):
    pass


class ncloud_placement_group(terrascript.Data):
    pass


class ncloud_port_forwarding_rule(terrascript.Data):
    pass


class ncloud_port_forwarding_rules(terrascript.Data):
    pass


class ncloud_public_ip(terrascript.Data):
    pass


class ncloud_regions(terrascript.Data):
    pass


class ncloud_root_password(terrascript.Data):
    pass


class ncloud_route_table(terrascript.Data):
    pass


class ncloud_route_tables(terrascript.Data):
    pass


class ncloud_server(terrascript.Data):
    pass


class ncloud_server_image(terrascript.Data):
    pass


class ncloud_server_images(terrascript.Data):
    pass


class ncloud_server_product(terrascript.Data):
    pass


class ncloud_server_products(terrascript.Data):
    pass


class ncloud_subnet(terrascript.Data):
    pass


class ncloud_subnets(terrascript.Data):
    pass


class ncloud_vpc(terrascript.Data):
    pass


class ncloud_vpc_peering(terrascript.Data):
    pass


class ncloud_vpcs(terrascript.Data):
    pass


class ncloud_zones(terrascript.Data):
    pass


__all__ = [
    "ncloud_access_control_group",
    "ncloud_access_control_groups",
    "ncloud_access_control_rule",
    "ncloud_access_control_rules",
    "ncloud_auto_scaling_group",
    "ncloud_auto_scaling_policy",
    "ncloud_auto_scaling_schedule",
    "ncloud_block_storage",
    "ncloud_block_storage_snapshot",
    "ncloud_init_script",
    "ncloud_launch_configuration",
    "ncloud_lb",
    "ncloud_lb_listener",
    "ncloud_lb_target_group",
    "ncloud_member_server_image",
    "ncloud_member_server_images",
    "ncloud_nas_volume",
    "ncloud_nas_volumes",
    "ncloud_nat_gateway",
    "ncloud_network_acls",
    "ncloud_network_interface",
    "ncloud_network_interfaces",
    "ncloud_placement_group",
    "ncloud_port_forwarding_rule",
    "ncloud_port_forwarding_rules",
    "ncloud_public_ip",
    "ncloud_regions",
    "ncloud_root_password",
    "ncloud_route_table",
    "ncloud_route_tables",
    "ncloud_server",
    "ncloud_server_image",
    "ncloud_server_images",
    "ncloud_server_product",
    "ncloud_server_products",
    "ncloud_subnet",
    "ncloud_subnets",
    "ncloud_vpc",
    "ncloud_vpc_peering",
    "ncloud_vpcs",
    "ncloud_zones",
]
