# terrascript/provider/rancher/rancher2.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:25:37 UTC)

import terrascript


class rancher2(terrascript.Provider):
    """Terraform Rancher2 provider"""

    __description__ = "Terraform Rancher2 provider"
    __namespace__ = "rancher"
    __name__ = "rancher2"
    __source__ = "https://github.com/rancher/terraform-provider-rancher2"
    __version__ = "1.20.0"
    __published__ = "2021-09-17T16:07:45Z"
    __tier__ = "partner"


__all__ = ["rancher2"]
