# terrascript/mongodbatlas/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class mongodbatlas_alert_configuration(terrascript.Resource):
    pass


class mongodbatlas_auditing(terrascript.Resource):
    pass


class mongodbatlas_cloud_backup_schedule(terrascript.Resource):
    pass


class mongodbatlas_cloud_provider_access(terrascript.Resource):
    pass


class mongodbatlas_cloud_provider_access_authorization(terrascript.Resource):
    pass


class mongodbatlas_cloud_provider_access_setup(terrascript.Resource):
    pass


class mongodbatlas_cloud_provider_snapshot(terrascript.Resource):
    pass


class mongodbatlas_cloud_provider_snapshot_backup_policy(terrascript.Resource):
    pass


class mongodbatlas_cloud_provider_snapshot_restore_job(terrascript.Resource):
    pass


class mongodbatlas_cluster(terrascript.Resource):
    pass


class mongodbatlas_custom_db_role(terrascript.Resource):
    pass


class mongodbatlas_custom_dns_configuration_cluster_aws(terrascript.Resource):
    pass


class mongodbatlas_data_lake(terrascript.Resource):
    pass


class mongodbatlas_database_user(terrascript.Resource):
    pass


class mongodbatlas_encryption_at_rest(terrascript.Resource):
    pass


class mongodbatlas_event_trigger(terrascript.Resource):
    pass


class mongodbatlas_global_cluster_config(terrascript.Resource):
    pass


class mongodbatlas_ldap_configuration(terrascript.Resource):
    pass


class mongodbatlas_ldap_verify(terrascript.Resource):
    pass


class mongodbatlas_maintenance_window(terrascript.Resource):
    pass


class mongodbatlas_network_container(terrascript.Resource):
    pass


class mongodbatlas_network_peering(terrascript.Resource):
    pass


class mongodbatlas_online_archive(terrascript.Resource):
    pass


class mongodbatlas_private_ip_mode(terrascript.Resource):
    pass


class mongodbatlas_privatelink_endpoint(terrascript.Resource):
    pass


class mongodbatlas_privatelink_endpoint_service(terrascript.Resource):
    pass


class mongodbatlas_project(terrascript.Resource):
    pass


class mongodbatlas_project_ip_access_list(terrascript.Resource):
    pass


class mongodbatlas_search_index(terrascript.Resource):
    pass


class mongodbatlas_team(terrascript.Resource):
    pass


class mongodbatlas_teams(terrascript.Resource):
    pass


class mongodbatlas_third_party_integration(terrascript.Resource):
    pass


class mongodbatlas_x509_authentication_database_user(terrascript.Resource):
    pass
