# terrascript/resource/ns1-terraform/ns1.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:26 UTC)
import terrascript


class ns1_apikey(terrascript.Resource):
    pass


class ns1_datafeed(terrascript.Resource):
    pass


class ns1_datasource(terrascript.Resource):
    pass


class ns1_monitoringjob(terrascript.Resource):
    pass


class ns1_notifylist(terrascript.Resource):
    pass


class ns1_record(terrascript.Resource):
    pass


class ns1_team(terrascript.Resource):
    pass


class ns1_user(terrascript.Resource):
    pass


class ns1_zone(terrascript.Resource):
    pass

__all__ = [
    "ns1_apikey",
    "ns1_datafeed",
    "ns1_datasource",
    "ns1_monitoringjob",
    "ns1_notifylist",
    "ns1_record",
    "ns1_team",
    "ns1_user",
    "ns1_zone",
]
