# terrascript/provider/bgpat/dnsimple.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:20 UTC)

import terrascript

class dnsimple(terrascript.Provider):
    '''Terraform DNSimple provider
    
    '''
    __description__ = "Terraform DNSimple provider"
    __namespace__ = "bgpat"
    __name__ = "dnsimple"
    __source__ = "https://github.com/bgpat/terraform-provider-dnsimple"
    __version__ = "0.5.1"
    __published__ = "2021-08-20T14:40:16Z"
    __tier__ = "community"
    

__all__ = ["dnsimple"]
