# terrascript/resource/onelogin/onelogin.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:23:37 UTC)
import terrascript


class onelogin_app_role_attachments(terrascript.Resource):
    pass


class onelogin_app_rules(terrascript.Resource):
    pass


class onelogin_apps(terrascript.Resource):
    pass


class onelogin_auth_servers(terrascript.Resource):
    pass


class onelogin_oidc_apps(terrascript.Resource):
    pass


class onelogin_privileges(terrascript.Resource):
    pass


class onelogin_roles(terrascript.Resource):
    pass


class onelogin_saml_apps(terrascript.Resource):
    pass


class onelogin_smarthook_environment_variables(terrascript.Resource):
    pass


class onelogin_smarthooks(terrascript.Resource):
    pass


class onelogin_user_mappings(terrascript.Resource):
    pass


class onelogin_users(terrascript.Resource):
    pass


__all__ = [
    "onelogin_app_role_attachments",
    "onelogin_app_rules",
    "onelogin_apps",
    "onelogin_auth_servers",
    "onelogin_oidc_apps",
    "onelogin_privileges",
    "onelogin_roles",
    "onelogin_saml_apps",
    "onelogin_smarthook_environment_variables",
    "onelogin_smarthooks",
    "onelogin_user_mappings",
    "onelogin_users",
]
