# terrascript/resource/datarootsio/kubeflowpipelines.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:20:37 UTC)
import terrascript


class kubeflowpipelines_experiment(terrascript.Resource):
    pass


class kubeflowpipelines_job(terrascript.Resource):
    pass


class kubeflowpipelines_pipeline(terrascript.Resource):
    pass


class kubeflowpipelines_run(terrascript.Resource):
    pass


__all__ = [
    "kubeflowpipelines_experiment",
    "kubeflowpipelines_job",
    "kubeflowpipelines_pipeline",
    "kubeflowpipelines_run",
]
