# terrascript/outlook/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class outlook_category(terrascript.Data):
    pass


class outlook_mail_folder(terrascript.Data):
    pass
