# terrascript/resource/magodo/outlook.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:40 UTC)
import terrascript


class outlook_category(terrascript.Resource):
    pass


class outlook_mail_folder(terrascript.Resource):
    pass


class outlook_message_rule(terrascript.Resource):
    pass

__all__ = [
    "outlook_category",
    "outlook_mail_folder",
    "outlook_message_rule",
]
