# terrascript/data/DataDog/datadog.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:15:03 UTC)
import terrascript


class datadog_api_key(terrascript.Data):
    pass


class datadog_application_key(terrascript.Data):
    pass


class datadog_dashboard(terrascript.Data):
    pass


class datadog_dashboard_list(terrascript.Data):
    pass


class datadog_ip_ranges(terrascript.Data):
    pass


class datadog_monitor(terrascript.Data):
    pass


class datadog_monitors(terrascript.Data):
    pass


class datadog_permissions(terrascript.Data):
    pass


class datadog_role(terrascript.Data):
    pass


class datadog_security_monitoring_filters(terrascript.Data):
    pass


class datadog_security_monitoring_rules(terrascript.Data):
    pass


class datadog_service_level_objective(terrascript.Data):
    pass


class datadog_service_level_objectives(terrascript.Data):
    pass


class datadog_synthetics_global_variable(terrascript.Data):
    pass


class datadog_synthetics_locations(terrascript.Data):
    pass


class datadog_user(terrascript.Data):
    pass


__all__ = [
    "datadog_api_key",
    "datadog_application_key",
    "datadog_dashboard",
    "datadog_dashboard_list",
    "datadog_ip_ranges",
    "datadog_monitor",
    "datadog_monitors",
    "datadog_permissions",
    "datadog_role",
    "datadog_security_monitoring_filters",
    "datadog_security_monitoring_rules",
    "datadog_service_level_objective",
    "datadog_service_level_objectives",
    "datadog_synthetics_global_variable",
    "datadog_synthetics_locations",
    "datadog_user",
]
