# terrascript/data/jianyuan/sentry.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:49 UTC)
import terrascript


class sentry_key(terrascript.Data):
    pass


class sentry_organization(terrascript.Data):
    pass


__all__ = [
    "sentry_key",
    "sentry_organization",
]
