# terrascript/data/bgpat/shellescape.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:07 UTC)
import terrascript


class shellescape_quote(terrascript.Data):
    pass


__all__ = [
    "shellescape_quote",
]
