# terrascript/provider/pmorillon/grid5000.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:17:36 UTC)

import terrascript


class grid5000(terrascript.Provider):
    """Terraform provider plugin for OAR jobs submission and Kadeploy bare-metal deployments on Grid'5000"""

    __description__ = "Terraform provider plugin for OAR jobs submission and Kadeploy bare-metal deployments on Grid'5000"
    __namespace__ = "pmorillon"
    __name__ = "grid5000"
    __source__ = "https://github.com/pmorillon/terraform-provider-grid5000"
    __version__ = "0.0.7"
    __published__ = "2021-02-10T13:50:46Z"
    __tier__ = "community"


__all__ = ["grid5000"]
