# terrascript/sentry/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class sentry_key(terrascript.Data):
    pass


class sentry_organization(terrascript.Data):
    pass
