# terrascript/provider/jeremmfr/iptables.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:19:14 UTC)

import terrascript


class iptables(terrascript.Provider):
    """Terraform's provider for generate iptables rules with iptables-api"""

    __description__ = (
        "Terraform's provider for generate iptables rules with iptables-api "
    )
    __namespace__ = "jeremmfr"
    __name__ = "iptables"
    __source__ = "https://github.com/jeremmfr/terraform-provider-iptables"
    __version__ = "1.2.0"
    __published__ = "2021-07-30T09:17:22Z"
    __tier__ = "community"


__all__ = ["iptables"]
