# terrascript/provider/datarootsio/kubeflowpipelines.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:20:37 UTC)

import terrascript


class kubeflowpipelines(terrascript.Provider):
    """Terraform provider for Kubeflow pipelines API"""

    __description__ = "Terraform provider for Kubeflow pipelines API"
    __namespace__ = "datarootsio"
    __name__ = "kubeflowpipelines"
    __source__ = "https://github.com/datarootsio/terraform-provider-kubeflowpipelines"
    __version__ = "0.0.10"
    __published__ = "2020-08-12T11:01:42Z"
    __tier__ = "community"


__all__ = ["kubeflowpipelines"]
