# terrascript/phpipam/d.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class phpipam_address(terrascript.Data):
    pass


class phpipam_addresses(terrascript.Data):
    pass


class phpipam_first_free_address(terrascript.Data):
    pass


class phpipam_section(terrascript.Data):
    pass


class phpipam_subnet(terrascript.Data):
    pass


class phpipam_subnets(terrascript.Data):
    pass


class phpipam_vlan(terrascript.Data):
    pass
