# terrascript/resource/TomTucka/circleci.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:55 UTC)
import terrascript


class circleci_environment_variable(terrascript.Resource):
    pass


class circleci_project(terrascript.Resource):
    pass


__all__ = [
    "circleci_environment_variable",
    "circleci_project",
]
