# terrascript/vcd/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class vcd_catalog(terrascript.Resource):
    pass


class vcd_catalog_item(terrascript.Resource):
    pass


class vcd_catalog_media(terrascript.Resource):
    pass


class vcd_edgegateway(terrascript.Resource):
    pass


class vcd_edgegateway_settings(terrascript.Resource):
    pass


class vcd_edgegateway_vpn(terrascript.Resource):
    pass


class vcd_external_network(terrascript.Resource):
    pass


class vcd_external_network_v2(terrascript.Resource):
    pass


class vcd_global_role(terrascript.Resource):
    pass


class vcd_independent_disk(terrascript.Resource):
    pass


class vcd_inserted_media(terrascript.Resource):
    pass


class vcd_lb_app_profile(terrascript.Resource):
    pass


class vcd_lb_app_rule(terrascript.Resource):
    pass


class vcd_lb_server_pool(terrascript.Resource):
    pass


class vcd_lb_service_monitor(terrascript.Resource):
    pass


class vcd_lb_virtual_server(terrascript.Resource):
    pass


class vcd_network_direct(terrascript.Resource):
    pass


class vcd_network_isolated(terrascript.Resource):
    pass


class vcd_network_isolated_v2(terrascript.Resource):
    pass


class vcd_network_routed(terrascript.Resource):
    pass


class vcd_network_routed_v2(terrascript.Resource):
    pass


class vcd_nsxt_app_port_profile(terrascript.Resource):
    pass


class vcd_nsxt_edgegateway(terrascript.Resource):
    pass


class vcd_nsxt_firewall(terrascript.Resource):
    pass


class vcd_nsxt_ip_set(terrascript.Resource):
    pass


class vcd_nsxt_ipsec_vpn_tunnel(terrascript.Resource):
    pass


class vcd_nsxt_nat_rule(terrascript.Resource):
    pass


class vcd_nsxt_network_dhcp(terrascript.Resource):
    pass


class vcd_nsxt_network_imported(terrascript.Resource):
    pass


class vcd_nsxt_security_group(terrascript.Resource):
    pass


class vcd_nsxv_dhcp_relay(terrascript.Resource):
    pass


class vcd_nsxv_dnat(terrascript.Resource):
    pass


class vcd_nsxv_firewall_rule(terrascript.Resource):
    pass


class vcd_nsxv_ip_set(terrascript.Resource):
    pass


class vcd_nsxv_snat(terrascript.Resource):
    pass


class vcd_org(terrascript.Resource):
    pass


class vcd_org_group(terrascript.Resource):
    pass


class vcd_org_user(terrascript.Resource):
    pass


class vcd_org_vdc(terrascript.Resource):
    pass


class vcd_rights_bundle(terrascript.Resource):
    pass


class vcd_role(terrascript.Resource):
    pass


class vcd_vapp(terrascript.Resource):
    pass


class vcd_vapp_access_control(terrascript.Resource):
    pass


class vcd_vapp_firewall_rules(terrascript.Resource):
    pass


class vcd_vapp_nat_rules(terrascript.Resource):
    pass


class vcd_vapp_network(terrascript.Resource):
    pass


class vcd_vapp_org_network(terrascript.Resource):
    pass


class vcd_vapp_static_routing(terrascript.Resource):
    pass


class vcd_vapp_vm(terrascript.Resource):
    pass


class vcd_vm(terrascript.Resource):
    pass


class vcd_vm_affinity_rule(terrascript.Resource):
    pass


class vcd_vm_internal_disk(terrascript.Resource):
    pass


class vcd_vm_sizing_policy(terrascript.Resource):
    pass
