# terrascript/resource/rancher/rke.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:25:51 UTC)
import terrascript


class rke_cluster(terrascript.Resource):
    pass


__all__ = [
    "rke_cluster",
]
