# terrascript/provider/gavinbunney/oktafork.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:23:32 UTC)

import terrascript


class oktafork(terrascript.Provider):
    """Terraform Okta provider"""

    __description__ = "Terraform Okta provider"
    __namespace__ = "gavinbunney"
    __name__ = "oktafork"
    __source__ = "https://github.com/gavinbunney/terraform-provider-oktafork"
    __version__ = "3.12.9"
    __published__ = "2021-07-13T23:02:56Z"
    __tier__ = "community"


__all__ = ["oktafork"]
