# terrascript/resource/iwarapter/scaffolding.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:11 UTC)
import terrascript


class scaffolding_resource(terrascript.Resource):
    pass


__all__ = [
    "scaffolding_resource",
]
