# terrascript/resource/ddelnano/mikrotik.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:18 UTC)
import terrascript


class mikrotik_bgp_instance(terrascript.Resource):
    pass


class mikrotik_bgp_peer(terrascript.Resource):
    pass


class mikrotik_dhcp_lease(terrascript.Resource):
    pass


class mikrotik_dns_record(terrascript.Resource):
    pass


class mikrotik_pool(terrascript.Resource):
    pass


class mikrotik_scheduler(terrascript.Resource):
    pass


class mikrotik_script(terrascript.Resource):
    pass

__all__ = [
    "mikrotik_bgp_instance",
    "mikrotik_bgp_peer",
    "mikrotik_dhcp_lease",
    "mikrotik_dns_record",
    "mikrotik_pool",
    "mikrotik_scheduler",
    "mikrotik_script",
]
