# terrascript/data/alxrem/hdns.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:18 UTC)
import terrascript


class hdns_zone(terrascript.Data):
    pass


__all__ = [
    "hdns_zone",
]
