# terrascript/provider/heroku/heroku.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:37 UTC)

import terrascript


class heroku(terrascript.Provider):
    """Terraform Heroku provider"""

    __description__ = "Terraform Heroku provider"
    __namespace__ = "heroku"
    __name__ = "heroku"
    __source__ = "https://github.com/heroku/terraform-provider-heroku"
    __version__ = "4.6.0"
    __published__ = "2021-07-14T21:53:12Z"
    __tier__ = "partner"


__all__ = ["heroku"]
