# terrascript/idm/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class idm_dns_record(terrascript.Resource):
    pass


class idm_host(terrascript.Resource):
    pass
