# terrascript/datadog/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class datadog_dashboard(terrascript.Data):
    pass


class datadog_dashboard_list(terrascript.Data):
    pass


class datadog_ip_ranges(terrascript.Data):
    pass


class datadog_monitor(terrascript.Data):
    pass


class datadog_monitors(terrascript.Data):
    pass


class datadog_permissions(terrascript.Data):
    pass


class datadog_role(terrascript.Data):
    pass


class datadog_security_monitoring_rules(terrascript.Data):
    pass


class datadog_service_level_objective(terrascript.Data):
    pass


class datadog_service_level_objectives(terrascript.Data):
    pass


class datadog_synthetics_locations(terrascript.Data):
    pass
