# terrascript/resource/brightbox/brightbox.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:07 UTC)
import terrascript


class brightbox_api_client(terrascript.Resource):
    pass


class brightbox_cloudip(terrascript.Resource):
    pass


class brightbox_config_map(terrascript.Resource):
    pass


class brightbox_database_server(terrascript.Resource):
    pass


class brightbox_firewall_policy(terrascript.Resource):
    pass


class brightbox_firewall_rule(terrascript.Resource):
    pass


class brightbox_load_balancer(terrascript.Resource):
    pass


class brightbox_orbit_container(terrascript.Resource):
    pass


class brightbox_server(terrascript.Resource):
    pass


class brightbox_server_group(terrascript.Resource):
    pass

__all__ = [
    "brightbox_api_client",
    "brightbox_cloudip",
    "brightbox_config_map",
    "brightbox_database_server",
    "brightbox_firewall_policy",
    "brightbox_firewall_rule",
    "brightbox_load_balancer",
    "brightbox_orbit_container",
    "brightbox_server",
    "brightbox_server_group",
]
