# terrascript/resource/abergmeier/exasol.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:16:02 UTC)
import terrascript


class exasol_connection(terrascript.Resource):
    pass


class exasol_physical_schema(terrascript.Resource):
    pass


class exasol_role(terrascript.Resource):
    pass


class exasol_table(terrascript.Resource):
    pass


class exasol_user(terrascript.Resource):
    pass


class exasol_view(terrascript.Resource):
    pass


__all__ = [
    "exasol_connection",
    "exasol_physical_schema",
    "exasol_role",
    "exasol_table",
    "exasol_user",
    "exasol_view",
]
