# terrascript/provider/nauxliu/pingdom.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:43 UTC)

import terrascript

class pingdom(terrascript.Provider):
    '''Terraform provider to manage pingdom resources
    
    '''
    __description__ = "Terraform provider to manage pingdom resources"
    __namespace__ = "nauxliu"
    __name__ = "pingdom"
    __source__ = "https://github.com/nauxliu/terraform-provider-pingdom"
    __version__ = "1.1.2"
    __published__ = "2020-08-13T08:36:39Z"
    __tier__ = "community"
    

__all__ = ["pingdom"]
