# terrascript/data/paultyng/airtable.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:11:05 UTC)
import terrascript


class airtable_table(terrascript.Data):
    pass


__all__ = [
    "airtable_table",
]
