# terrascript/provider/philips-software/hsdp.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:54 UTC)

import terrascript

class hsdp(terrascript.Provider):
    '''Terraform provider to orchestrate various HSDP resources https://registry.terraform.io/providers/philips-software/hsdp/latest
    
    '''
    __description__ = "Terraform provider to orchestrate various HSDP resources https://registry.terraform.io/providers/philips-software/hsdp/latest"
    __namespace__ = "philips-software"
    __name__ = "hsdp"
    __source__ = "https://github.com/philips-software/terraform-provider-hsdp"
    __version__ = "0.18.8"
    __published__ = "2021-08-08T20:11:33Z"
    __tier__ = "community"
    

__all__ = ["hsdp"]
