# terrascript/resource/yannh/statuspage.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:27:54 UTC)
import terrascript


class statuspage_component(terrascript.Resource):
    pass


class statuspage_component_group(terrascript.Resource):
    pass


class statuspage_metric(terrascript.Resource):
    pass


class statuspage_metrics_provider(terrascript.Resource):
    pass


__all__ = [
    "statuspage_component",
    "statuspage_component_group",
    "statuspage_metric",
    "statuspage_metrics_provider",
]
