# terrascript/provider/innovationnorway/domeneshop.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:20 UTC)

import terrascript

class domeneshop(terrascript.Provider):
    '''Terraform provider for Domeneshop (domainnameshop)
    
    '''
    __description__ = "Terraform provider for Domeneshop (domainnameshop)"
    __namespace__ = "innovationnorway"
    __name__ = "domeneshop"
    __source__ = "https://github.com/innovationnorway/terraform-provider-domeneshop"
    __version__ = "0.1.0"
    __published__ = "2021-01-11T18:15:16Z"
    __tier__ = "community"
    

__all__ = ["domeneshop"]
