# terrascript/provider/innovationnorway/git.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:16:55 UTC)

import terrascript


class git(terrascript.Provider):
    """Terraform provider for Git"""

    __description__ = "Terraform provider for Git"
    __namespace__ = "innovationnorway"
    __name__ = "git"
    __source__ = "https://github.com/innovationnorway/terraform-provider-git"
    __version__ = "0.1.3"
    __published__ = "2020-07-04T12:56:44Z"
    __tier__ = "community"


__all__ = ["git"]
