# terrascript/provider/innovationnorway/netbox.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:22:28 UTC)

import terrascript


class netbox(terrascript.Provider):
    """Terraform provider for NetBox"""

    __description__ = "Terraform provider for NetBox"
    __namespace__ = "innovationnorway"
    __name__ = "netbox"
    __source__ = "https://github.com/innovationnorway/terraform-provider-netbox"
    __version__ = "0.1.0-alpha.2"
    __published__ = "2021-02-01T22:07:45Z"
    __tier__ = "community"


__all__ = ["netbox"]
