# terrascript/provider/innovationnorway/seq.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:53 UTC)

import terrascript


class seq(terrascript.Provider):
    """Terraform provider for Seq"""

    __description__ = "Terraform provider for Seq"
    __namespace__ = "innovationnorway"
    __name__ = "seq"
    __source__ = "https://github.com/innovationnorway/terraform-provider-seq"
    __version__ = "0.1.0-alpha.5"
    __published__ = "2021-03-14T23:41:58Z"
    __tier__ = "community"


__all__ = ["seq"]
