# terrascript/data/chanzuckerberg/bless.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:34 UTC)
import terrascript


class bless_kms_public_key(terrascript.Data):
    pass


__all__ = [
    "bless_kms_public_key",
]
