# terrascript/oraclepaas/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class oraclepaas_database_service_instance(terrascript.Data):
    pass
