# terrascript/kafka_connect/__init__.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)

import terrascript


class kafka_connect(terrascript.Provider):
    pass
