# terrascript/provider/cyrilgdn/postgresql.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:47 UTC)

import terrascript

class postgresql(terrascript.Provider):
    '''Terraform PostgreSQL provider
    
    '''
    __description__ = "Terraform PostgreSQL provider"
    __namespace__ = "cyrilgdn"
    __name__ = "postgresql"
    __source__ = "https://github.com/cyrilgdn/terraform-provider-postgresql"
    __version__ = "1.14.0"
    __published__ = "2021-08-22T13:58:27Z"
    __tier__ = "community"
    

__all__ = ["postgresql"]
