# terrascript/hcp/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class hcp_aws_network_peering(terrascript.Resource):
    pass


class hcp_aws_transit_gateway_attachment(terrascript.Resource):
    pass


class hcp_consul_cluster(terrascript.Resource):
    pass


class hcp_consul_cluster_root_token(terrascript.Resource):
    pass


class hcp_consul_snapshot(terrascript.Resource):
    pass


class hcp_hvn(terrascript.Resource):
    pass


class hcp_hvn_peering_connection(terrascript.Resource):
    pass


class hcp_hvn_route(terrascript.Resource):
    pass


class hcp_vault_cluster(terrascript.Resource):
    pass


class hcp_vault_cluster_admin_token(terrascript.Resource):
    pass
