# terrascript/selectel/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class selectel_dbaas_available_extension_v1(terrascript.Data):
    pass


class selectel_dbaas_datastore_type_v1(terrascript.Data):
    pass


class selectel_dbaas_flavor_v1(terrascript.Data):
    pass


class selectel_domains_domain_v1(terrascript.Data):
    pass
