# terrascript/data/mildred/sys.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:28:08 UTC)
import terrascript


class sys_error(terrascript.Data):
    pass


class sys_file(terrascript.Data):
    pass


class sys_shell_script(terrascript.Data):
    pass


__all__ = [
    "sys_error",
    "sys_file",
    "sys_shell_script",
]
