# terrascript/resource/gavinbunney/bitbucketserver.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:29 UTC)
import terrascript


class bitbucketserver_banner(terrascript.Resource):
    pass


class bitbucketserver_default_reviewers_condition(terrascript.Resource):
    pass


class bitbucketserver_global_permissions_group(terrascript.Resource):
    pass


class bitbucketserver_global_permissions_user(terrascript.Resource):
    pass


class bitbucketserver_group(terrascript.Resource):
    pass


class bitbucketserver_license(terrascript.Resource):
    pass


class bitbucketserver_mail_server(terrascript.Resource):
    pass


class bitbucketserver_plugin(terrascript.Resource):
    pass


class bitbucketserver_plugin_config(terrascript.Resource):
    pass


class bitbucketserver_project(terrascript.Resource):
    pass


class bitbucketserver_project_hook(terrascript.Resource):
    pass


class bitbucketserver_project_permissions_group(terrascript.Resource):
    pass


class bitbucketserver_project_permissions_user(terrascript.Resource):
    pass


class bitbucketserver_repository(terrascript.Resource):
    pass


class bitbucketserver_repository_hook(terrascript.Resource):
    pass


class bitbucketserver_repository_permissions_group(terrascript.Resource):
    pass


class bitbucketserver_repository_permissions_user(terrascript.Resource):
    pass


class bitbucketserver_user(terrascript.Resource):
    pass


class bitbucketserver_user_access_token(terrascript.Resource):
    pass


class bitbucketserver_user_group(terrascript.Resource):
    pass


__all__ = [
    "bitbucketserver_banner",
    "bitbucketserver_default_reviewers_condition",
    "bitbucketserver_global_permissions_group",
    "bitbucketserver_global_permissions_user",
    "bitbucketserver_group",
    "bitbucketserver_license",
    "bitbucketserver_mail_server",
    "bitbucketserver_plugin",
    "bitbucketserver_plugin_config",
    "bitbucketserver_project",
    "bitbucketserver_project_hook",
    "bitbucketserver_project_permissions_group",
    "bitbucketserver_project_permissions_user",
    "bitbucketserver_repository",
    "bitbucketserver_repository_hook",
    "bitbucketserver_repository_permissions_group",
    "bitbucketserver_repository_permissions_user",
    "bitbucketserver_user",
    "bitbucketserver_user_access_token",
    "bitbucketserver_user_group",
]
