# terrascript/resource/bltavares/zerotier.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:40 UTC)
import terrascript


class zerotier_member(terrascript.Resource):
    pass


class zerotier_network(terrascript.Resource):
    pass

__all__ = [
    "zerotier_member",
    "zerotier_network",
]
