# terrascript/provider/e-breuninger/netbox.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:22:23 UTC)

import terrascript


class netbox(terrascript.Provider):
    """Terraform provider to interact with Netbox"""

    __description__ = "Terraform provider to interact with Netbox"
    __namespace__ = "e-breuninger"
    __name__ = "netbox"
    __source__ = "https://github.com/e-breuninger/terraform-provider-netbox"
    __version__ = "0.2.4"
    __published__ = "2021-09-20T10:25:58Z"
    __tier__ = "community"


__all__ = ["netbox"]
