# terrascript/resource/davidji99/split.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:10 UTC)
import terrascript


class split_environment(terrascript.Resource):
    pass


class split_group(terrascript.Resource):
    pass


class split_segment(terrascript.Resource):
    pass


class split_user(terrascript.Resource):
    pass

__all__ = [
    "split_environment",
    "split_group",
    "split_segment",
    "split_user",
]
