# terrascript/provider/banzaicloud/k8s.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:19:55 UTC)

import terrascript


class k8s(terrascript.Provider):
    """Kubernetes Terraform provider with support for raw manifests"""

    __description__ = "Kubernetes Terraform provider with support for raw manifests"
    __namespace__ = "banzaicloud"
    __name__ = "k8s"
    __source__ = "https://github.com/banzaicloud/terraform-provider-k8s"
    __version__ = "0.9.1"
    __published__ = "2021-03-17T14:36:53Z"
    __tier__ = "community"


__all__ = ["k8s"]
