# terrascript/resource/Ouest-France/itop.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:19:18 UTC)
import terrascript


class itop_virtual_machine(terrascript.Resource):
    pass


__all__ = [
    "itop_virtual_machine",
]
