# terrascript/data/vinyldns/vinyldns.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:30:26 UTC)
import terrascript


class vinyldns_zone(terrascript.Data):
    pass


__all__ = [
    "vinyldns_zone",
]
