# terrascript/resource/phoenixnap/pnap.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:24:49 UTC)
import terrascript


class pnap_server(terrascript.Resource):
    pass


class pnap_ssh_key(terrascript.Resource):
    pass


__all__ = [
    "pnap_server",
    "pnap_ssh_key",
]
