# terrascript/aviatrix/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class aviatrix_account(terrascript.Data):
    pass


class aviatrix_caller_identity(terrascript.Data):
    pass


class aviatrix_firenet(terrascript.Data):
    pass


class aviatrix_firenet_firewall_manager(terrascript.Data):
    pass


class aviatrix_firenet_vendor_integration(terrascript.Data):
    pass


class aviatrix_firewall(terrascript.Data):
    pass


class aviatrix_gateway(terrascript.Data):
    pass


class aviatrix_gateway_image(terrascript.Data):
    pass


class aviatrix_spoke_gateway(terrascript.Data):
    pass


class aviatrix_transit_gateway(terrascript.Data):
    pass


class aviatrix_vpc(terrascript.Data):
    pass


class aviatrix_vpc_tracker(terrascript.Data):
    pass
