# terrascript/provider/josenk/esxi.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:23 UTC)

import terrascript

class esxi(terrascript.Provider):
    '''Terraform-provider-esxi plugin
    
    '''
    __description__ = "Terraform-provider-esxi plugin"
    __namespace__ = "josenk"
    __name__ = "esxi"
    __source__ = "https://github.com/josenk/terraform-provider-esxi"
    __version__ = "1.8.2"
    __published__ = "2021-05-29T02:41:44Z"
    __tier__ = "community"
    

__all__ = ["esxi"]
