# terrascript/data/NetApp/netapp_gcp.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:22:18 UTC)
import terrascript


class netapp_gcp_active_directory(terrascript.Data):
    pass


class netapp_gcp_volume(terrascript.Data):
    pass


__all__ = [
    "netapp_gcp_active_directory",
    "netapp_gcp_volume",
]
