# terrascript/data/unicell/scaffolding.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:17 UTC)
import terrascript


class scaffolding_data_source(terrascript.Data):
    pass


__all__ = [
    "scaffolding_data_source",
]
