# terrascript/resource/DeviaVir/gsuite.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:44 UTC)
import terrascript


class gsuite_domain(terrascript.Resource):
    pass


class gsuite_group(terrascript.Resource):
    pass


class gsuite_group_member(terrascript.Resource):
    pass


class gsuite_group_members(terrascript.Resource):
    pass


class gsuite_group_settings(terrascript.Resource):
    pass


class gsuite_user(terrascript.Resource):
    pass


class gsuite_user_attributes(terrascript.Resource):
    pass


class gsuite_user_schema(terrascript.Resource):
    pass

__all__ = [
    "gsuite_domain",
    "gsuite_group",
    "gsuite_group_member",
    "gsuite_group_members",
    "gsuite_group_settings",
    "gsuite_user",
    "gsuite_user_attributes",
    "gsuite_user_schema",
]
