# terrascript/provider/paultyng/git.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:17:00 UTC)

import terrascript


class git(terrascript.Provider):
    """"""

    __description__ = ""
    __namespace__ = "paultyng"
    __name__ = "git"
    __source__ = "https://github.com/paultyng/terraform-provider-git"
    __version__ = "0.1.0"
    __published__ = "2020-08-20T20:02:49Z"
    __tier__ = "community"


__all__ = ["git"]
