# terrascript/provider/paultyng/sql.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:12 UTC)

import terrascript

class sql(terrascript.Provider):
    '''
    
    '''
    __description__ = ""
    __namespace__ = "paultyng"
    __name__ = "sql"
    __source__ = "https://github.com/paultyng/terraform-provider-sql"
    __version__ = "0.4.0"
    __published__ = "2021-04-09T20:41:00Z"
    __tier__ = "community"
    

__all__ = ["sql"]
