# terrascript/provider/paultyng/unifi.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:28 UTC)

import terrascript

class unifi(terrascript.Provider):
    '''Terraform provider for Unifi :satellite:
    
    '''
    __description__ = "Terraform provider for Unifi :satellite:"
    __namespace__ = "paultyng"
    __name__ = "unifi"
    __source__ = "https://github.com/paultyng/terraform-provider-unifi"
    __version__ = "0.28.1"
    __published__ = "2021-08-20T01:27:35Z"
    __tier__ = "community"
    

__all__ = ["unifi"]
