# terrascript/azurerm/d.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class azurerm_active_directory_domain_service(terrascript.Data):
    pass


class azurerm_advisor_recommendations(terrascript.Data):
    pass


class azurerm_api_management(terrascript.Data):
    pass


class azurerm_api_management_api(terrascript.Data):
    pass


class azurerm_api_management_api_version_set(terrascript.Data):
    pass


class azurerm_api_management_gateway(terrascript.Data):
    pass


class azurerm_api_management_group(terrascript.Data):
    pass


class azurerm_api_management_product(terrascript.Data):
    pass


class azurerm_api_management_user(terrascript.Data):
    pass


class azurerm_app_configuration(terrascript.Data):
    pass


class azurerm_app_service(terrascript.Data):
    pass


class azurerm_app_service_certificate(terrascript.Data):
    pass


class azurerm_app_service_certificate_order(terrascript.Data):
    pass


class azurerm_app_service_environment(terrascript.Data):
    pass


class azurerm_app_service_environment_v3(terrascript.Data):
    pass


class azurerm_app_service_plan(terrascript.Data):
    pass


class azurerm_application_gateway(terrascript.Data):
    pass


class azurerm_application_insights(terrascript.Data):
    pass


class azurerm_application_security_group(terrascript.Data):
    pass


class azurerm_attestation_provider(terrascript.Data):
    pass


class azurerm_automation_account(terrascript.Data):
    pass


class azurerm_automation_variable_bool(terrascript.Data):
    pass


class azurerm_automation_variable_datetime(terrascript.Data):
    pass


class azurerm_automation_variable_int(terrascript.Data):
    pass


class azurerm_automation_variable_string(terrascript.Data):
    pass


class azurerm_availability_set(terrascript.Data):
    pass


class azurerm_backup_policy_vm(terrascript.Data):
    pass


class azurerm_batch_account(terrascript.Data):
    pass


class azurerm_batch_certificate(terrascript.Data):
    pass


class azurerm_batch_pool(terrascript.Data):
    pass


class azurerm_billing_enrollment_account_scope(terrascript.Data):
    pass


class azurerm_billing_mca_account_scope(terrascript.Data):
    pass


class azurerm_blueprint_definition(terrascript.Data):
    pass


class azurerm_blueprint_published_version(terrascript.Data):
    pass


class azurerm_cdn_profile(terrascript.Data):
    pass


class azurerm_client_config(terrascript.Data):
    pass


class azurerm_cognitive_account(terrascript.Data):
    pass


class azurerm_container_registry(terrascript.Data):
    pass


class azurerm_container_registry_scope_map(terrascript.Data):
    pass


class azurerm_container_registry_token(terrascript.Data):
    pass


class azurerm_cosmosdb_account(terrascript.Data):
    pass


class azurerm_cosmosdb_mongo_database(terrascript.Data):
    pass


class azurerm_data_factory(terrascript.Data):
    pass


class azurerm_data_lake_store(terrascript.Data):
    pass


class azurerm_data_protection_backup_vault(terrascript.Data):
    pass


class azurerm_data_share(terrascript.Data):
    pass


class azurerm_data_share_account(terrascript.Data):
    pass


class azurerm_data_share_dataset_blob_storage(terrascript.Data):
    pass


class azurerm_data_share_dataset_data_lake_gen1(terrascript.Data):
    pass


class azurerm_data_share_dataset_data_lake_gen2(terrascript.Data):
    pass


class azurerm_data_share_dataset_kusto_cluster(terrascript.Data):
    pass


class azurerm_data_share_dataset_kusto_database(terrascript.Data):
    pass


class azurerm_database_migration_project(terrascript.Data):
    pass


class azurerm_database_migration_service(terrascript.Data):
    pass


class azurerm_databricks_workspace(terrascript.Data):
    pass


class azurerm_databricks_workspace_private_endpoint_connection(terrascript.Data):
    pass


class azurerm_dedicated_host(terrascript.Data):
    pass


class azurerm_dedicated_host_group(terrascript.Data):
    pass


class azurerm_dev_test_lab(terrascript.Data):
    pass


class azurerm_dev_test_virtual_network(terrascript.Data):
    pass


class azurerm_digital_twins_instance(terrascript.Data):
    pass


class azurerm_disk_access(terrascript.Data):
    pass


class azurerm_disk_encryption_set(terrascript.Data):
    pass


class azurerm_dns_zone(terrascript.Data):
    pass


class azurerm_eventgrid_domain(terrascript.Data):
    pass


class azurerm_eventgrid_domain_topic(terrascript.Data):
    pass


class azurerm_eventgrid_topic(terrascript.Data):
    pass


class azurerm_eventhub(terrascript.Data):
    pass


class azurerm_eventhub_authorization_rule(terrascript.Data):
    pass


class azurerm_eventhub_cluster(terrascript.Data):
    pass


class azurerm_eventhub_consumer_group(terrascript.Data):
    pass


class azurerm_eventhub_namespace(terrascript.Data):
    pass


class azurerm_eventhub_namespace_authorization_rule(terrascript.Data):
    pass


class azurerm_express_route_circuit(terrascript.Data):
    pass


class azurerm_firewall(terrascript.Data):
    pass


class azurerm_firewall_policy(terrascript.Data):
    pass


class azurerm_function_app(terrascript.Data):
    pass


class azurerm_function_app_host_keys(terrascript.Data):
    pass


class azurerm_hdinsight_cluster(terrascript.Data):
    pass


class azurerm_healthcare_service(terrascript.Data):
    pass


class azurerm_image(terrascript.Data):
    pass


class azurerm_images(terrascript.Data):
    pass


class azurerm_iothub(terrascript.Data):
    pass


class azurerm_iothub_dps(terrascript.Data):
    pass


class azurerm_iothub_dps_shared_access_policy(terrascript.Data):
    pass


class azurerm_iothub_shared_access_policy(terrascript.Data):
    pass


class azurerm_ip_group(terrascript.Data):
    pass


class azurerm_key_vault(terrascript.Data):
    pass


class azurerm_key_vault_access_policy(terrascript.Data):
    pass


class azurerm_key_vault_certificate(terrascript.Data):
    pass


class azurerm_key_vault_certificate_data(terrascript.Data):
    pass


class azurerm_key_vault_certificate_issuer(terrascript.Data):
    pass


class azurerm_key_vault_key(terrascript.Data):
    pass


class azurerm_key_vault_managed_hardware_security_module(terrascript.Data):
    pass


class azurerm_key_vault_secret(terrascript.Data):
    pass


class azurerm_key_vault_secrets(terrascript.Data):
    pass


class azurerm_kubernetes_cluster(terrascript.Data):
    pass


class azurerm_kubernetes_cluster_node_pool(terrascript.Data):
    pass


class azurerm_kubernetes_service_versions(terrascript.Data):
    pass


class azurerm_kusto_cluster(terrascript.Data):
    pass


class azurerm_lb(terrascript.Data):
    pass


class azurerm_lb_backend_address_pool(terrascript.Data):
    pass


class azurerm_lb_rule(terrascript.Data):
    pass


class azurerm_local_network_gateway(terrascript.Data):
    pass


class azurerm_log_analytics_workspace(terrascript.Data):
    pass


class azurerm_logic_app_integration_account(terrascript.Data):
    pass


class azurerm_logic_app_workflow(terrascript.Data):
    pass


class azurerm_machine_learning_workspace(terrascript.Data):
    pass


class azurerm_maintenance_configuration(terrascript.Data):
    pass


class azurerm_managed_application_definition(terrascript.Data):
    pass


class azurerm_managed_disk(terrascript.Data):
    pass


class azurerm_management_group(terrascript.Data):
    pass


class azurerm_maps_account(terrascript.Data):
    pass


class azurerm_mariadb_server(terrascript.Data):
    pass


class azurerm_monitor_action_group(terrascript.Data):
    pass


class azurerm_monitor_diagnostic_categories(terrascript.Data):
    pass


class azurerm_monitor_log_profile(terrascript.Data):
    pass


class azurerm_monitor_scheduled_query_rules_alert(terrascript.Data):
    pass


class azurerm_monitor_scheduled_query_rules_log(terrascript.Data):
    pass


class azurerm_mssql_database(terrascript.Data):
    pass


class azurerm_mssql_elasticpool(terrascript.Data):
    pass


class azurerm_mssql_server(terrascript.Data):
    pass


class azurerm_mysql_server(terrascript.Data):
    pass


class azurerm_nat_gateway(terrascript.Data):
    pass


class azurerm_netapp_account(terrascript.Data):
    pass


class azurerm_netapp_pool(terrascript.Data):
    pass


class azurerm_netapp_snapshot(terrascript.Data):
    pass


class azurerm_netapp_volume(terrascript.Data):
    pass


class azurerm_network_ddos_protection_plan(terrascript.Data):
    pass


class azurerm_network_interface(terrascript.Data):
    pass


class azurerm_network_security_group(terrascript.Data):
    pass


class azurerm_network_service_tags(terrascript.Data):
    pass


class azurerm_network_watcher(terrascript.Data):
    pass


class azurerm_notification_hub(terrascript.Data):
    pass


class azurerm_notification_hub_namespace(terrascript.Data):
    pass


class azurerm_platform_image(terrascript.Data):
    pass


class azurerm_policy_definition(terrascript.Data):
    pass


class azurerm_policy_set_definition(terrascript.Data):
    pass


class azurerm_policy_virtual_machine_configuration_assignment(terrascript.Data):
    pass


class azurerm_postgresql_flexible_server(terrascript.Data):
    pass


class azurerm_postgresql_server(terrascript.Data):
    pass


class azurerm_private_dns_zone(terrascript.Data):
    pass


class azurerm_private_endpoint_connection(terrascript.Data):
    pass


class azurerm_private_link_service(terrascript.Data):
    pass


class azurerm_private_link_service_endpoint_connections(terrascript.Data):
    pass


class azurerm_proximity_placement_group(terrascript.Data):
    pass


class azurerm_public_ip(terrascript.Data):
    pass


class azurerm_public_ip_prefix(terrascript.Data):
    pass


class azurerm_public_ips(terrascript.Data):
    pass


class azurerm_recovery_services_vault(terrascript.Data):
    pass


class azurerm_redis_cache(terrascript.Data):
    pass


class azurerm_redis_enterprise_database(terrascript.Data):
    pass


class azurerm_resource_group(terrascript.Data):
    pass


class azurerm_resources(terrascript.Data):
    pass


class azurerm_role_definition(terrascript.Data):
    pass


class azurerm_route_filter(terrascript.Data):
    pass


class azurerm_route_table(terrascript.Data):
    pass


class azurerm_search_service(terrascript.Data):
    pass


class azurerm_sentinel_alert_rule(terrascript.Data):
    pass


class azurerm_sentinel_alert_rule_template(terrascript.Data):
    pass


class azurerm_servicebus_namespace(terrascript.Data):
    pass


class azurerm_servicebus_namespace_authorization_rule(terrascript.Data):
    pass


class azurerm_servicebus_namespace_disaster_recovery_config(terrascript.Data):
    pass


class azurerm_servicebus_queue(terrascript.Data):
    pass


class azurerm_servicebus_queue_authorization_rule(terrascript.Data):
    pass


class azurerm_servicebus_subscription(terrascript.Data):
    pass


class azurerm_servicebus_topic(terrascript.Data):
    pass


class azurerm_servicebus_topic_authorization_rule(terrascript.Data):
    pass


class azurerm_shared_image(terrascript.Data):
    pass


class azurerm_shared_image_gallery(terrascript.Data):
    pass


class azurerm_shared_image_version(terrascript.Data):
    pass


class azurerm_shared_image_versions(terrascript.Data):
    pass


class azurerm_signalr_service(terrascript.Data):
    pass


class azurerm_snapshot(terrascript.Data):
    pass


class azurerm_spatial_anchors_account(terrascript.Data):
    pass


class azurerm_spring_cloud_app(terrascript.Data):
    pass


class azurerm_spring_cloud_service(terrascript.Data):
    pass


class azurerm_sql_database(terrascript.Data):
    pass


class azurerm_sql_server(terrascript.Data):
    pass


class azurerm_ssh_public_key(terrascript.Data):
    pass


class azurerm_storage_account(terrascript.Data):
    pass


class azurerm_storage_account_blob_container_sas(terrascript.Data):
    pass


class azurerm_storage_account_sas(terrascript.Data):
    pass


class azurerm_storage_blob(terrascript.Data):
    pass


class azurerm_storage_container(terrascript.Data):
    pass


class azurerm_storage_encryption_scope(terrascript.Data):
    pass


class azurerm_storage_management_policy(terrascript.Data):
    pass


class azurerm_storage_share(terrascript.Data):
    pass


class azurerm_storage_sync(terrascript.Data):
    pass


class azurerm_storage_sync_group(terrascript.Data):
    pass


class azurerm_storage_table_entity(terrascript.Data):
    pass


class azurerm_stream_analytics_job(terrascript.Data):
    pass


class azurerm_subnet(terrascript.Data):
    pass


class azurerm_subscription(terrascript.Data):
    pass


class azurerm_subscriptions(terrascript.Data):
    pass


class azurerm_synapse_workspace(terrascript.Data):
    pass


class azurerm_template_spec_version(terrascript.Data):
    pass


class azurerm_traffic_manager_geographical_location(terrascript.Data):
    pass


class azurerm_traffic_manager_profile(terrascript.Data):
    pass


class azurerm_user_assigned_identity(terrascript.Data):
    pass


class azurerm_virtual_hub(terrascript.Data):
    pass


class azurerm_virtual_machine(terrascript.Data):
    pass


class azurerm_virtual_machine_scale_set(terrascript.Data):
    pass


class azurerm_virtual_network(terrascript.Data):
    pass


class azurerm_virtual_network_gateway(terrascript.Data):
    pass


class azurerm_virtual_network_gateway_connection(terrascript.Data):
    pass


class azurerm_virtual_wan(terrascript.Data):
    pass


class azurerm_vmware_private_cloud(terrascript.Data):
    pass


class azurerm_vpn_gateway(terrascript.Data):
    pass


class azurerm_web_application_firewall_policy(terrascript.Data):
    pass
