# terrascript/data/jeffwecan/pypi.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:49 UTC)
import terrascript


class pypi_package_file(terrascript.Data):
    pass


class pypi_requirements_file(terrascript.Data):
    pass


__all__ = [
    "pypi_package_file",
    "pypi_requirements_file",
]
