# terrascript/data/jeffwecan/teamcity.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:17 UTC)
import terrascript


class teamcity_agent_pool(terrascript.Data):
    pass


class teamcity_project(terrascript.Data):
    pass


__all__ = [
    "teamcity_agent_pool",
    "teamcity_project",
]
