# terrascript/resource/cappyzawa/artifactory.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:49 UTC)
import terrascript


class artifactory_access_token(terrascript.Resource):
    pass


class artifactory_api_key(terrascript.Resource):
    pass


class artifactory_certificate(terrascript.Resource):
    pass


class artifactory_group(terrascript.Resource):
    pass


class artifactory_local_repository(terrascript.Resource):
    pass


class artifactory_permission_target(terrascript.Resource):
    pass


class artifactory_permission_targets(terrascript.Resource):
    pass


class artifactory_remote_repository(terrascript.Resource):
    pass


class artifactory_replication_config(terrascript.Resource):
    pass


class artifactory_single_replication_config(terrascript.Resource):
    pass


class artifactory_user(terrascript.Resource):
    pass


class artifactory_virtual_repository(terrascript.Resource):
    pass


class artifactory_xray_policy(terrascript.Resource):
    pass


class artifactory_xray_watch(terrascript.Resource):
    pass

__all__ = [
    "artifactory_access_token",
    "artifactory_api_key",
    "artifactory_certificate",
    "artifactory_group",
    "artifactory_local_repository",
    "artifactory_permission_target",
    "artifactory_permission_targets",
    "artifactory_remote_repository",
    "artifactory_replication_config",
    "artifactory_single_replication_config",
    "artifactory_user",
    "artifactory_virtual_repository",
    "artifactory_xray_policy",
    "artifactory_xray_watch",
]
