# terrascript/resource/cappyzawa/concourse.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:12 UTC)
import terrascript


class concourse_team(terrascript.Resource):
    pass

__all__ = [
    "concourse_team",
]
