# terrascript/resource/paultyng/unifi.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:28 UTC)
import terrascript


class unifi_device(terrascript.Resource):
    pass


class unifi_dynamic_dns(terrascript.Resource):
    pass


class unifi_firewall_group(terrascript.Resource):
    pass


class unifi_firewall_rule(terrascript.Resource):
    pass


class unifi_network(terrascript.Resource):
    pass


class unifi_port_forward(terrascript.Resource):
    pass


class unifi_port_profile(terrascript.Resource):
    pass


class unifi_setting_mgmt(terrascript.Resource):
    pass


class unifi_site(terrascript.Resource):
    pass


class unifi_static_route(terrascript.Resource):
    pass


class unifi_user(terrascript.Resource):
    pass


class unifi_user_group(terrascript.Resource):
    pass


class unifi_wlan(terrascript.Resource):
    pass

__all__ = [
    "unifi_device",
    "unifi_dynamic_dns",
    "unifi_firewall_group",
    "unifi_firewall_rule",
    "unifi_network",
    "unifi_port_forward",
    "unifi_port_profile",
    "unifi_setting_mgmt",
    "unifi_site",
    "unifi_static_route",
    "unifi_user",
    "unifi_user_group",
    "unifi_wlan",
]
