# terrascript/data/splunk-terraform/signalfx.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:07 UTC)
import terrascript


class signalfx_aws_services(terrascript.Data):
    pass


class signalfx_azure_services(terrascript.Data):
    pass


class signalfx_dimension_values(terrascript.Data):
    pass


class signalfx_gcp_services(terrascript.Data):
    pass


class signalfx_pagerduty_integration(terrascript.Data):
    pass


__all__ = [
    "signalfx_aws_services",
    "signalfx_azure_services",
    "signalfx_dimension_values",
    "signalfx_gcp_services",
    "signalfx_pagerduty_integration",
]
