# terrascript/data/alertmixer/amixr.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:11:40 UTC)
import terrascript


class amixr_action(terrascript.Data):
    pass


class amixr_schedule(terrascript.Data):
    pass


class amixr_slack_channel(terrascript.Data):
    pass


class amixr_user(terrascript.Data):
    pass


class amixr_user_group(terrascript.Data):
    pass


__all__ = [
    "amixr_action",
    "amixr_schedule",
    "amixr_slack_channel",
    "amixr_user",
    "amixr_user_group",
]
