# terrascript/provider/NetApp/netapp_cloudmanager.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:21 UTC)

import terrascript

class netapp_cloudmanager(terrascript.Provider):
    '''Terraform provider to create NetAPP OCCM instances, CVO resources, volumes, snapshots, ... in Azure, AWS, GCP.
    
    '''
    __description__ = "Terraform provider to create NetAPP OCCM instances, CVO resources, volumes, snapshots, ... in Azure, AWS, GCP."
    __namespace__ = "NetApp"
    __name__ = "netapp-cloudmanager"
    __source__ = "https://github.com/NetApp/terraform-provider-netapp-cloudmanager"
    __version__ = "21.8.1"
    __published__ = "2021-08-23T21:57:21Z"
    __tier__ = "partner"
    

__all__ = ["netapp_cloudmanager"]
