# terrascript/provider/brightbox/brightbox.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:07 UTC)

import terrascript

class brightbox(terrascript.Provider):
    '''Terraform Brightbox Cloud provider
    
    '''
    __description__ = "Terraform Brightbox Cloud provider"
    __namespace__ = "brightbox"
    __name__ = "brightbox"
    __source__ = "https://github.com/brightbox/terraform-provider-brightbox"
    __version__ = "2.0.6"
    __published__ = "2021-07-23T10:47:35Z"
    __tier__ = "partner"
    

__all__ = ["brightbox"]
