# terrascript/provider/techBeck03/vsphere.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:31:01 UTC)

import terrascript


class vsphere(terrascript.Provider):
    """Terraform VMware vSphere provider"""

    __description__ = "Terraform VMware vSphere provider"
    __namespace__ = "techBeck03"
    __name__ = "vsphere"
    __source__ = "https://github.com/techBeck03/terraform-provider-vsphere"
    __version__ = "1.24.3-patch"
    __published__ = "2020-12-20T13:01:08Z"
    __tier__ = "community"


__all__ = ["vsphere"]
