# terrascript/provider/aequitas/transip.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:29:04 UTC)

import terrascript


class transip(terrascript.Provider):
    """Terraform provider to manage Transip resources"""

    __description__ = "Terraform provider to manage Transip resources"
    __namespace__ = "aequitas"
    __name__ = "transip"
    __source__ = "https://github.com/aequitas/terraform-provider-transip"
    __version__ = "0.1.11"
    __published__ = "2021-09-18T15:18:02Z"
    __tier__ = "community"


__all__ = ["transip"]
