# terrascript/njalla/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class njalla_record_a(terrascript.Resource):
    pass


class njalla_record_aaaa(terrascript.Resource):
    pass


class njalla_record_caa(terrascript.Resource):
    pass


class njalla_record_cname(terrascript.Resource):
    pass


class njalla_record_mx(terrascript.Resource):
    pass


class njalla_record_naptr(terrascript.Resource):
    pass


class njalla_record_ns(terrascript.Resource):
    pass


class njalla_record_ptr(terrascript.Resource):
    pass


class njalla_record_tlsa(terrascript.Resource):
    pass


class njalla_record_txt(terrascript.Resource):
    pass
