# terrascript/provider/ddelnano/mikrotik.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:18 UTC)

import terrascript

class mikrotik(terrascript.Provider):
    '''
    
    '''
    __description__ = ""
    __namespace__ = "ddelnano"
    __name__ = "mikrotik"
    __source__ = "https://github.com/ddelnano/terraform-provider-mikrotik"
    __version__ = "0.7.0"
    __published__ = "2021-07-28T03:06:02Z"
    __tier__ = "community"
    

__all__ = ["mikrotik"]
