# terrascript/mikrotik/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class mikrotik_bgp_instance(terrascript.Resource):
    pass


class mikrotik_bgp_peer(terrascript.Resource):
    pass


class mikrotik_dhcp_lease(terrascript.Resource):
    pass


class mikrotik_dns_record(terrascript.Resource):
    pass


class mikrotik_pool(terrascript.Resource):
    pass


class mikrotik_scheduler(terrascript.Resource):
    pass


class mikrotik_script(terrascript.Resource):
    pass
