# terrascript/data/gridscale/gridscale.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:43 UTC)
import terrascript


class gridscale_backup_list(terrascript.Data):
    pass


class gridscale_backupschedule(terrascript.Data):
    pass


class gridscale_firewall(terrascript.Data):
    pass


class gridscale_ipv4(terrascript.Data):
    pass


class gridscale_ipv6(terrascript.Data):
    pass


class gridscale_isoimage(terrascript.Data):
    pass


class gridscale_loadbalancer(terrascript.Data):
    pass


class gridscale_marketplace_application(terrascript.Data):
    pass


class gridscale_network(terrascript.Data):
    pass


class gridscale_object_storage_accesskey(terrascript.Data):
    pass


class gridscale_paas(terrascript.Data):
    pass


class gridscale_paas_securityzone(terrascript.Data):
    pass


class gridscale_public_network(terrascript.Data):
    pass


class gridscale_server(terrascript.Data):
    pass


class gridscale_snapshot(terrascript.Data):
    pass


class gridscale_snapshotschedule(terrascript.Data):
    pass


class gridscale_sshkey(terrascript.Data):
    pass


class gridscale_ssl_certificate(terrascript.Data):
    pass


class gridscale_storage(terrascript.Data):
    pass


class gridscale_template(terrascript.Data):
    pass


__all__ = [
    "gridscale_backup_list",
    "gridscale_backupschedule",
    "gridscale_firewall",
    "gridscale_ipv4",
    "gridscale_ipv6",
    "gridscale_isoimage",
    "gridscale_loadbalancer",
    "gridscale_marketplace_application",
    "gridscale_network",
    "gridscale_object_storage_accesskey",
    "gridscale_paas",
    "gridscale_paas_securityzone",
    "gridscale_public_network",
    "gridscale_server",
    "gridscale_snapshot",
    "gridscale_snapshotschedule",
    "gridscale_sshkey",
    "gridscale_ssl_certificate",
    "gridscale_storage",
    "gridscale_template",
]
