# terrascript/elasticsearch/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class elasticsearch_component_template(terrascript.Resource):
    pass


class elasticsearch_composable_index_template(terrascript.Resource):
    pass


class elasticsearch_destination(terrascript.Resource):
    pass


class elasticsearch_index(terrascript.Resource):
    pass


class elasticsearch_index_lifecycle_policy(terrascript.Resource):
    pass


class elasticsearch_index_template(terrascript.Resource):
    pass


class elasticsearch_ingest_pipeline(terrascript.Resource):
    pass


class elasticsearch_kibana_alert(terrascript.Resource):
    pass


class elasticsearch_kibana_object(terrascript.Resource):
    pass


class elasticsearch_monitor(terrascript.Resource):
    pass


class elasticsearch_opendistro_destination(terrascript.Resource):
    pass


class elasticsearch_opendistro_ism_policy(terrascript.Resource):
    pass


class elasticsearch_opendistro_ism_policy_mapping(terrascript.Resource):
    pass


class elasticsearch_opendistro_kibana_tenant(terrascript.Resource):
    pass


class elasticsearch_opendistro_monitor(terrascript.Resource):
    pass


class elasticsearch_opendistro_role(terrascript.Resource):
    pass


class elasticsearch_opendistro_roles_mapping(terrascript.Resource):
    pass


class elasticsearch_opendistro_user(terrascript.Resource):
    pass


class elasticsearch_snapshot_repository(terrascript.Resource):
    pass


class elasticsearch_watch(terrascript.Resource):
    pass


class elasticsearch_xpack_index_lifecycle_policy(terrascript.Resource):
    pass


class elasticsearch_xpack_license(terrascript.Resource):
    pass


class elasticsearch_xpack_role(terrascript.Resource):
    pass


class elasticsearch_xpack_role_mapping(terrascript.Resource):
    pass


class elasticsearch_xpack_snapshot_lifecycle_policy(terrascript.Resource):
    pass


class elasticsearch_xpack_user(terrascript.Resource):
    pass


class elasticsearch_xpack_watch(terrascript.Resource):
    pass
