# terrascript/resource/launchdarkly/launchdarkly.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:12 UTC)
import terrascript


class launchdarkly_access_token(terrascript.Resource):
    pass


class launchdarkly_custom_role(terrascript.Resource):
    pass


class launchdarkly_destination(terrascript.Resource):
    pass


class launchdarkly_environment(terrascript.Resource):
    pass


class launchdarkly_feature_flag(terrascript.Resource):
    pass


class launchdarkly_feature_flag_environment(terrascript.Resource):
    pass


class launchdarkly_project(terrascript.Resource):
    pass


class launchdarkly_segment(terrascript.Resource):
    pass


class launchdarkly_team_member(terrascript.Resource):
    pass


class launchdarkly_webhook(terrascript.Resource):
    pass

__all__ = [
    "launchdarkly_access_token",
    "launchdarkly_custom_role",
    "launchdarkly_destination",
    "launchdarkly_environment",
    "launchdarkly_feature_flag",
    "launchdarkly_feature_flag_environment",
    "launchdarkly_project",
    "launchdarkly_segment",
    "launchdarkly_team_member",
    "launchdarkly_webhook",
]
