# terrascript/provider/DTherHtun/idm.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:55 UTC)

import terrascript

class idm(terrascript.Provider):
    '''Terrafrom Provider for Redhat IDM
    
    '''
    __description__ = "Terrafrom Provider for Redhat IDM"
    __namespace__ = "DTherHtun"
    __name__ = "idm"
    __source__ = "https://github.com/DTherHtun/terraform-provider-idm"
    __version__ = "0.0.2"
    __published__ = "2020-06-11T08:01:15Z"
    __tier__ = "community"
    

__all__ = ["idm"]
