# terrascript/data/hashicorp/archive.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:11:52 UTC)
import terrascript


class archive_file(terrascript.Data):
    pass


__all__ = [
    "archive_file",
]
