# terrascript/data/hashicorp/googleworkspace.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:41 UTC)
import terrascript


class googleworkspace_chrome_policy_schema(terrascript.Data):
    pass


class googleworkspace_domain(terrascript.Data):
    pass


class googleworkspace_domain_alias(terrascript.Data):
    pass


class googleworkspace_group(terrascript.Data):
    pass


class googleworkspace_group_member(terrascript.Data):
    pass


class googleworkspace_group_settings(terrascript.Data):
    pass


class googleworkspace_org_unit(terrascript.Data):
    pass


class googleworkspace_privileges(terrascript.Data):
    pass


class googleworkspace_role(terrascript.Data):
    pass


class googleworkspace_schema(terrascript.Data):
    pass


class googleworkspace_user(terrascript.Data):
    pass


__all__ = [
    "googleworkspace_chrome_policy_schema",
    "googleworkspace_domain",
    "googleworkspace_domain_alias",
    "googleworkspace_group",
    "googleworkspace_group_member",
    "googleworkspace_group_settings",
    "googleworkspace_org_unit",
    "googleworkspace_privileges",
    "googleworkspace_role",
    "googleworkspace_schema",
    "googleworkspace_user",
]
