# terrascript/data/hashicorp/hcp.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:10 UTC)
import terrascript


class hcp_aws_network_peering(terrascript.Data):
    pass


class hcp_aws_transit_gateway_attachment(terrascript.Data):
    pass


class hcp_consul_agent_helm_config(terrascript.Data):
    pass


class hcp_consul_agent_kubernetes_secret(terrascript.Data):
    pass


class hcp_consul_cluster(terrascript.Data):
    pass


class hcp_consul_versions(terrascript.Data):
    pass


class hcp_hvn(terrascript.Data):
    pass


class hcp_hvn_peering_connection(terrascript.Data):
    pass


class hcp_hvn_route(terrascript.Data):
    pass


class hcp_packer_image(terrascript.Data):
    pass


class hcp_packer_image_iteration(terrascript.Data):
    pass


class hcp_packer_iteration(terrascript.Data):
    pass


class hcp_vault_cluster(terrascript.Data):
    pass


__all__ = [
    "hcp_aws_network_peering",
    "hcp_aws_transit_gateway_attachment",
    "hcp_consul_agent_helm_config",
    "hcp_consul_agent_kubernetes_secret",
    "hcp_consul_cluster",
    "hcp_consul_versions",
    "hcp_hvn",
    "hcp_hvn_peering_connection",
    "hcp_hvn_route",
    "hcp_packer_image",
    "hcp_packer_image_iteration",
    "hcp_packer_iteration",
    "hcp_vault_cluster",
]
