# terrascript/data/hashicorp/helm.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:50 UTC)
import terrascript


class helm_template(terrascript.Data):
    pass


__all__ = [
    "helm_template",
]
