# terrascript/provider/someara/tls.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:22 UTC)

import terrascript

class tls(terrascript.Provider):
    '''Terraform TLS provider
    
    '''
    __description__ = "Terraform TLS provider"
    __namespace__ = "someara"
    __name__ = "tls"
    __source__ = "https://github.com/someara/terraform-provider-tls"
    __version__ = "2.3.0-pre"
    __published__ = "2020-08-11T14:39:50Z"
    __tier__ = "community"
    

__all__ = ["tls"]
