# terrascript/provider/hashicorp/boundary.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:38 UTC)

import terrascript


class boundary(terrascript.Provider):
    """terraform-provider-boundary"""

    __description__ = "terraform-provider-boundary"
    __namespace__ = "hashicorp"
    __name__ = "boundary"
    __source__ = "https://github.com/hashicorp/terraform-provider-boundary"
    __version__ = "1.0.5"
    __published__ = "2021-09-09T15:29:12Z"
    __tier__ = "official"


__all__ = ["boundary"]
