# terrascript/provider/hashicorp/cloudinit.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:11 UTC)

import terrascript

class cloudinit(terrascript.Provider):
    '''terraform-provider-cloudinit
    
    '''
    __description__ = "terraform-provider-cloudinit"
    __namespace__ = "hashicorp"
    __name__ = "cloudinit"
    __source__ = "https://github.com/hashicorp/terraform-provider-cloudinit"
    __version__ = "2.2.0"
    __published__ = "2021-02-19T13:12:46Z"
    __tier__ = "official"
    

__all__ = ["cloudinit"]
