# terrascript/provider/hashicorp/external.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:16:09 UTC)

import terrascript


class external(terrascript.Provider):
    """terraform-provider-external"""

    __description__ = "terraform-provider-external"
    __namespace__ = "hashicorp"
    __name__ = "external"
    __source__ = "https://github.com/hashicorp/terraform-provider-external"
    __version__ = "2.1.0"
    __published__ = "2021-02-19T15:40:26Z"
    __tier__ = "official"


__all__ = ["external"]
