# terrascript/provider/hashicorp/google.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:17:10 UTC)

import terrascript


class google(terrascript.Provider):
    """terraform-provider-google"""

    __description__ = "terraform-provider-google"
    __namespace__ = "hashicorp"
    __name__ = "google"
    __source__ = "https://github.com/hashicorp/terraform-provider-google"
    __version__ = "3.85.0"
    __published__ = "2021-09-20T19:59:25Z"
    __tier__ = "official"


__all__ = ["google"]
