# terrascript/provider/hashicorp/hcs.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:13 UTC)

import terrascript


class hcs(terrascript.Provider):
    """terraform-provider-hcs"""

    __description__ = "terraform-provider-hcs"
    __namespace__ = "hashicorp"
    __name__ = "hcs"
    __source__ = "https://github.com/hashicorp/terraform-provider-hcs"
    __version__ = "0.5.0"
    __published__ = "2021-09-22T20:59:45Z"
    __tier__ = "official"


__all__ = ["hcs"]
