# terrascript/provider/hashicorp/kubernetes_alpha.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:11 UTC)

import terrascript

class kubernetes_alpha(terrascript.Provider):
    '''terraform-provider-kubernetes-alpha
    
    '''
    __description__ = "terraform-provider-kubernetes-alpha"
    __namespace__ = "hashicorp"
    __name__ = "kubernetes-alpha"
    __source__ = "https://github.com/hashicorp/terraform-provider-kubernetes-alpha"
    __version__ = "0.6.0"
    __published__ = "2021-08-04T18:31:30Z"
    __tier__ = "official"
    

__all__ = ["kubernetes_alpha"]
