# terrascript/provider/hashicorp/local.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:15 UTC)

import terrascript

class local(terrascript.Provider):
    '''terraform-provider-local
    
    '''
    __description__ = "terraform-provider-local"
    __namespace__ = "hashicorp"
    __name__ = "local"
    __source__ = "https://github.com/hashicorp/terraform-provider-local"
    __version__ = "2.1.0"
    __published__ = "2021-02-19T15:44:35Z"
    __tier__ = "official"
    

__all__ = ["local"]
