# terrascript/provider/hashicorp/template.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:28:21 UTC)

import terrascript


class template(terrascript.Provider):
    """terraform-provider-template"""

    __description__ = "terraform-provider-template"
    __namespace__ = "hashicorp"
    __name__ = "template"
    __source__ = "https://github.com/hashicorp/terraform-provider-template"
    __version__ = "2.2.0"
    __published__ = "2020-10-08T16:16:33Z"
    __tier__ = "official"


__all__ = ["template"]
