# terrascript/provider/hashicorp/time.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:20 UTC)

import terrascript

class time(terrascript.Provider):
    '''terraform-provider-time
    
    '''
    __description__ = "terraform-provider-time"
    __namespace__ = "hashicorp"
    __name__ = "time"
    __source__ = "https://github.com/hashicorp/terraform-provider-time"
    __version__ = "0.7.2"
    __published__ = "2021-07-01T17:40:41Z"
    __tier__ = "official"
    

__all__ = ["time"]
