# terrascript/provider/terra-farm/virtualbox.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:34 UTC)

import terrascript

class virtualbox(terrascript.Provider):
    '''VirtualBox provider for Terraform
    
    '''
    __description__ = "VirtualBox provider for Terraform"
    __namespace__ = "terra-farm"
    __name__ = "virtualbox"
    __source__ = "https://github.com/terra-farm/terraform-provider-virtualbox"
    __version__ = "0.2.1-alpha.1"
    __published__ = "2021-06-10T11:06:08Z"
    __tier__ = "community"
    

__all__ = ["virtualbox"]
