# terrascript/provider/terra-farm/xenorchestra.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:40 UTC)

import terrascript

class xenorchestra(terrascript.Provider):
    '''Xen Orchestra provider for Terraform
    
    '''
    __description__ = "Xen Orchestra provider for Terraform"
    __namespace__ = "terra-farm"
    __name__ = "xenorchestra"
    __source__ = "https://github.com/terra-farm/terraform-provider-xenorchestra"
    __version__ = "0.21.0"
    __published__ = "2021-07-30T01:18:46Z"
    __tier__ = "community"
    

__all__ = ["xenorchestra"]
