# terrascript/xenorchestra/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class xenorchestra_cloud_config(terrascript.Data):
    pass


class xenorchestra_host(terrascript.Data):
    pass


class xenorchestra_hosts(terrascript.Data):
    pass


class xenorchestra_network(terrascript.Data):
    pass


class xenorchestra_pif(terrascript.Data):
    pass


class xenorchestra_pool(terrascript.Data):
    pass


class xenorchestra_resource_set(terrascript.Data):
    pass


class xenorchestra_sr(terrascript.Data):
    pass


class xenorchestra_template(terrascript.Data):
    pass


class xenorchestra_user(terrascript.Data):
    pass


class xenorchestra_vdi(terrascript.Data):
    pass


class xenorchestra_vms(terrascript.Data):
    pass
