# terrascript/provider/DataDog/datadog.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:17 UTC)

import terrascript

class datadog(terrascript.Provider):
    '''Terraform Datadog provider
    
    '''
    __description__ = "Terraform Datadog provider"
    __namespace__ = "DataDog"
    __name__ = "datadog"
    __source__ = "https://github.com/DataDog/terraform-provider-datadog"
    __version__ = "3.2.0"
    __published__ = "2021-07-14T13:52:46Z"
    __tier__ = "partner"
    

__all__ = ["datadog"]
