from terrascript import _data
class openstack_blockstorage_availability_zones_v3(_data): pass
blockstorage_availability_zones_v3 = openstack_blockstorage_availability_zones_v3

class openstack_blockstorage_snapshot_v2(_data): pass
blockstorage_snapshot_v2 = openstack_blockstorage_snapshot_v2

class openstack_blockstorage_snapshot_v3(_data): pass
blockstorage_snapshot_v3 = openstack_blockstorage_snapshot_v3

class openstack_compute_availability_zones_v2(_data): pass
compute_availability_zones_v2 = openstack_compute_availability_zones_v2

class openstack_compute_flavor_v2(_data): pass
compute_flavor_v2 = openstack_compute_flavor_v2

class openstack_compute_keypair_v2(_data): pass
compute_keypair_v2 = openstack_compute_keypair_v2

class openstack_containerinfra_clustertemplate_v1(_data): pass
containerinfra_clustertemplate_v1 = openstack_containerinfra_clustertemplate_v1

class openstack_containerinfra_cluster_v1(_data): pass
containerinfra_cluster_v1 = openstack_containerinfra_cluster_v1

class openstack_dns_zone_v2(_data): pass
dns_zone_v2 = openstack_dns_zone_v2

class openstack_fw_policy_v1(_data): pass
fw_policy_v1 = openstack_fw_policy_v1

class openstack_identity_role_v3(_data): pass
identity_role_v3 = openstack_identity_role_v3

class openstack_identity_project_v3(_data): pass
identity_project_v3 = openstack_identity_project_v3

class openstack_identity_user_v3(_data): pass
identity_user_v3 = openstack_identity_user_v3

class openstack_identity_auth_scope_v3(_data): pass
identity_auth_scope_v3 = openstack_identity_auth_scope_v3

class openstack_identity_endpoint_v3(_data): pass
identity_endpoint_v3 = openstack_identity_endpoint_v3

class openstack_identity_group_v3(_data): pass
identity_group_v3 = openstack_identity_group_v3

class openstack_images_image_v2(_data): pass
images_image_v2 = openstack_images_image_v2

class openstack_networking_addressscope_v2(_data): pass
networking_addressscope_v2 = openstack_networking_addressscope_v2

class openstack_networking_network_v2(_data): pass
networking_network_v2 = openstack_networking_network_v2

class openstack_networking_subnet_v2(_data): pass
networking_subnet_v2 = openstack_networking_subnet_v2

class openstack_networking_secgroup_v2(_data): pass
networking_secgroup_v2 = openstack_networking_secgroup_v2

class openstack_networking_subnetpool_v2(_data): pass
networking_subnetpool_v2 = openstack_networking_subnetpool_v2

class openstack_networking_floatingip_v2(_data): pass
networking_floatingip_v2 = openstack_networking_floatingip_v2

class openstack_networking_router_v2(_data): pass
networking_router_v2 = openstack_networking_router_v2

class openstack_networking_port_v2(_data): pass
networking_port_v2 = openstack_networking_port_v2

class openstack_networking_port_ids_v2(_data): pass
networking_port_ids_v2 = openstack_networking_port_ids_v2

class openstack_networking_trunk_v2(_data): pass
networking_trunk_v2 = openstack_networking_trunk_v2

class openstack_sharedfilesystem_availability_zones_v2(_data): pass
sharedfilesystem_availability_zones_v2 = openstack_sharedfilesystem_availability_zones_v2

class openstack_sharedfilesystem_sharenetwork_v2(_data): pass
sharedfilesystem_sharenetwork_v2 = openstack_sharedfilesystem_sharenetwork_v2

class openstack_sharedfilesystem_share_v2(_data): pass
sharedfilesystem_share_v2 = openstack_sharedfilesystem_share_v2

class openstack_sharedfilesystem_snapshot_v2(_data): pass
sharedfilesystem_snapshot_v2 = openstack_sharedfilesystem_snapshot_v2

