# terrascript/hdns/r.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class hdns_record(terrascript.Resource):
    pass


class hdns_zone(terrascript.Resource):
    pass
