# terrascript/resource/transloadit/transloadit.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:24 UTC)
import terrascript


class transloadit_template(terrascript.Resource):
    pass

__all__ = [
    "transloadit_template",
]
