# terrascript/resource/chanzuckerberg/okta.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:32 UTC)
import terrascript


class okta_admin_role_targets(terrascript.Resource):
    pass


class okta_app_auto_login(terrascript.Resource):
    pass


class okta_app_basic_auth(terrascript.Resource):
    pass


class okta_app_bookmark(terrascript.Resource):
    pass


class okta_app_group_assignments(terrascript.Resource):
    pass


class okta_app_oauth(terrascript.Resource):
    pass


class okta_app_oauth_api_scope(terrascript.Resource):
    pass


class okta_app_oauth_redirect_uri(terrascript.Resource):
    pass


class okta_app_saml(terrascript.Resource):
    pass


class okta_app_secure_password_store(terrascript.Resource):
    pass


class okta_app_swa(terrascript.Resource):
    pass


class okta_app_three_field(terrascript.Resource):
    pass


class okta_app_user(terrascript.Resource):
    pass


class okta_app_user_base_schema(terrascript.Resource):
    pass


class okta_app_user_schema(terrascript.Resource):
    pass


class okta_auth_server(terrascript.Resource):
    pass


class okta_auth_server_claim(terrascript.Resource):
    pass


class okta_auth_server_claim_default(terrascript.Resource):
    pass


class okta_auth_server_default(terrascript.Resource):
    pass


class okta_auth_server_policy(terrascript.Resource):
    pass


class okta_auth_server_policy_rule(terrascript.Resource):
    pass


class okta_auth_server_scope(terrascript.Resource):
    pass


class okta_auto_login_app(terrascript.Resource):
    pass


class okta_bookmark_app(terrascript.Resource):
    pass


class okta_event_hook(terrascript.Resource):
    pass


class okta_factor(terrascript.Resource):
    pass


class okta_group(terrascript.Resource):
    pass


class okta_group_membership(terrascript.Resource):
    pass


class okta_group_role(terrascript.Resource):
    pass


class okta_group_roles(terrascript.Resource):
    pass


class okta_group_rule(terrascript.Resource):
    pass


class okta_idp(terrascript.Resource):
    pass


class okta_idp_oidc(terrascript.Resource):
    pass


class okta_idp_saml(terrascript.Resource):
    pass


class okta_idp_saml_key(terrascript.Resource):
    pass


class okta_idp_social(terrascript.Resource):
    pass


class okta_inline_hook(terrascript.Resource):
    pass


class okta_mfa_policy(terrascript.Resource):
    pass


class okta_mfa_policy_rule(terrascript.Resource):
    pass


class okta_network_zone(terrascript.Resource):
    pass


class okta_oauth_app(terrascript.Resource):
    pass


class okta_oauth_app_redirect_uri(terrascript.Resource):
    pass


class okta_password_policy(terrascript.Resource):
    pass


class okta_password_policy_rule(terrascript.Resource):
    pass


class okta_policy_mfa(terrascript.Resource):
    pass


class okta_policy_mfa_default(terrascript.Resource):
    pass


class okta_policy_password(terrascript.Resource):
    pass


class okta_policy_password_default(terrascript.Resource):
    pass


class okta_policy_rule_idp_discovery(terrascript.Resource):
    pass


class okta_policy_rule_mfa(terrascript.Resource):
    pass


class okta_policy_rule_password(terrascript.Resource):
    pass


class okta_policy_rule_signon(terrascript.Resource):
    pass


class okta_policy_signon(terrascript.Resource):
    pass


class okta_profile_mapping(terrascript.Resource):
    pass


class okta_saml_app(terrascript.Resource):
    pass


class okta_saml_idp(terrascript.Resource):
    pass


class okta_saml_idp_signing_key(terrascript.Resource):
    pass


class okta_secure_password_store_app(terrascript.Resource):
    pass


class okta_signon_policy(terrascript.Resource):
    pass


class okta_signon_policy_rule(terrascript.Resource):
    pass


class okta_social_idp(terrascript.Resource):
    pass


class okta_swa_app(terrascript.Resource):
    pass


class okta_template_email(terrascript.Resource):
    pass


class okta_template_sms(terrascript.Resource):
    pass


class okta_three_field_app(terrascript.Resource):
    pass


class okta_trusted_origin(terrascript.Resource):
    pass


class okta_user(terrascript.Resource):
    pass


class okta_user_base_schema(terrascript.Resource):
    pass


class okta_user_schema(terrascript.Resource):
    pass


class okta_user_type(terrascript.Resource):
    pass

__all__ = [
    "okta_admin_role_targets",
    "okta_app_auto_login",
    "okta_app_basic_auth",
    "okta_app_bookmark",
    "okta_app_group_assignments",
    "okta_app_oauth",
    "okta_app_oauth_api_scope",
    "okta_app_oauth_redirect_uri",
    "okta_app_saml",
    "okta_app_secure_password_store",
    "okta_app_swa",
    "okta_app_three_field",
    "okta_app_user",
    "okta_app_user_base_schema",
    "okta_app_user_schema",
    "okta_auth_server",
    "okta_auth_server_claim",
    "okta_auth_server_claim_default",
    "okta_auth_server_default",
    "okta_auth_server_policy",
    "okta_auth_server_policy_rule",
    "okta_auth_server_scope",
    "okta_auto_login_app",
    "okta_bookmark_app",
    "okta_event_hook",
    "okta_factor",
    "okta_group",
    "okta_group_membership",
    "okta_group_role",
    "okta_group_roles",
    "okta_group_rule",
    "okta_idp",
    "okta_idp_oidc",
    "okta_idp_saml",
    "okta_idp_saml_key",
    "okta_idp_social",
    "okta_inline_hook",
    "okta_mfa_policy",
    "okta_mfa_policy_rule",
    "okta_network_zone",
    "okta_oauth_app",
    "okta_oauth_app_redirect_uri",
    "okta_password_policy",
    "okta_password_policy_rule",
    "okta_policy_mfa",
    "okta_policy_mfa_default",
    "okta_policy_password",
    "okta_policy_password_default",
    "okta_policy_rule_idp_discovery",
    "okta_policy_rule_mfa",
    "okta_policy_rule_password",
    "okta_policy_rule_signon",
    "okta_policy_signon",
    "okta_profile_mapping",
    "okta_saml_app",
    "okta_saml_idp",
    "okta_saml_idp_signing_key",
    "okta_secure_password_store_app",
    "okta_signon_policy",
    "okta_signon_policy_rule",
    "okta_social_idp",
    "okta_swa_app",
    "okta_template_email",
    "okta_template_sms",
    "okta_three_field_app",
    "okta_trusted_origin",
    "okta_user",
    "okta_user_base_schema",
    "okta_user_schema",
    "okta_user_type",
]
