# terrascript/data/nrkno/lastpass.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:12 UTC)
import terrascript


class lastpass_secret(terrascript.Data):
    pass


__all__ = [
    "lastpass_secret",
]
