# terrascript/data/heroku/heroku.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:37 UTC)
import terrascript


class heroku_addon(terrascript.Data):
    pass


class heroku_app(terrascript.Data):
    pass


class heroku_pipeline(terrascript.Data):
    pass


class heroku_space(terrascript.Data):
    pass


class heroku_space_peering_info(terrascript.Data):
    pass


class heroku_team(terrascript.Data):
    pass


class heroku_team_members(terrascript.Data):
    pass


__all__ = [
    "heroku_addon",
    "heroku_app",
    "heroku_pipeline",
    "heroku_space",
    "heroku_space_peering_info",
    "heroku_team",
    "heroku_team_members",
]
