# terrascript/provider/davidji99/asana.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:50 UTC)

import terrascript

class asana(terrascript.Provider):
    '''Terraform Asana Provider
    
    '''
    __description__ = "Terraform Asana Provider"
    __namespace__ = "davidji99"
    __name__ = "asana"
    __source__ = "https://github.com/davidji99/terraform-provider-asana"
    __version__ = "0.1.2"
    __published__ = "2021-02-25T10:26:57Z"
    __tier__ = "community"
    

__all__ = ["asana"]
