# terrascript/provider/davidji99/sendgrid.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:00 UTC)

import terrascript

class sendgrid(terrascript.Provider):
    '''Terraform Provider Sendgrid
    
    '''
    __description__ = "Terraform Provider Sendgrid"
    __namespace__ = "davidji99"
    __name__ = "sendgrid"
    __source__ = "https://github.com/davidji99/terraform-provider-sendgrid"
    __version__ = "0.1.1"
    __published__ = "2021-02-25T07:53:30Z"
    __tier__ = "community"
    

__all__ = ["sendgrid"]
