# terrascript/data/F5Networks/bigip.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:05 UTC)
import terrascript


class bigip_ltm_datagroup(terrascript.Data):
    pass


class bigip_ltm_irule(terrascript.Data):
    pass


class bigip_ltm_monitor(terrascript.Data):
    pass


class bigip_ltm_node(terrascript.Data):
    pass


class bigip_ltm_pool(terrascript.Data):
    pass


class bigip_ssl_certificate(terrascript.Data):
    pass


class bigip_vwan_config(terrascript.Data):
    pass


__all__ = [
    "bigip_ltm_datagroup",
    "bigip_ltm_irule",
    "bigip_ltm_monitor",
    "bigip_ltm_node",
    "bigip_ltm_pool",
    "bigip_ssl_certificate",
    "bigip_vwan_config",
]
