# terrascript/provider/invidian/libvirt.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:21:04 UTC)

import terrascript


class libvirt(terrascript.Provider):
    """Terraform provider to provision infrastructure with Linux's KVM using libvirt"""

    __description__ = (
        "Terraform provider to provision infrastructure with Linux's KVM using libvirt"
    )
    __namespace__ = "invidian"
    __name__ = "libvirt"
    __source__ = "https://github.com/invidian/terraform-provider-libvirt"
    __version__ = "0.6.10-rc1"
    __published__ = "2021-07-02T11:53:57Z"
    __tier__ = "community"


__all__ = ["libvirt"]
