# terrascript/provider/invidian/tls.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:28:50 UTC)

import terrascript


class tls(terrascript.Provider):
    """Terraform TLS provider"""

    __description__ = "Terraform TLS provider"
    __namespace__ = "invidian"
    __name__ = "tls"
    __source__ = "https://github.com/invidian/terraform-provider-tls"
    __version__ = "2.2.1"
    __published__ = "2020-08-21T15:10:19Z"
    __tier__ = "community"


__all__ = ["tls"]
