# terrascript/resource/philips-software/hsdp.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:54 UTC)
import terrascript


class hsdp_cdl_data_type_definition(terrascript.Resource):
    pass


class hsdp_cdl_export_route(terrascript.Resource):
    pass


class hsdp_cdl_label_definition(terrascript.Resource):
    pass


class hsdp_cdl_research_study(terrascript.Resource):
    pass


class hsdp_cdr_org(terrascript.Resource):
    pass


class hsdp_cdr_subscription(terrascript.Resource):
    pass


class hsdp_container_host(terrascript.Resource):
    pass


class hsdp_container_host_exec(terrascript.Resource):
    pass


class hsdp_dicom_gateway_config(terrascript.Resource):
    pass


class hsdp_dicom_object_store(terrascript.Resource):
    pass


class hsdp_dicom_remote_node(terrascript.Resource):
    pass


class hsdp_dicom_repository(terrascript.Resource):
    pass


class hsdp_dicom_store_config(terrascript.Resource):
    pass


class hsdp_function(terrascript.Resource):
    pass


class hsdp_iam_application(terrascript.Resource):
    pass


class hsdp_iam_client(terrascript.Resource):
    pass


class hsdp_iam_email_template(terrascript.Resource):
    pass


class hsdp_iam_group(terrascript.Resource):
    pass


class hsdp_iam_mfa_policy(terrascript.Resource):
    pass


class hsdp_iam_org(terrascript.Resource):
    pass


class hsdp_iam_password_policy(terrascript.Resource):
    pass


class hsdp_iam_proposition(terrascript.Resource):
    pass


class hsdp_iam_role(terrascript.Resource):
    pass


class hsdp_iam_service(terrascript.Resource):
    pass


class hsdp_iam_user(terrascript.Resource):
    pass


class hsdp_metrics_autoscaler(terrascript.Resource):
    pass


class hsdp_notification_producer(terrascript.Resource):
    pass


class hsdp_notification_subscriber(terrascript.Resource):
    pass


class hsdp_notification_subscription(terrascript.Resource):
    pass


class hsdp_notification_topic(terrascript.Resource):
    pass


class hsdp_pki_cert(terrascript.Resource):
    pass


class hsdp_pki_tenant(terrascript.Resource):
    pass


class hsdp_s3creds_policy(terrascript.Resource):
    pass


class hsdp_stl_app(terrascript.Resource):
    pass


class hsdp_stl_config(terrascript.Resource):
    pass


class hsdp_stl_custom_cert(terrascript.Resource):
    pass


class hsdp_stl_sync(terrascript.Resource):
    pass

__all__ = [
    "hsdp_cdl_data_type_definition",
    "hsdp_cdl_export_route",
    "hsdp_cdl_label_definition",
    "hsdp_cdl_research_study",
    "hsdp_cdr_org",
    "hsdp_cdr_subscription",
    "hsdp_container_host",
    "hsdp_container_host_exec",
    "hsdp_dicom_gateway_config",
    "hsdp_dicom_object_store",
    "hsdp_dicom_remote_node",
    "hsdp_dicom_repository",
    "hsdp_dicom_store_config",
    "hsdp_function",
    "hsdp_iam_application",
    "hsdp_iam_client",
    "hsdp_iam_email_template",
    "hsdp_iam_group",
    "hsdp_iam_mfa_policy",
    "hsdp_iam_org",
    "hsdp_iam_password_policy",
    "hsdp_iam_proposition",
    "hsdp_iam_role",
    "hsdp_iam_service",
    "hsdp_iam_user",
    "hsdp_metrics_autoscaler",
    "hsdp_notification_producer",
    "hsdp_notification_subscriber",
    "hsdp_notification_subscription",
    "hsdp_notification_topic",
    "hsdp_pki_cert",
    "hsdp_pki_tenant",
    "hsdp_s3creds_policy",
    "hsdp_stl_app",
    "hsdp_stl_config",
    "hsdp_stl_custom_cert",
    "hsdp_stl_sync",
]
