# terrascript/akamai/r.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class akamai_appsec_activations(terrascript.Resource):
    pass


class akamai_appsec_advanced_settings_logging(terrascript.Resource):
    pass


class akamai_appsec_advanced_settings_pragma_header(terrascript.Resource):
    pass


class akamai_appsec_advanced_settings_prefetch(terrascript.Resource):
    pass


class akamai_appsec_api_constraints_protection(terrascript.Resource):
    pass


class akamai_appsec_api_request_constraints(terrascript.Resource):
    pass


class akamai_appsec_attack_group(terrascript.Resource):
    pass


class akamai_appsec_bypass_network_lists(terrascript.Resource):
    pass


class akamai_appsec_configuration(terrascript.Resource):
    pass


class akamai_appsec_configuration_rename(terrascript.Resource):
    pass


class akamai_appsec_custom_deny(terrascript.Resource):
    pass


class akamai_appsec_custom_rule(terrascript.Resource):
    pass


class akamai_appsec_custom_rule_action(terrascript.Resource):
    pass


class akamai_appsec_eval(terrascript.Resource):
    pass


class akamai_appsec_eval_group(terrascript.Resource):
    pass


class akamai_appsec_eval_hostnames(terrascript.Resource):
    pass


class akamai_appsec_eval_protect_host(terrascript.Resource):
    pass


class akamai_appsec_eval_rule(terrascript.Resource):
    pass


class akamai_appsec_ip_geo(terrascript.Resource):
    pass


class akamai_appsec_ip_geo_protection(terrascript.Resource):
    pass


class akamai_appsec_match_target(terrascript.Resource):
    pass


class akamai_appsec_match_target_sequence(terrascript.Resource):
    pass


class akamai_appsec_penalty_box(terrascript.Resource):
    pass


class akamai_appsec_rate_policy(terrascript.Resource):
    pass


class akamai_appsec_rate_policy_action(terrascript.Resource):
    pass


class akamai_appsec_rate_protection(terrascript.Resource):
    pass


class akamai_appsec_reputation_profile(terrascript.Resource):
    pass


class akamai_appsec_reputation_profile_action(terrascript.Resource):
    pass


class akamai_appsec_reputation_profile_analysis(terrascript.Resource):
    pass


class akamai_appsec_reputation_protection(terrascript.Resource):
    pass


class akamai_appsec_rule(terrascript.Resource):
    pass


class akamai_appsec_rule_upgrade(terrascript.Resource):
    pass


class akamai_appsec_security_policy(terrascript.Resource):
    pass


class akamai_appsec_security_policy_rename(terrascript.Resource):
    pass


class akamai_appsec_selected_hostnames(terrascript.Resource):
    pass


class akamai_appsec_siem_settings(terrascript.Resource):
    pass


class akamai_appsec_slow_post(terrascript.Resource):
    pass


class akamai_appsec_slowpost_protection(terrascript.Resource):
    pass


class akamai_appsec_threat_intel(terrascript.Resource):
    pass


class akamai_appsec_version_notes(terrascript.Resource):
    pass


class akamai_appsec_waf_mode(terrascript.Resource):
    pass


class akamai_appsec_waf_protection(terrascript.Resource):
    pass


class akamai_appsec_wap_selected_hostnames(terrascript.Resource):
    pass


class akamai_cp_code(terrascript.Resource):
    pass


class akamai_cps_dv_enrollment(terrascript.Resource):
    pass


class akamai_cps_dv_validation(terrascript.Resource):
    pass


class akamai_dns_record(terrascript.Resource):
    pass


class akamai_dns_zone(terrascript.Resource):
    pass


class akamai_edge_hostname(terrascript.Resource):
    pass


class akamai_gtm_asmap(terrascript.Resource):
    pass


class akamai_gtm_cidrmap(terrascript.Resource):
    pass


class akamai_gtm_datacenter(terrascript.Resource):
    pass


class akamai_gtm_domain(terrascript.Resource):
    pass


class akamai_gtm_geomap(terrascript.Resource):
    pass


class akamai_gtm_property(terrascript.Resource):
    pass


class akamai_gtm_resource(terrascript.Resource):
    pass


class akamai_iam_user(terrascript.Resource):
    pass


class akamai_networklist_activations(terrascript.Resource):
    pass


class akamai_networklist_description(terrascript.Resource):
    pass


class akamai_networklist_network_list(terrascript.Resource):
    pass


class akamai_networklist_subscription(terrascript.Resource):
    pass


class akamai_property(terrascript.Resource):
    pass


class akamai_property_activation(terrascript.Resource):
    pass


class akamai_property_variables(terrascript.Resource):
    pass
