# terrascript/exasol/d.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)
import terrascript


class exasol_connection(terrascript.Data):
    pass


class exasol_physical_schema(terrascript.Data):
    pass


class exasol_role(terrascript.Data):
    pass


class exasol_table(terrascript.Data):
    pass


class exasol_view(terrascript.Data):
    pass
