# terrascript/resource/nauxliu/cronitor.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:15 UTC)
import terrascript


class cronitor_heartbeat_monitor(terrascript.Resource):
    pass

__all__ = [
    "cronitor_heartbeat_monitor",
]
