# terrascript/provider/SumoLogic/sumologic.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:28:04 UTC)

import terrascript


class sumologic(terrascript.Provider):
    """Terraform provider for Sumo Logic"""

    __description__ = "Terraform provider for Sumo Logic"
    __namespace__ = "SumoLogic"
    __name__ = "sumologic"
    __source__ = "https://github.com/SumoLogic/terraform-provider-sumologic"
    __version__ = "2.10.0"
    __published__ = "2021-09-22T22:04:13Z"
    __tier__ = "partner"


__all__ = ["sumologic"]
