# terrascript/resource/mumoshu/eksctl.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:15:43 UTC)
import terrascript


class eksctl_cluster(terrascript.Resource):
    pass


class eksctl_courier_alb(terrascript.Resource):
    pass


class eksctl_courier_route53_record(terrascript.Resource):
    pass


class eksctl_iamserviceaccount(terrascript.Resource):
    pass


class eksctl_nodegroup(terrascript.Resource):
    pass


__all__ = [
    "eksctl_cluster",
    "eksctl_courier_alb",
    "eksctl_courier_route53_record",
    "eksctl_iamserviceaccount",
    "eksctl_nodegroup",
]
