# terrascript/resource/mumoshu/helmfile.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:51 UTC)
import terrascript


class helmfile_embedding_example(terrascript.Resource):
    pass


class helmfile_release(terrascript.Resource):
    pass


class helmfile_release_set(terrascript.Resource):
    pass

__all__ = [
    "helmfile_embedding_example",
    "helmfile_release",
    "helmfile_release_set",
]
