# terrascript/pingaccess/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class pingaccess_acme_default(terrascript.Data):
    pass


class pingaccess_certificate(terrascript.Data):
    pass


class pingaccess_keypair(terrascript.Data):
    pass


class pingaccess_keypair_csr(terrascript.Data):
    pass


class pingaccess_pingfederate_runtime_metadata(terrascript.Data):
    pass


class pingaccess_trusted_certificate_group(terrascript.Data):
    pass
