# terrascript/provider/apparentlymart/testing.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:19 UTC)

import terrascript

class testing(terrascript.Provider):
    '''An experimental Terraform provider to assist in writing tests for Terraform modules
    
    '''
    __description__ = "An experimental Terraform provider to assist in writing tests for Terraform modules"
    __namespace__ = "apparentlymart"
    __name__ = "testing"
    __source__ = "https://github.com/apparentlymart/terraform-provider-testing"
    __version__ = "0.0.2"
    __published__ = "2020-06-04T17:02:47Z"
    __tier__ = "community"
    

__all__ = ["testing"]
