# terrascript/resource/akamai.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:31:41 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.akamai
#
# instead of
#
#   >>> import terrascript.resource.akamai.akamai
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.akamai.akamai import *