# terrascript/resource/azuread.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:12:52 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.azuread
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.azuread
#
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.azuread import *
