# terrascript/resource/brightbox.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:13:43 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.brightbox
#
# instead of
#
#   >>> import terrascript.resource.brightbox.brightbox
#
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.brightbox.brightbox import *
