# terrascript/resource/consul.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:14 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.consul
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.consul
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.consul import *