# terrascript/resource/external.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:25 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.external
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.external
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.external import *