# terrascript/resource/fortimanager.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:32:29 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.fortimanager
#
# instead of
#
#   >>> import terrascript.resource.fortinetdev.fortimanager
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.fortinetdev.fortimanager import *