# terrascript/resource/heroku.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:37 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.heroku
#
# instead of
#
#   >>> import terrascript.resource.heroku.heroku
#
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.heroku.heroku import *
