# terrascript/resource/http.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:18:58 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.http
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.http
#
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.http import *
