# terrascript/resource/kubernetes.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:10 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.kubernetes
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.kubernetes
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.kubernetes import *