# terrascript/resource/null.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:27 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.null
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.null
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.null import *