# terrascript/resource/oci.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:31 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.oci
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.oci
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.oci import *