# terrascript/resource/oktaasa.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:34 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.oktaasa
#
# instead of
#
#   >>> import terrascript.resource.oktadeveloper.oktaasa
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.oktadeveloper.oktaasa import *