# terrascript/resource/opc.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:36 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.opc
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.opc
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.opc import *