# terrascript/resource/opsgenie.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:38 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.opsgenie
#
# instead of
#
#   >>> import terrascript.resource.opsgenie.opsgenie
#
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.opsgenie.opsgenie import *
