# terrascript/resource/random.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:33:52 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.random
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.random
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.random import *