# terrascript/resource/sematext.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:26:36 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.sematext
#
# instead of
#
#   >>> import terrascript.resource.sematext.sematext
#
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.sematext.sematext import *
