# terrascript/resource/vault.py
# Automatically generated by tools/makecode.py (24-Aug-2021 11:34:31 UTC)
#
# For imports without namespace, e.g.
#
#   >>> import terrascript.resource.vault
#
# instead of
#
#   >>> import terrascript.resource.hashicorp.vault
# 
# This is only available for 'official' and 'partner' providers.

from terrascript.resource.hashicorp.vault import *