# terrascript/vinyldns/__init__.py
# Automatically generated by tools/makecode.py ()

import warnings

warnings.warn(
    "using the 'legacy layout' is deprecated", DeprecationWarning, stacklevel=2
)

import terrascript


class vinyldns(terrascript.Provider):
    pass
