# terrascript/data/invidian/stdlib.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:27:59 UTC)
import terrascript


class stdlib_base64decodehash(terrascript.Data):
    pass


__all__ = [
    "stdlib_base64decodehash",
]
