# terrascript/data/invidian/tls.py
# Automatically generated by tools/makecode.py (24-Sep-2021 15:28:50 UTC)
import terrascript


class tls_certificate(terrascript.Data):
    pass


class tls_public_key(terrascript.Data):
    pass


__all__ = [
    "tls_certificate",
    "tls_public_key",
]
