# terrascript/pingfederate/d.py
# Automatically generated by tools/makecode.py ()

import warnings
warnings.warn("using the 'legacy layout' is deprecated", DeprecationWarning,
              stacklevel=2)
import terrascript


class pingfederate_custom_data_store(terrascript.Data):
    pass


class pingfederate_jdbc_data_store(terrascript.Data):
    pass


class pingfederate_keypair_signing_csr(terrascript.Data):
    pass


class pingfederate_keypair_ssl_server_csr(terrascript.Data):
    pass


class pingfederate_ldap_data_store(terrascript.Data):
    pass


class pingfederate_version(terrascript.Data):
    pass
